/* Plotz © 2011 - 2014 Kevin Reynolds. All rights reserved. */
function pl6b(a,b,d){this.pl73=d;d=document.getElementById("pcan");a?(d.width=a,d.height=b):(a=d.width=window.innerWidth-120,b=d.height=window.innerHeight-0);this.pl74=d.offsetLeft;this.pl75=d.offsetTop;this.pl76=d.getContext("2d");d=document.getElementById("pev");d.style.width=a+"px";d.style.height=a+"px";this.pl77=a;this.pl78=b;this.pl79=a;this.pl7a=b;this.pl7c=this.pl7b=0;this.pl7d=1;this.pl7f=this.pl7e=0;this.pl80=[];this.pl81=[];this.pl82=[];this.pl81[0]=["#000000","#ffff00","#b1b100","#5b5b00"];
this.pl81[1]=["#000000","#c0c0c0","#808080","#5f5f5f"];this.pl81[2]=["#000000","#303060","#202040","#101020"];this.pl81[3]=["#000000","#E0E0E0","#A0A0A0","#808080"];this.pl81[4]=["#808080","#ffffff","#E0E0E0","#C0C0C0"];this.pl81[5]=["#000000","#A00000","#700000","#400000"];this.pl81[6]=["#808080","rgba(255, 255, 255, 0.09)","rgba(224, 224, 224, 0.09)","rgba(192, 192, 192, 0.09)"];this.pl81[7]=["#333333","#FF8C00","#B16100","#5B3200"];this.pl82[0]=["#000000","#b1b100"];this.pl82[1]=["#000000","#808080"];
this.pl82[2]=["#000000","#202040"];this.pl82[3]=["#000000","#A0A0A0"];this.pl82[4]=["#000000","#E0E0E0"];this.pl82[5]=["#000000","#700000"];this.pl82[6]=["#000000","#80c0ff"];this.pl82[7]=["#000000","#B16100"];this.pl83=new pl72(32,32,this);this.pl84=Array(4);for(a=0;4>a;a++)this.pl84[a]=new pl6f(a);this.pl85=document.getElementById("pcon");this.pl85.style.display="none";this.pl86=!1;this.pl87=!0;this.pl88=!1}
pl6b.prototype.pl0=function(){var a=this.pl7d;this.pl7d=4>this.pl7d?2*this.pl7d:1;this.log("zoom="+this.pl7d);if(1<this.pl7d){this.pl87?(this.pl89=document.createElement("canvas"),this.pl89.width=this.pl77,this.pl89.height=this.pl78,this.pl79=this.pl77*this.pl7d,this.pl7a=this.pl78*this.pl7d):(this.pl89=document.createElement("canvas"),this.pl79=this.pl89.width=this.pl77*this.pl7d,this.pl7a=this.pl89.height=this.pl78*this.pl7d);this.pl8a=this.pl89.getContext("2d");var b=(this.pl7b+this.pl77/2)/a,
a=(this.pl7c+this.pl78/2)/a;this.pl8b=this.pl7b=b*this.pl7d-this.pl77/2;this.pl8c=this.pl7c=a*this.pl7d-this.pl78/2;console.log("zoomOffX="+this.pl7b+", this.pl7c="+this.pl7c+", cx="+b+", cy="+a)}else this.pl8a=this.pl89=null,this.pl79=this.pl77,this.pl7a=this.pl78,this.pl7c=this.pl8c=this.pl7b=this.pl8b=0;0==this.pl7e?(this.pl8(),this.pl3()):(this.pl7(),this.pl2())};
pl6b.prototype.pl1=function(a,b,d){a&&(this.pl8d=a,this.pl1a(0));this.pl8e=b;0==this.pl7e?this.pl3():this.pl2();this.pl83.plba!=this.pl8d.length&&(this.pl83.plba=this.pl8d.length);this.pl83.pl56(this.pl8e+1);this.pl16()};
pl6b.prototype.pl2=function(){var a,b,d,e,g,h,k=1==this.pl8d.length;h=this.pl8e>this.pl8d.length-1?this.pl8d.length-1:this.pl8e;var f,n,m;new pl70;1<this.pl7d?(f=this.pl8a,this.pl87?(n=this.pl92-this.pl7b,m=this.pl93-this.pl7c,f.clearRect(0,0,this.pl77,this.pl78)):f.clearRect(0,0,this.pl79,this.pl7a)):(f=this.pl76,n=this.pl92,m=this.pl93);this.pl76.clearRect(0,0,this.pl77,this.pl78);e=this.pl8d[0].length;g=this.pl8d[0][0].length;for(b=0;b<e;b++)for(d=0;d<g;d++)f.drawImage(this.pl94,n+b*this.pl91,
m+d*this.pl90);if(0<h)for(a=this.pl8d[h-1],b=0;b<e;b++)for(d=0;d<g;d++)0<a[b][d]&&f.drawImage(this.pl95,n+b*this.pl91,m+d*this.pl90);a=this.pl8d[h];for(b=0;b<e;b++)for(d=0;d<g;d++)h=a[b][d],0>=h||(f.drawImage(this.pl96[h],n+b*this.pl91,m+d*this.pl90),k&&this.pl8f++);f.beginPath();f.lineWidth=1;f.strokeStyle="#a00000";b=1+n+Math.floor(e/2)*this.pl91-1;f.moveTo(b+.5,m);f.lineTo(b+.5,1+m+g*this.pl90);e%2&&(b+=this.pl91,f.moveTo(b+.5,m),f.lineTo(b+.5,1+m+g*this.pl90));f.stroke();f.beginPath();f.lineWidth=
1;f.strokeStyle="#008000";d=1+m+Math.floor(g/2)*this.pl90-1;f.moveTo(n,d+.5);f.lineTo(1+n+e*this.pl91,d+.5);g%2&&(d+=this.pl90,f.moveTo(n,d+.5),f.lineTo(1+n+e*this.pl91,d+.5));f.stroke();plcd.pla4.plc4&&this.pl20(f);plcd.pla4.plc5&&this.pl21(f);1<this.pl7d&&this.pl87&&this.pl76.drawImage(this.pl89,0,0,this.pl77,this.pl78,0,0,this.pl77,this.pl78)};
pl6b.prototype.pl3=function(){1<this.pl7d?(this.pl76.clearRect(0,0,this.pl77,this.pl78),this.pl87?(this.pl5(),this.pl76.drawImage(this.pl89,0,0,this.pl77,this.pl78,0,0,this.pl77,this.pl78)):(this.pl6(),this.pl76.drawImage(this.pl89,this.pl7b,this.pl7c,this.pl77,this.pl78,0,0,this.pl77,this.pl78))):this.pl4()};
pl6b.prototype.pl4=function(){var a,b,d,e,g,h=this.pl8e>=this.pl8d.length-1,k=this.pl8e>this.pl8d.length-1?this.pl8d.length-1:this.pl8e,f;h&&(this.pl8f=0);this.pl76.clearRect(0,0,this.pl77,this.pl78);for(f=0;f<=k;f++)for(g=this.pl8e<=this.pl8d.length-1&&f==this.pl8e,a=this.pl8d[f],b=0;b<a.length;b++)for(d=0;d<a[b].length;d++)e=a[b][d],0<e&&(h&&this.pl8f++,g&&(e=0),this.pl76.drawImage(this.pl80[e],this.pl92+(b-d)*this.pl97,this.pl93+(b+d)*this.pl98/2-f*this.pl98));document.getElementById("pbc").innerHTML=
this.pl8f};pl6b.prototype.pl5=function(){var a,b,d,e,g,h=this.pl8e>=this.pl8d.length-1,k=this.pl8e>this.pl8d.length-1?this.pl8d.length-1:this.pl8e,f,n=0+this.pl92-this.pl8b,m=0+this.pl93-this.pl8c;this.pl8a.clearRect(0,0,this.pl77,this.pl78);for(f=0;f<=k;f++)for(g=this.pl8e<=this.pl8d.length-1&&f==this.pl8e,a=this.pl8d[f],b=0;b<a.length;b++)for(d=0;d<a[b].length;d++)e=a[b][d],0<e&&(h&&this.pl8f++,g&&(e=0),this.pl8a.drawImage(this.pl80[e],n+(b-d)*this.pl97,m+(b+d)*this.pl98/2-f*this.pl98))};
pl6b.prototype.pl6=function(){var a,b,d,e,g,h=this.pl8e>=this.pl8d.length-1,k=this.pl8e>this.pl8d.length-1?this.pl8d.length-1:this.pl8e,f;this.pl8a.clearRect(0,0,this.pl79,this.pl7a);for(f=0;f<=k;f++)for(g=this.pl8e<=this.pl8d.length-1&&f==this.pl8e,a=this.pl8d[f],b=0;b<a.length;b++)for(d=0;d<a[b].length;d++)e=a[b][d],0<e&&(h&&this.pl8f++,g&&(e=0),this.pl8a.drawImage(this.pl80[e],this.pl92+(b-d)*this.pl97,this.pl93+(b+d)*this.pl98/2-f*this.pl98))};
pl6b.prototype.pl7=function(){var a=this.pl8d[0].length,b=this.pl8d[0][0].length;this.pl77/a<this.pl78/b?this.pl90=this.pl91=Math.floor((this.pl77-40)/a)*this.pl7d:this.pl91=this.pl90=Math.floor((this.pl78-40)/b)*this.pl7d;this.pl92=Math.floor((this.pl77*this.pl7d-a*this.pl91)/2);this.pl93=Math.floor((this.pl78*this.pl7d-b*this.pl90)/2);this.pl94=this.pl9("#e0e0e0","#ffffff");this.pl95=this.pl9("#a0a0a0","#e8e8e8");this.pl96=[];for(a=0;a<this.pl82.length;a++)this.pl96[a]=this.pl9(this.pl82[a][0],
this.pl82[a][1])};
pl6b.prototype.pl8=function(){var a,b,d,e,g,h,k=-1E4,f=-1E4,n=1E4,m=1E4,l;e=this.pl8d.length;g=this.pl8d[0].length;h=this.pl8d[0][0].length;for(a=0;a<e;a++)for(b=0;b<g;b++)for(d=0;d<h;d++)0<this.pl8d[a][b][d]&&(l=64*(b-d)/2,l<n&&(n=l),l>k&&(k=l),l=36*(b+d)/2-36*a,l<m&&(m=l),l>f&&(f=l));(k-n)/this.pl77>(f-m)/this.pl78?(this.pl91=Math.floor((this.pl77-40)/((k-n)/64+1)*this.pl7d),this.pl90=Math.round(72*this.pl91/64)):(this.pl90=Math.floor((this.pl78-40)/((f-m)/72+1)*this.pl7d),this.pl91=Math.round(64*
this.pl90/72));this.pl92=Math.floor((this.pl79-(k+n)/64*this.pl91-this.pl91)/2);this.pl93=Math.floor((this.pl7a-(f+m)/72*this.pl90-this.pl90)/2);this.pl97=this.pl91/2;this.pl98=this.pl90/2;for(a=0;a<this.pl81.length;a++)this.pl80[a]=this.pla(a)};pl6b.prototype.pl9=function(a,b){var d=document.createElement("canvas");d.width=this.pl91+2;d.height=this.pl90+2;var e=d.getContext("2d");e.strokeStyle=a;e.fillStyle=b;e.lineWidth=1;e.beginPath();e.rect(.5,.5,this.pl91,this.pl90);e.fill();e.stroke();return d};
pl6b.prototype.pla=function(a){var b=Array(7);b[0]=[.5*this.pl91,0];b[1]=[this.pl91,.25*this.pl90];b[2]=[this.pl91,.75*this.pl90];b[3]=[.5*this.pl91,this.pl90];b[4]=[0,.75*this.pl90];b[5]=[0,.25*this.pl90];b[6]=[.5*this.pl91,.5*this.pl90];var d=document.createElement("canvas");d.width=this.pl91+1;d.height=this.pl90+1;var e=d.getContext("2d");e.lineWidth=.75;e.strokeStyle=this.pl81[a][0];e.beginPath();e.moveTo(.5+b[0][0],.5+b[0][1]);e.lineTo(.5+b[1][0],.5+b[1][1]);e.lineTo(.5+b[6][0],.5+b[6][1]);e.lineTo(.5+
b[5][0],.5+b[5][1]);e.closePath();e.fillStyle=this.pl81[a][1];e.fill();e.stroke();e.beginPath();e.moveTo(.5+b[5][0],.5+b[5][1]);e.lineTo(.5+b[6][0],.5+b[6][1]);e.lineTo(.5+b[3][0],.5+b[3][1]);e.lineTo(.5+b[4][0],.5+b[4][1]);e.closePath();e.fillStyle=this.pl81[a][2];e.fill();e.stroke();e.beginPath();e.moveTo(.5+b[1][0],.5+b[1][1]);e.lineTo(.5+b[2][0],.5+b[2][1]);e.lineTo(.5+b[3][0],.5+b[3][1]);e.lineTo(.5+b[6][0],.5+b[6][1]);e.closePath();e.fillStyle=this.pl81[a][3];e.fill();e.stroke();return d};
pl6b.prototype.plb=function(a,b,d,e){this.pl76.drawImage(this.pl80,this.pl92+(b-d)*this.pl97,this.pl93+(b+d)*this.pl98/2-a*this.pl98)};pl6b.prototype.plc=function(a){if(this.pl83.pl57(a.clientX,a.clientY))this.pl7f=1,this.pl83.pl58(a.clientX,a.clientY);else{var b;for(b=0;b<this.pl84.length;b++)if(this.pl84[b].pl57(a.clientX,a.clientY)){this.pl7f=3;this.pl99=b;this.pl84[b].pl58(a.clientX,a.clientY);return}1<this.pl7d&&(this.pl7f=2,this.pl12(a.clientX,a.clientY))}};
pl6b.prototype.pld=function(a){this.log("touchStart"+a.touches);if(this.pl83.pl57(a.touches[0].pageX,a.touches[0].pageY))this.log("dragMode = 1"),this.pl7f=1,this.pl83.pl58(a.touches[0].pageX,a.touches[0].pageY);else{var b;for(b=0;b<this.pl84.length;b++)if(this.pl84[b].pl57(a.touches[0].pageX,a.touches[0].pageY)){this.pl7f=3;this.pl99=b;this.pl84[b].pl58(a.touches[0].pageX,a.touches[0].pageY);return}1<this.pl7d&&(this.pl7f=2,this.pl12(a.touches[0].pageX,a.touches[0].pageY))}};
pl6b.prototype.ple=function(a){1==this.pl7f?this.pl83.pl59(a.touches[0].pageX,a.touches[0].pageY):2==this.pl7f?this.pl13(a.touches[0].pageX,a.touches[0].pageY):3==this.pl7f&&this.pl84[this.pl99].pl59(a.touches[0].pageX,a.touches[0].pageY)};pl6b.prototype.plf=function(a){1==this.pl7f?this.pl83.pl59(a.clientX,a.clientY):2==this.pl7f?this.pl13(a.clientX,a.clientY):3==this.pl7f&&this.pl84[this.pl99].pl59(a.clientX,a.clientY)};
pl6b.prototype.pl10=function(a){1==this.pl7f?this.pl83.pl5a():2==this.pl7f?this.pl14():3==this.pl7f&&this.pl84[this.pl99].pl5a();this.pl7f=0};pl6b.prototype.pl11=function(a){1==this.pl7f?this.pl83.pl5a():2==this.pl7f?this.pl14():3==this.pl7f&&this.pl84[this.pl99].pl5a();this.pl7f=0};pl6b.prototype.pl12=function(a,b){this.pl9a=a;this.pl9b=b};
pl6b.prototype.pl13=function(a,b){var d=this.pl7b+this.pl9a-a,e=this.pl7c+this.pl9b-b;0>d&&(a+=d,d=0);0>e&&(b+=e,e=0);d>this.pl79-this.pl77&&(a=a+d-(this.pl79-this.pl77),d=this.pl79-this.pl77);e>this.pl7a-this.pl78&&(b=b+e-(this.pl7a-this.pl78),e=this.pl7a-this.pl78);this.pl8b=d;this.pl8c=e;this.pl76.clearRect(0,0,this.pl77,this.pl78);this.pl87?this.pl76.drawImage(this.pl89,0,0,this.pl77,this.pl78,a-this.pl9a,b-this.pl9b,this.pl77,this.pl78):this.pl76.drawImage(this.pl89,d,e,this.pl77,this.pl78,0,
0,this.pl77,this.pl78)};pl6b.prototype.pl14=function(){this.pl7b=this.pl8b;this.pl7c=this.pl8c;console.log("panStop() - "+this.pl7b+", "+this.pl7c);this.pl87&&(this.pl76.clearRect(0,0,this.pl77,this.pl78),0==this.pl7e?this.pl5():this.pl2(),this.pl76.drawImage(this.pl89,0,0,this.pl77,this.pl78,0,0,this.pl77,this.pl78))};pl6b.prototype.log=function(a){this.pl85.innerHTML+=a+"<br/>";this.pl85.scrollTop=this.pl85.scrollHeight};
pl6b.prototype.pl15=function(a,b){a.preventDefault();var d=plcd.pla3;if(d.pl9c)b();else{var e;s=a.target.className;if("bn"!=s.substring(s.length-2)){e=a.target.getElementsByTagName("div");if(0==e.length){setTimeout(b,10);return}e=e[0]}else e=a.target;e.style.background="#ffffff";e.style.color="#000000";d.pl9c=e;setTimeout(b,10)}};pl6b.prototype.pl16=function(){this.pl9c&&(this.pl9c.style.background="#000000",this.pl9c.style.color="#ffffff",this.pl9c=null)};
pl6b.prototype.pl17=function(){var a=document.getElementById("ppro");a.style.left=(this.pl77-a.offsetWidth)/2+"px";a.style.top=this.pl78/2-32+"px";a.style.visibility="visible"};pl6b.prototype.pl18=function(a){document.getElementById("ppro").innerHTML=a};pl6b.prototype.pl19=function(){document.getElementById("ppro").style.visibility="hidden"};
pl6b.prototype.pl1a=function(a){document.getElementById("seglbn").style.background=0==a?"#003000":"#808080";document.getElementById("seglbn").style.color=0==a?"#ffffff":"#000000";document.getElementById("segrbn").style.background=0==a?"#808080":"#003000";document.getElementById("segrbn").style.color=0==a?"#000000":"#ffffff";this.pl7e=a;0==a?this.pl8():this.pl7()};pl6b.prototype.pl1b=function(){plcd.pla4.pl1b(parseInt(plcd.pla3.pl9c.id.substring(1)))};pl6b.prototype.pl1c=function(){plcd.pla4.pl1c(parseInt(plcd.pla3.pl9c.id.substring(1)))};
pl6b.prototype.pl1d=function(){for(var a=0,b="";;){el=document.getElementById("tl"+a);if(!el)break;b+=el.innerHTML+"<br/>";a++}a=40*++a;document.getElementById("pvl").style.height=a+"px";document.getElementById("pvlp").innerHTML=b};pl6b.prototype.pl1e=function(){this.pl88=!1;this.pl1f();document.getElementById("pctl").style.visibility="visible"};
pl6b.prototype.pl1f=function(){console.log("hideValues");for(i=0;i<this.pl84.length;i++)document.getElementById("pv"+i+"bn0").style.visibility="hidden",document.getElementById("pv"+i+"bn1").style.visibility="hidden",document.getElementById("pvrl"+i).style.visibility="hidden",document.getElementById("pvkn"+i).style.visibility="hidden";document.getElementById("pvl").style.visibility="hidden"};
pl6b.prototype.pl20=function(a){var b=this.pl8d[this.pl8e>this.pl8d.length-1?this.pl8d.length-1:this.pl8e],d=Math.floor((b.length+1)/2-1),e=Math.floor((b[0].length+1)/2-1),g,h,k,f,n,m,l,q=[],t=0;1<this.pl7d&&this.pl87?(g=this.pl92-this.pl7b,h=this.pl93-this.pl7c):(g=this.pl92,h=this.pl93);14<this.pl90?(m=Math.floor((this.pl90-14)/2),a.font="bold 14px Helvetica"):(m=0,a.font="bold "+this.pl90+"px Helvetica");for(k=0;k<=d;k++){for(f=0;0>=b[k][f]&&f<=e;)f++;if(!(f>e)){l=1;n=f+1;if(0==k)for(;0<b[k][n]&&
n<=e;)n++,l++;else for(;0<b[k][n]&&0>=b[k-1][n]&&n<=e;)n++,l++;n=!1;1==l&&0<f&&0<b[k+1][f-1]&&(0==k||0>=b[k-1][f])&&(n=!0);if(n||1<l)n?q[t++]=new pl6c(l,g+k*this.pl91,h+m+f*this.pl90-this.pl90,"top","right"):q[t++]=new pl6c(l,g+k*this.pl91-1,h+m+f*this.pl90+Math.floor(l*this.pl90/2)-this.pl90/2,"top","right")}}for(f=0;f<=e;f++){for(k=0;0>=b[k][f]&&k<=d;)k++;if(!(k>d)){l=1;m=k+1;if(0==f)for(;0<b[m][f]&&m<=d;)m++,l++;else for(;0<b[m][f]&&0>=b[m][f-1]&&m<=d;)m++,l++;1<l&&(q[t++]=new pl6c(l,g+k*this.pl91+
Math.floor(l*this.pl91/2),h+f*this.pl90,"bottom","center"))}}this.pl22(a,q)};
pl6b.prototype.pl21=function(a){var b=this.pl8d[this.pl8e>this.pl8d.length-1?this.pl8d.length-1:this.pl8e],d=Math.floor((b.length+1)/2-1),e=Math.floor((b[0].length+1)/2-1),g,h,k,f,n,m,l,q=[],t=0;1<this.pl7d&&this.pl87?(g=this.pl92-this.pl7b,h=this.pl93-this.pl7c):(g=this.pl92,h=this.pl93);14<this.pl90?(l=Math.floor((this.pl90-14)/2),a.font="bold 14px Helvetica"):(l=0,a.font="bold "+this.pl90+"px Helvetica");a.fillStyle="#000";a.textBaseline="top";a.textAlign="left";var r=Math.floor(this.pl90/2);for(k=
d;0<=k;k--){for(f=e;0<=f&&0>=b[k][f];)f--;if(!(0>f)){m=1;n=f-1;if(0==k)for(;0<=n&&0<b[k][n];)n--,m++;else for(;0<=n&&0<b[k][n]&&0>=b[k+1][n];)n--,m++;n=!1;1==m&&f<e&&0<b[k+1][f-1]&&0>=b[k+1][f]&&(0==k||0<b[k-1][f+1])&&(n=!0);if(n||1<m)n?q[t++]=new pl6c(m,g+1+(k+1)*this.pl91,h+(f+1)*this.pl90,"top","bottom"):q[t++]=new pl6c(m,g+1+(k+1)*this.pl91,h+l+(f+1)*this.pl90-m*this.pl90/2-r,"top","bottom");if(f==e)break}}for(f=e-1;0<=f;f--){for(k=d;0<=k&&0>=b[k][f];)k--;if(!(0>k)){m=1;for(e=k-1;0<=e&&0<b[e][f]&&
0>=b[e][f+1];)e--,m++;1<m&&(q[t++]=new pl6c(m,g+1+(k+1)*this.pl90-m*this.pl91/2-r/2,h+(f+1)*this.pl91,"top","bottom"));if(k==d)break}}this.pl22(a,q)};
pl6b.prototype.pl22=function(a,b){var d=65535,e=0,g=0,h=["#c00000","#008000","#0000c0"];for(c=0;c<b.length;c++){yp=-1;for(idx=0;idx<b.length;idx++)b[idx].pl9f<d&&b[idx].pl9f>yp&&(yp=b[idx].pl9f,yFound=idx);d=yp;a.fillStyle=h[g];a.textBaseline=b[yFound].pla0;a.textAlign=b[yFound].pla1;a.fillText(b[yFound].pl9d,b[yFound].pl9e,b[yFound].pl9f);5<=++e&&(e=0,++g>=h.length&&(g=0))}};
pl6b.prototype.pl23=function(){var a=plcd.pla3,b=document.getElementById("pcan");b.width=window.innerWidth-120;b.height=window.innerHeight;a.pl89&&(a.pl89.width=b.width,a.pl89.height=b.height);a.pl77=window.innerWidth-120;a.pl78=window.innerHeight;a.pl79=a.pl77*a.pl7d;a.pl7a=a.pl78*a.pl7d;0==a.pl7e?(a.pl8(),a.pl3()):(a.pl7(),a.pl2());a.pl83.pl6a();document.getElementById("pvl");"visible"==pvl.style.visibility&&plcd.pla4.pl68()};
function pl6c(a,b,d,e,g){this.pl9d=a;this.pl9e=b;this.pl9f=d;this.pla0=e;this.pla1=g}function pl6d(a){this.pl73=a;this.pla2=0}pl6d.prototype.pl24=function(){/*var a=new XMLHttpRequest;a.open("GET","/plotzhtml5/ptb.php",!1);a.send(null);200===a.status&&(document.getElementById("ptb").innerHTML=a.responseText)*/;this.pla3=new pl6b(0,0,this.pl73);this.pla4=new pl71(this.pla3);this.pla4.pl5d();this.pla4.pl29();this.pl29();this.pla3.pl1d();this.pl28(!0);this.pla4.pl68()};
pl6d.prototype.pl28=function(a){var b=a?"visible":"hidden";document.getElementById("pctl").style.visibility=b;document.getElementById("ptb").style.visibility=b;document.getElementById("pslrl").style.visibility=b;document.getElementById("pslbn0").style.visibility=b;document.getElementById("pslbn1").style.visibility=b;document.getElementById("pslkn").style.visibility=b;document.getElementById("pcon").style.visibility=b;document.getElementById("pbc").style.visibility=b;a||this.pla3.pl88&&this.pla3.pl1f()};
pl6d.prototype.pl29=function(){var a;this.pl73?(a="touchstart",document.getElementById("pev").addEventListener("touchstart",this.pl2f,!1),document.getElementById("pev").addEventListener("touchmove",this.pl33,!1),document.getElementById("pev").addEventListener("touchend",this.pl34,!1)):(a="click",document.getElementById("pev").addEventListener("click",this.pl2e,!1),document.getElementById("pev").addEventListener("mousedown",this.pl30,!1),document.getElementById("pev").addEventListener("mousemove",
this.pl31,!1),document.getElementById("pev").addEventListener("mouseout",this.pl32,!1),document.getElementById("pev").addEventListener("mouseup",this.pl32,!1));document.getElementById("pslbn0").addEventListener(a,function(a){plcd.pla3.pl15(a,plcd.pl2c)},!1);document.getElementById("pslbn1").addEventListener(a,function(a){plcd.pla3.pl15(a,plcd.pl2d)},!1);document.getElementById("ptbz").addEventListener(a,function(a){plcd.pla3.pl15(a,plcd.pl0)},!1);document.getElementById("ptbiso").addEventListener(a,
function(a){plcd.pl35()},!1);document.getElementById("ptbflt").addEventListener(a,function(a){plcd.pl36()},!1);document.getElementById("ptbm").addEventListener(a,function(a){a.preventDefault();plcd.pl2b()},!1);document.getElementById("pvlhd").addEventListener(a,function(a){plcd.pla3.pl1e()},!1);var b;for(b=0;b<this.pla3.pl84.length;b++)document.getElementById("pv"+b+"bn0").addEventListener(a,function(a){plcd.pla3.pl15(a,plcd.pla3.pl1b)},!1),document.getElementById("pv"+b+"bn1").addEventListener(a,
function(a){plcd.pla3.pl15(a,plcd.pla3.pl1c)},!1);window.onresize=function(a){pto&&clearTimeout(pto);pto=setTimeout(plcd.pla3.pl23,200)};"onorientationchange"in window&&(window.onorientationchange=function(a){pto=setTimeout(plcd.pla3.pl23,10)})};pl6d.prototype.pl2a=function(){alert("objectUpdate")};pl6d.prototype.pl2b=function(){/*window.top.location.href="/plotz-menu.php"*/};
pl6d.prototype.pl0=function(){plcd.pla3.pl0();document.getElementById("ptbzv").innerHTML=1==plcd.pla3.pl7d?"100%":100*plcd.pla3.pl7d+"%";plcd.pla3.pl16()};pl6d.prototype.pl2c=function(a){plcd.pla3.pl86||(a=plcd.pla3.pl8e,a<plcd.pla3.pl8d.length?(a++,plcd.pla3.pl1(null,a,-1)):plcd.pla3.pl16())};pl6d.prototype.pl2d=function(a){plcd.pla3.pl86||(a=plcd.pla3.pl8e,1==plcd.pla3.pl7e&&plcd.pla3.pl8e>=plcd.pla3.pl8d.length&&a--,a?(a--,plcd.pla3.pl1(null,a,-1)):plcd.pla3.pl16())};pl6d.prototype.pl2e=function(a){};
pl6d.prototype.pl2f=function(a){a.preventDefault();plcd.pla3.pld(a)};pl6d.prototype.pl30=function(a){plcd.pla3.plc(a)};pl6d.prototype.pl31=function(a){plcd.pla3.plf(a)};pl6d.prototype.pl32=function(a){plcd.pla3.pl11(a)};pl6d.prototype.pl33=function(a){plcd.pla3.ple(a)};pl6d.prototype.pl34=function(a){plcd.pla3.pl10(a)};pl6d.prototype.pl35=function(){plcd.pl37(0)};pl6d.prototype.pl36=function(){plcd.pl37(1)};pl6d.prototype.pl37=function(a){this.pla3.pl1a(a);this.pla3.pl1(null,this.pla3.pl8e,-1)};var plcd;
function plce(){plcd=new pl6d(touch);plcd.pl24()}window.onload=setTimeout(plce,100);function pl6e(a,b,d){this.pla5=a;this.pla6=b;this.pla7=1;this.pl38(a,b,d)}pl6e.prototype.pl38=function(a,b,d){this.pl8d=Array(a);var e;for(e=0;e<a;e++)this.pl8d[e]=this.pl3a(b,d)};pl6e.prototype.pl39=function(a,b){var d;this.pla8=Array(a);for(d=0;d<a;d++)this.pla8[d]=new Int8Array(b)};pl6e.prototype.pl3a=function(a,b){var d=Array(a),e,g;for(e=0;e<a;e++)for(d[e]=new Int8Array(b),g=0;g<b;g++)d[e][g]=-1;return d};
pl6e.prototype.pl3b=function(a,b,d,e,g){var h=Math.abs(d-a),k=Math.abs(e-b),f=k&1,n=4*(1-h)*k*k,m=4*(f+1)*h*h,l=n+m+f*h*h,q,t=this.pla7;a>d&&(a=d,d+=h);b>e&&(b=e);b+=Math.floor((k+1)/2);e=b-f;h*=8*h;f=8*k*k;do g[d][b]=t,g[a][b]=t,g[a][e]=t,g[d][e]=t,q=2*l,q>=n&&(a++,d--,l+=n+=f),q<=m&&(b++,e--,l+=m+=h);while(a<=d);for(;b-e<k;)g[a-1][++b]=t,g[a-1][--e]=t};
pl6e.prototype.pl3c=function(a,b){switch(this.pla9){case 0:this.pl8d[this.plaa][a][b]=this.pla7;break;case 1:this.pl8d[b][this.plaa][a]=this.pla7;break;case 2:this.pl8d[b][a][this.plaa]=this.pla7}};pl6e.prototype.pl3d=function(a,b){switch(this.pla9){case 0:return this.pl8d[this.plaa][a][b];case 1:return this.pl8d[b][this.plaa][a];case 2:return this.pl8d[b][a][this.plaa]}return 0};
pl6e.prototype.pl3e=function(a,b,d,e,g,h){var k=Math.abs(d-a),f=Math.abs(e-b),n=f&1,m=4*(1-k)*f*f,l=4*(n+1)*k*k,q=m+l+n*k*k;this.pla9=g;this.plaa=h;a>d&&(a=d,d+=k);b>e&&(b=e);b+=Math.floor((f+1)/2);e=b-n;k*=8*k;n=8*f*f;do this.pl3c(d,b),this.pl3c(a,b),this.pl3c(a,e),this.pl3c(d,e),g=2*q,g>=m&&(a++,d--,q+=m+=n),g<=l&&(b++,e--,q+=l+=k);while(a<=d);for(;b-e<f;)this.pl3c(a-1,++b),this.pl3c(a-1,--e)};
pl6e.prototype.pl3f=function(a,b){var d,e,g,h=this.pl8d[0].length;for(e=0;e<h;e++){for(d=0;d<h&&-1==this.pl8d[a][d][e];)d++;if(!(d>=h)){for(;d<h&&1<=this.pl8d[a][d][e];)d++;for(g=h-d;d<g;)this.pl8d[a][d++][e]=b}}};pl6e.prototype.pl40=function(a,b){var d,e,g;for(d=a;d<=b;d++)for(e=a;e<=b;e++)for(g=a;g<=b;g++)this.pl8d[d][e][g]=0};
pl6e.prototype.pl41=function(a,b){var d,e,g,h,k;h=this.pl8d[0].length;for(g=0;g<h;g++){for(d=0;d<h&&0>=this.pl8d[a][d][g];)d++;if(!(d>=h||0<this.pl8d[b][d][g])){for(;0<this.pl8d[a][d][g];)d++;k=h-d;for(e=h-1-d;d<k&&!(0<this.pl8d[b][d][g]);)this.pl8d[a][d][g]=this.pla7,this.pl8d[a][e][g]=this.pla7,d++,e--}}};
pl6e.prototype.pl44=function(a,b,d){d=3;var e=b*d,g=this.pl3a(e,e),h,k=Math.floor((b+1)/4),f,n,m=Math.floor(d*d*d/8),l=Math.floor((b+1)/2),q=b-1;console.log("prec "+d+", quadLimit"+m);new pl70;h=Array(d);for(f=0;f<d;f++)h[f]=this.pl3a(e,e);this.pl3b(0,0,e-1,e-1,g);for(a&&(zpSoFar=0);zpSoFar<k;){n=zpSoFar*d;for(a=0;a<d;a++){for(f=0;f<e;f++)for(k=0;k<e;k++)h[a][f][k]=-1;for(f=0;f<e&&!(0<g[f][n]);f++);this.pl3b(f,f,e-f-1,e-f-1,h[a]);this.pl48(h[a],1)}for(e=0;e<l;e++)for(g=0;g<l;g++){for(a=f=0;a<d;a++)f+=
this.pl4a(h[a],e*d,g*d,d);f>m&&(this.pl8d[zpSoFar][e][g]=1,this.pl8d[zpSoFar][q-e][g]=1,this.pl8d[zpSoFar][e][q-g]=1,this.pl8d[zpSoFar][q-e][q-g]=1,this.pl8d[g][zpSoFar][e]=1,this.pl8d[g][zpSoFar][q-e]=1,this.pl8d[g][e][zpSoFar]=1,this.pl8d[g][q-e][zpSoFar]=1,this.pl8d[g][e][q-zpSoFar]=1,this.pl8d[g][q-e][q-zpSoFar]=1,this.pl8d[g][q-zpSoFar][e]=1,this.pl8d[g][q-zpSoFar][q-e]=1)}break}this.pl8d[b-1]=this.pl8d[0];d=Math.floor((b+1)/2);for(h=1;h<d;h++)this.pl45(h,h-1),this.pl8d[b-1-h]=this.pl8d[h];return!0};
pl6e.prototype.pl42=function(a,b,d,e){var g=b*d,h=this.pl3a(g,g),k=this.pl3a(g,g),f,n=Math.floor((b+1)/4),m=Math.floor((d+1)/2-1),l,q=Math.floor(d*d/2),t=Math.floor((b+1)/2),r=b-1,u=new pl70;this.pl3b(0,0,g-1,g-1,h);a&&(this.plab=0);for(;this.plab<n;this.plab++){l=this.plab*d+m;for(a=0;a<g;a++)for(f=0;f<g;f++)k[a][f]=-1;for(a=0;a<g&&!(0<h[a][l]);a++);if(0!=this.plab)for(this.pl3b(a,a,g-a-1,g-a-1,k),this.pl48(k,1),a=0;a<t;a++)for(f=0;f<t;f++)this.pl4a(k,a*d,f*d,d)>q&&(this.pl8d[this.plab][a][f]=this.pla7,
this.pl8d[this.plab][r-a][f]=this.pla7,this.pl8d[this.plab][a][r-f]=this.pla7,this.pl8d[this.plab][r-a][r-f]=this.pla7,this.pl8d[f][this.plab][a]=this.pla7,this.pl8d[f][this.plab][r-a]=this.pla7,this.pl8d[f][a][this.plab]=this.pla7,this.pl8d[f][r-a][this.plab]=this.pla7,this.pl8d[f][a][r-this.plab]=this.pla7,this.pl8d[f][r-a][r-this.plab]=this.pla7,this.pl8d[f][r-this.plab][a]=this.pla7,this.pl8d[f][r-this.plab][r-a]=this.pla7);else for(a=Math.round(a/d),this.pl3b(a,a,r-a,r-a,this.pl8d[0]),this.pl48(this.pl8d[0],
this.pla7),p=this.pl8d[0],a=0;a<t;a++)for(f=0;f<t;f++)0<p[a][f]&&(this.pl8d[f][this.plab][a]=this.pla7,this.pl8d[f][this.plab][r-a]=this.pla7,this.pl8d[f][a][this.plab]=this.pla7,this.pl8d[f][r-a][this.plab]=this.pla7,this.pl8d[f][a][r-this.plab]=this.pla7,this.pl8d[f][r-a][r-this.plab]=this.pla7,this.pl8d[f][r-this.plab][a]=this.pla7,this.pl8d[f][r-this.plab][r-a]=this.pla7);if(e&&500<u.pl5c())return!1}this.pl8d[b-1]=this.pl8d[0];d=Math.floor((b+1)/2);for(e=1;e<d;e++)this.pl45(e,e-1),this.pl8d[b-
1-e]=this.pl8d[e];return!0};pl6e.prototype.pl45=function(a,b){for(var d=this.pl8d[a],e=this.pl8d[b],g=Math.floor((d.length+1)/2)-1,h=Math.floor((d[0].length+1)/2)-1,k=d.length-1,f=d[0].length-1,n=0;n<g&&!(0<d[n][h]);)n++;for(var m=0;m<h&&!(0<d[g][m]);)m++;var l;m++;for(l=h;l>=m;l--){for(h=n;h<=g&&!(0<d[h++][l]););for(;h<=g&&!(0<d[h][l-1]&&-1!=e[h][l]);)h++;for(;h<=g;)d[h][l]=0,d[h][f-l]=0,d[k-h][l]=0,d[k-h][f-l]=0,h++}};
pl6e.prototype.pl46=function(a,b,d,e,g){var h=b*g,k=d*g,f=e*g,n=this.pl3a(h,f),m=this.pl3a(k,f),l=this.pl3a(h,k),q=Math.floor((e+1)/2),t=Math.floor((g+1)/2-1),r,u=Math.floor(g*g/2),w=Math.floor((b+1)/2),x=Math.floor((d+1)/2);b-=1;d-=1;var v=new pl70;this.pl3b(0,0,h-1,f-1,n);this.pl3b(0,0,k-1,f-1,m);a&&(this.plab=0);for(;this.plab<q;this.plab++){r=this.plab*g+t;for(a=0;a<h;a++)for(f=0;f<k;f++)l[a][f]=-1;for(a=0;a<h&&!(0<n[a][r]);a++);for(f=0;f<k&&!(0<m[f][r]);f++);this.pl3b(a,f,h-a-1,k-f-1,l);this.pl48(l,
1);for(a=0;a<w;a++)for(f=0;f<x;f++)this.pl4a(l,a*g,f*g,g)>u&&(this.pl8d[this.plab][a][f]=1,this.pl8d[this.plab][b-a][f]=1,this.pl8d[this.plab][a][d-f]=1,this.pl8d[this.plab][b-a][d-f]=1);if(500<v.pl5c())return!1}this.pl8d[e-1]=this.pl8d[0];for(g=1;g<q;g++)this.pl45(g,g-1),this.pl8d[e-1-g]=this.pl8d[g];return!0};
pl6e.prototype.pl47=function(a,b,d,e,g,h){var k=Math.floor((h+1)/2-1);e*=h;var f=Math.floor((g+1)/2),n=b*h,m=d*h,l,q=this.pl3a(e,e),t=this.pl3a(n,m),r=Math.floor((b+1)/2),u=Math.floor((d+1)/2);b-=1;d-=1;var w=Math.floor(h*h/2);this.pl3b(0,0,e-1,e-1,q);var x=new pl70;a&&(this.plab=0);for(;this.plab<f;this.plab++){if(500<x.pl5c())return!1;l=this.plab*h+k;for(a=0;a<e&&!(0<q[a][l]);a++);var v;for(l=0;l<n;l++)for(v=0;v<m;v++)t[l][v]=-1;l=a;this.pl3b(l,l,n-1-l,n-1-l,t);l=e-a-1;this.pl3b(l,l,n-1-l,n-1-l,
t);this.pl49(t,1);for(l=0;l<r;l++)for(a=0;a<u;a++)this.pl4a(t,l*h,a*h,h)>w&&(this.pl8d[this.plab][l][a]=1,this.pl8d[this.plab][b-l][a]=1,this.pl8d[this.plab][l][d-a]=1,this.pl8d[this.plab][b-l][d-a]=1);if(this.plab)for(a=u-1;0<a;a--){for(l=0;l<r&&!(0<this.pl8d[this.plab][l][a]);)l++;if(l==r)break;for(l++;l<r&&0>=this.pl8d[this.plab][l][a-1];)l++;for(;l<r&&!(0>this.pl8d[this.plab][l+1][a])&&!(0>this.pl8d[this.plab][l][a+1]);)0<=this.pl8d[this.plab-1][l][a]&&(this.pl8d[this.plab][l][a]=0,this.pl8d[this.plab][b-
l][a]=0,this.pl8d[this.plab][l][d-a]=0,this.pl8d[this.plab][b-l][d-a]=0),l++}this.pl8d[g-1-this.plab]=this.pl8d[this.plab]}return this.plab>=f};pl6e.prototype.pl48=function(a,b){var d,e,g,h=a.length,k=a[0].length;for(e=0;e<k;e++){for(d=0;d<h&&-1==a[d][e];)d++;if(!(d>=h)){for(;d<h&&1<=a[d][e];)d++;for(g=h-d;d<g;)a[d++][e]=b}}};
pl6e.prototype.pl49=function(a,b){var d=Math.floor((a.length+1)/2),e=Math.floor((a[0].length+1)/2),g,h,k,f=a.length-1,n=a[0].length-1;for(h=0;h<e;h++){for(g=0;g<d&&-1==a[g][h];)g++;if(!(g>=d-1)){for(;g<d&&1<=a[g][h];)g++;if(!(g>=d-1)){for(k=g+1;k<d&&-1==a[k][h];)k++;if(!(k>=d))for(;g<=d&&-1==a[g][h];)a[g][h]=b,a[g][n-h]=b,a[f-g][h]=b,a[f-g][n-h]=b,g++}}}for(g=0;g<d;g++){for(h=0;h<e&&-1==a[g][h];)h++;if(!(h>=e-1)){for(;h<e&&1<=a[g][h];)h++;if(!(h>=e-1)){for(k=h+1;k<e&&-1==a[g][k];)k++;if(!(k>=e))for(;h<
e&&-1==a[g][h];)a[g][h]=b,a[g][n-h]=b,a[f-g][h]=b,a[f-g][n-h]=b,h++}}}};pl6e.prototype.pl4a=function(a,b,d,e){var g=b+e;e=d+e;for(var h,k=0;b<g;b++)for(h=d;h<e;h++)0<a[b][h]&&k++;return k};pl6e.prototype.pl4b=function(a,b,d){var e,g,h;for(e=0;e<b;e++){h="";for(g=0;g<d;g++)h+=0<a[e][g]?"*":"-";console.log(h)}};pl6e.prototype.pl4c=function(a,b,d,e,g){for(var h=0,k=0,f=0,n,h=b;h<a.length;h++){b=e;for(k=0;k<a.length;k++){n=g;for(f=0;f<a.length;f++)this.pl8d[d][b][n++]=a[h][k][f];b++}d++}};
pl6e.prototype.pl4d=function(a,b){var d,e;for(d=0;d<a.length;d++)for(e=0;e<a[d].length;e++)b[d][e]=a[d][e]};pl6e.prototype.pl4e=function(a,b){var d,e;for(d=0;d<a.length;d++)for(e=0;e<a[d].length;e++)b[d][e]=0<a[d][e]?0:b[d][e]};
pl6e.prototype.pl4f=function(a,b,d,e,g){var h,k,f,n,m,l,q,t,r,u;m=a.length;l=b.length;f=d+l<=m?d+l:m;m=a[0].length;l=b[0].length;n=e+l<=m?e+l:m;m=a[0][0].length;l=b[0][0].length;m=g+l<=m?g+l:m;for(l=q=t=0;d<f;d++){for(h=e;h<n;h++){for(k=g;k<m;k++)r=b[l][q][t],u=a[d][h][k],-1==u&&(a[d][h][k]=r),t++;q++;t=0}l++;q=0}};
pl6e.prototype.pl50=function(a,b,d,e,g){var h,k,f,n,m,l,q,t,r;m=a.length;l=b.length;f=d+l<=m?d+l:m;m=a[0].length;l=b[0].length;n=e+l<=m?e+l:m;m=a[0][0].length;l=b[0][0].length;m=g+l<=m?g+l:m;for(l=q=t=0;d<f;d++){for(h=e;h<n;h++){for(k=g;k<m;k++)r=b[l][q][t],a[d][h][k]=r,t++;q++;t=0}l++;q=0}};pl6e.prototype.pl51=function(a,b,d){b=Math.floor(a*b);return b%2!=a%2?d?b+1:b-1:b};
pl6e.prototype.pl52=function(a,b,d){var e,g,h;for(e=0;e<a.length;e++)for(g=0;g<a[0].length;g++)if(0<a[e][g])for(h=this.pl8d[0].length-1;0<=h;){if(0<this.pl8d[b+g][h][d+e]){this.pl8d[b+g][h][d+e]=a[e][g];break}h--}};
function pl6f(a){this.plac=a;this.plae=this.plad=0;this.plaf=document.getElementById("pv"+a+"bn0");this.plb0=document.getElementById("pv"+a+"bn1");this.plb1=document.getElementById("pvrl"+a);this.plb2=document.getElementById("pvkn"+a);this.plb3=document.getElementById("pvin"+a);this.plb4=!1}
pl6f.prototype.pl53=function(a,b,d){this.plaf.style.left=a+"px";this.plaf.style.top=b+"px";this.plb0.style.left=a+d-40+"px";this.plb0.style.top=b+"px";this.plb1.style.left=a+52+"px";this.plb1.style.top=b+16+"px";this.plb1.style.width=d-40-40-12-12+"px";this.plb5=a+40;this.plb6=d-40-40-32;this.plb7=this.plb5+this.plb6;this.plb8=a+40;this.plb9=b+4;this.plb2.style.left=this.plb8+"px";this.plb2.style.top=this.plb9+"px";this.plb3.style.left=this.plb8-16+"px";this.plb3.style.top=this.plb9-44+"px"};
pl6f.prototype.pl54=function(a,b,d){this.plaf.style.visibility="visible";this.plb0.style.visibility="visible";this.plb1.style.visibility="visible";this.plb2.style.visibility="visible";this.plb4=!0;this.plad=a-1;this.plba=1+d-a;this.pl56(b)};pl6f.prototype.pl55=function(a,b){this.plba=b-this.plad;this.pl56(a)};
pl6f.prototype.pl56=function(a){a>this.plba+this.minValu1?a=this.plba+this.plad:a<this.plad+1&&(a=this.plad+1);a-=this.plad;newX=this.plb5+Math.floor(a*this.plb6/this.plba)-1;this.plb2.style.left=newX+"px";this.plb3.style.left=newX-16+"px";this.plb8=newX;this.plbb=a;this.plb2.innerHTML=this.plbb+this.plad};pl6f.prototype.pl57=function(a,b){return!plcd.pla3.pl86&&this.plb4&&a>=this.plb8-4&&a<=this.plb8+40&&b>=this.plb9-4&&b<=this.plb9+40};
pl6f.prototype.pl58=function(a,b){this.plbc=a;this.plbd=a-this.plb8;this.plb3.style.visibility="visible";this.pl5b()};pl6f.prototype.pl59=function(a,b){var d=this.plbc+a-this.plbc-this.plbd;d<this.plb5?d=this.plb5:d>this.plb7-1&&(d=this.plb7-1);this.plb2.style.left=d+"px";this.plb3.style.left=d-16+"px";this.plb8=d;this.pl5b()};pl6f.prototype.pl5a=function(){this.plb3.style.visibility="hidden";this.pl56(this.plbb+this.plad);plcd.pla4.pl69(this.plac,this.plbb+this.plad)};
pl6f.prototype.pl5b=function(){this.plbb=1+Math.floor(this.plba*(this.plb8-this.plb5)/this.plb6);this.plb3.innerHTML=this.plb2.innerHTML=this.plbb+this.plad};function pl70(){this.plbe=(new Date).getTime()}pl70.prototype.pl5c=function(){return(new Date).getTime()-this.plbe};
function pl71(a){this.pla3=a;this.plc0=this.plbf=32;this.plc2=this.plc1=12;this.plc3=5;this.plc5=this.plc4=!0;a=document.getElementById("pctl");/*var b=new XMLHttpRequest;b.open("GET","/plotzhtml5/pclt.php?o=2",!1);b.send(null);200===b.status&&(a.style.width="204px",a.style.height="120px",a.innerHTML=b.responseText)*/}
pl71.prototype.pl29=function(){var a=this.pla3.pl73?"touchstart":"click";document.getElementById("b0").addEventListener(a,function(a){plcd.pla3.pl15(a,plcd.pla4.pl62);return!1},!1);document.getElementById("b1").addEventListener(a,function(a){plcd.pla3.pl15(a,plcd.pla4.pl61);return!1},!1);document.getElementById("b2").addEventListener(a,function(a){plcd.pla3.pl15(a,plcd.pla4.pl64);return!1},!1);document.getElementById("b3").addEventListener(a,function(a){plcd.pla3.pl15(a,plcd.pla4.pl63);return!1},
!1);document.getElementById("b4").addEventListener(a,function(a){plcd.pla3.pl15(a,plcd.pla4.pl66);return!1},!1);document.getElementById("b5").addEventListener(a,function(a){plcd.pla3.pl15(a,plcd.pla4.pl65);return!1},!1);document.getElementById("st0").addEventListener(a,function(a){plcd.pla3.pl15(a,plcd.pla4.pl68);return!1},!1);document.getElementById("st1").addEventListener(a,function(a){plcd.pla3.pl15(a,plcd.pla4.pl68);return!1},!1);document.getElementById("st2").addEventListener(a,function(a){plcd.pla3.pl15(a,
plcd.pla4.pl68);return!1},!1);document.getElementById("ptbmv").innerHTML="Torus"};pl71.prototype.pl5d=function(){this.pla3.pl86=!0;this.plc2=this.plc1;this.plc0=this.plbf;this.pl60();this.plc6=new pl6e(this.plc2,this.plbf,this.plc0);this.plc6.pla7=1;this.plc7=!0;this.pl5e()};
pl71.prototype.pl5e=function(){var a=plcd.pla4;a.plc6.pl47(a.plc7,a.plbf,a.plc0,a.plc1,a.plc2,2*a.plc3-1)?a.plc7?a.pl5f():(a.pla3.pl18("rendering"),setTimeout(plcd.pla4.pl5f,50)):(a.plc7&&(a.plc7=!1,a.pla3.pl17()),a.pla3.pl18("Creating Torus "+Math.floor(200*a.plc6.plab/a.plc6.pla5)+"%"),setTimeout(plcd.pla4.pl5e,50))};pl71.prototype.pl5f=function(){plcd.pla3.pl1(plcd.pla4.plc6.pl8d,plcd.pla4.plc6.pla5,0);plcd.pla3.pl19();plcd.pla3.pl86=!1};
pl71.prototype.pl60=function(){document.getElementById("sz0").innerHTML=this.plbf;document.getElementById("sz1").innerHTML=this.plc1;document.getElementById("sz2").innerHTML=this.plc3};pl71.prototype.pl61=function(){var a=plcd.pla4;256>a.plbf?(a.plbf++,a.pl5d()):a.pla3.pl16()};pl71.prototype.pl62=function(){var a=plcd.pla4;4<a.plbf&&a.plbf-1>2*a.plc1?(a.plbf--,a.pl5d()):a.pla3.pl16()};pl71.prototype.pl63=function(){var a=plcd.pla4;2*(a.plc1+1)<a.plbf?(a.plc1++,a.pl5d()):a.pla3.pl16()};
pl71.prototype.pl64=function(){var a=plcd.pla4;1<a.plc1?(a.plc1--,a.pl5d()):a.pla3.pl16()};pl71.prototype.pl65=function(){var a=plcd.pla4;6>a.plc3?(a.plc3++,a.pl5d()):a.pla3.pl16()};pl71.prototype.pl66=function(){var a=plcd.pla4;1<a.plc3?(a.plc3--,a.pl5d()):a.pla3.pl16()};pl71.prototype.pl67=function(){var a=Math.floor(this.plbf/2);this.plc1>a&&(this.plc1=a)};
pl71.prototype.pl68=function(){document.getElementById("pctl").style.visibility="hidden";document.getElementById("pvl").style.visibility="visible";var a=plcd.pla3.pl78-120,b;for(b=0;3>b;b++)plcd.pla3.pl84[b].pl53(64,a,plcd.pla3.pl77-64-64),a+=40;a=plcd.pla4;plcd.pla3.pl84[0].pl54(4,a.plbf,256);plcd.pla3.pl84[1].pl54(1,a.plc1,Math.floor(a.plbf/2));plcd.pla3.pl84[2].pl54(1,a.plc3,6);plcd.pla3.pl88=!0};
pl71.prototype.pl69=function(a,b){0==a?(this.plbf=b,this.pl67(),this.pla3.pl84[1].pl55(this.plc1,Math.floor(this.plbf/2))):1==a?this.plc1=b:2==a&&(this.plc3=b);this.pl5d()};pl71.prototype.pl1b=function(a){0==a?(this.pl62(),this.pl67(),this.pla3.pl84[0].pl56(this.plbf),this.pla3.pl84[1].pl55(this.plc1,Math.floor(this.plbf/2))):1==a?(this.pl64(),this.pla3.pl84[1].pl56(this.plc1)):2==a&&(this.pl66(),this.pla3.pl84[2].pl56(this.plc3))};
pl71.prototype.pl1c=function(a){0==a?(this.pl61(),this.pl67(),this.pla3.pl84[0].pl56(this.plbf),this.pla3.pl84[1].pl55(this.plc1,Math.floor(this.plbf/2))):1==a?(this.pl63(),this.pla3.pl84[1].pl56(this.plc1)):2==a&&(this.pl65(),this.pla3.pl84[2].pl56(this.plc3))};function pl72(a,b,d){this.plba=b;this.pla3=d;this.pl6a();this.plbb=a;this.pl5b()}
pl72.prototype.pl6a=function(){var a=this.pla3.pl78-160;this.plc8=a-32;this.plb8=this.pla3.pl77-32-16;this.plb9=this.plc9=Math.floor((this.pla3.pl78-a)/2);this.plca=this.plc9+a-1-32;var b=document.getElementById("pslrl");b.style.left=this.plb8+12+"px";b.style.top=this.plb9+12+"px";b.style.height=a-28+"px";this.plb2=document.getElementById("pslkn");this.plb2.style.top=this.plb9+"px";this.plb2.style.left=this.plb8+"px";this.plb3=document.getElementById("pslin");this.plb3.style.top=this.plb9-4+"px";
this.plb3.style.left=this.plb8-70+"px";b=document.getElementById("pslbn0");b.style.left=this.plb8-4+"px";b.style.top=this.plb9-40+"px";b=document.getElementById("pslbn1");b.style.left=this.plb8-4+"px";b.style.top=this.plb9+a+"px";this.pl56(this.plbb)};pl72.prototype.pl57=function(a,b){return!this.pla3.pl86&&a>=this.plb8&&a<=this.plb8+32&&b>=this.plb9&&b<=this.plb9+32};pl72.prototype.pl58=function(a,b){this.plcb=b;this.plcc=b-this.plb9;this.plb3.style.visibility="visible";this.pl5b()};
pl72.prototype.pl59=function(a,b){var d=this.plcb+b-this.plcb-this.plcc;d<this.plc9?d=this.plc9:d>this.plca&&(d=this.plca);this.plb2.style.top=d+"px";this.plb3.style.top=d-4+"px";this.plb9=d;this.pl5b()};pl72.prototype.pl5a=function(){this.plb3.style.visibility="hidden";this.pla3.pl1(null,this.plbb-1,-1)};pl72.prototype.pl5b=function(){this.plbb=this.plba-Math.floor(this.plba*(this.plb9-this.plc9)/this.plc8);this.plb3.innerHTML=this.plb2.innerHTML=this.plbb};
pl72.prototype.pl56=function(a){a>this.plba?a=this.plba:1>a&&(a=1);newY=this.plc9+this.plc8-1-Math.floor((a-1)*(this.plc8-1)/(this.plba-1));this.plb2.style.top=newY+"px";this.plb3.style.top=newY-4+"px";this.plb9=newY;this.plbb=a;this.plb3.innerHTML=this.plb2.innerHTML=this.plbb};