function pl6c(a,b){var d=document.getElementById("pcan");a?(d.width=a,d.height=b):(a=d.width=window.innerWidth-120,b=d.height=window.innerHeight-0);this.pl74=d.offsetLeft;this.pl75=d.offsetTop;this.pl76=d.getContext("2d");this.pl77=document.getElementById("pev");this.pl77.style.width=a+"px";this.pl77.style.height=b+"px";this.pl78=a;this.pl79=b;this.pl7a=a;this.pl7b=b;this.pl7d=this.pl7c=0;this.pl7e=1;this.pl80=this.pl7f=0;this.pl81=[];this.pl82=[];this.pl83=[];this.pl82[0]=["#000000","#ffff00","#b1b100",
"#5b5b00"];this.pl82[1]=["#000000","#c0c0c0","#808080","#5f5f5f"];this.pl82[2]=["#000000","#303060","#202040","#101020"];this.pl82[3]=["#000000","#E0E0E0","#A0A0A0","#808080"];this.pl82[4]=["#808080","#ffffff","#E0E0E0","#C0C0C0"];this.pl82[5]=["#000000","#A00000","#700000","#400000"];this.pl82[6]=["#808080","rgba(255, 255, 255, 0.09)","rgba(224, 224, 224, 0.09)","rgba(192, 192, 192, 0.09)"];this.pl82[7]=["#333333","#FF8C00","#B16100","#5B3200"];this.pl83[0]=["#000000","#b1b100"];this.pl83[1]=["#000000",
"#808080"];this.pl83[2]=["#000000","#202040"];this.pl83[3]=["#000000","#A0A0A0"];this.pl83[4]=["#000000","#E0E0E0"];this.pl83[5]=["#000000","#700000"];this.pl83[6]=["#000000","#80c0ff"];this.pl83[7]=["#000000","#B16100"];this.pl84=new pl6f(32,32,this);this.pl85=Array(4);for(d=0;4>d;d++)this.pl85[d]=new pl73(d);this.pl86=document.getElementById("pcon");this.pl86.style.display="none";this.pl87=!1;this.pl88=!0;this.pl89=!1}
pl6c.prototype.pl0=function(){var a=this.pl7e;this.pl7e=4>this.pl7e?2*this.pl7e:1;this.log("zoom="+this.pl7e);if(1<this.pl7e){this.pl88?(this.pl8a=document.createElement("canvas"),this.pl8a.width=this.pl78,this.pl8a.height=this.pl79,this.pl7a=this.pl78*this.pl7e,this.pl7b=this.pl79*this.pl7e):(this.pl8a=document.createElement("canvas"),this.pl7a=this.pl8a.width=this.pl78*this.pl7e,this.pl7b=this.pl8a.height=this.pl79*this.pl7e);this.pl8b=this.pl8a.getContext("2d");var b=(this.pl7c+this.pl78/2)/a;
a=(this.pl7d+this.pl79/2)/a;this.pl8c=this.pl7c=b*this.pl7e-this.pl78/2;this.pl8d=this.pl7d=a*this.pl7e-this.pl79/2;console.log("zoomOffX="+this.pl7c+", this.pl7d="+this.pl7d+", cx="+b+", cy="+a)}else this.pl8b=this.pl8a=null,this.pl7a=this.pl78,this.pl7b=this.pl79,this.pl7d=this.pl8d=this.pl7c=this.pl8c=0;0==this.pl7f?(this.pl8(),this.pl3()):(this.pl7(),this.pl2())};
pl6c.prototype.pl1=function(a,b,d){a&&(this.pl8e=a,this.pl1a(0));this.pl8f=b;0==this.pl7f?this.pl3():this.pl2();this.pl84.pla6!=this.pl8e.length&&(this.pl84.pla6=this.pl8e.length);this.pl84.pl46(this.pl8f+1);this.pl16()};
pl6c.prototype.pl2=function(){var a,b,d=1==this.pl8e.length;var e=this.pl8f>this.pl8e.length-1?this.pl8e.length-1:this.pl8f;new pl6e;if(1<this.pl7e){var f=this.pl8b;if(this.pl88){var g=this.pl93-this.pl7c;var k=this.pl94-this.pl7d;f.clearRect(0,0,this.pl78,this.pl79)}else f.clearRect(0,0,this.pl7a,this.pl7b)}else f=this.pl76,g=this.pl93,k=this.pl94;this.pl76.clearRect(0,0,this.pl78,this.pl79);var h=this.pl8e[0].length;var n=this.pl8e[0][0].length;for(a=0;a<h;a++)for(b=0;b<n;b++)f.drawImage(this.pl95,
g+a*this.pl92,k+b*this.pl91);if(0<e){var m=this.pl8e[e-1];for(a=0;a<h;a++)for(b=0;b<n;b++)0<m[a][b]&&f.drawImage(this.pl96,g+a*this.pl92,k+b*this.pl91)}m=this.pl8e[e];for(a=0;a<h;a++)for(b=0;b<n;b++)e=m[a][b],0>=e||(f.drawImage(this.pl97[e],g+a*this.pl92,k+b*this.pl91),d&&this.pl90++);f.beginPath();f.lineWidth=1;f.strokeStyle="#a00000";a=1+g+Math.floor(h/2)*this.pl92-1;f.moveTo(a+.5,k);f.lineTo(a+.5,1+k+n*this.pl91);h%2&&(a+=this.pl92,f.moveTo(a+.5,k),f.lineTo(a+.5,1+k+n*this.pl91));f.stroke();f.beginPath();
f.lineWidth=1;f.strokeStyle="#008000";b=1+k+Math.floor(n/2)*this.pl91-1;f.moveTo(g,b+.5);f.lineTo(1+g+h*this.pl92,b+.5);n%2&&(b+=this.pl91,f.moveTo(g,b+.5),f.lineTo(1+g+h*this.pl92,b+.5));f.stroke();plcc.plb3.plb8&&this.pl20(f);plcc.plb3.innerEdgeSizes&&this.pl21(f);1<this.pl7e&&this.pl88&&this.pl76.drawImage(this.pl8a,0,0,this.pl78,this.pl79,0,0,this.pl78,this.pl79)};
pl6c.prototype.pl3=function(){1<this.pl7e?(this.pl76.clearRect(0,0,this.pl78,this.pl79),this.pl88?(this.pl5(),this.pl76.drawImage(this.pl8a,0,0,this.pl78,this.pl79,0,0,this.pl78,this.pl79)):(this.pl6(),this.pl76.drawImage(this.pl8a,this.pl7c,this.pl7d,this.pl78,this.pl79,0,0,this.pl78,this.pl79))):this.pl4()};
pl6c.prototype.pl4=function(){var a,b,d=this.pl8f>=this.pl8e.length-1,e=this.pl8f>this.pl8e.length-1?this.pl8e.length-1:this.pl8f,f;d&&(this.pl90=0);this.pl76.clearRect(0,0,this.pl78,this.pl79);for(f=0;f<=e;f++){var g=this.pl8f<=this.pl8e.length-1&&f==this.pl8f;var k=this.pl8e[f];for(a=0;a<k.length;a++)for(b=0;b<k[a].length;b++){var h=k[a][b];0<h&&(d&&this.pl90++,g&&(h=0),this.pl76.drawImage(this.pl81[h],this.pl93+(a-b)*this.pl98,this.pl94+(a+b)*this.pl99/2-f*this.pl99))}}document.getElementById("pbc").innerHTML=
this.pl90};pl6c.prototype.pl5=function(){var a,b,d=this.pl8f>=this.pl8e.length-1,e=this.pl8f>this.pl8e.length-1?this.pl8e.length-1:this.pl8f,f,g=0+this.pl93-this.pl8c,k=0+this.pl94-this.pl8d;this.pl8b.clearRect(0,0,this.pl78,this.pl79);for(f=0;f<=e;f++){var h=this.pl8f<=this.pl8e.length-1&&f==this.pl8f;var n=this.pl8e[f];for(a=0;a<n.length;a++)for(b=0;b<n[a].length;b++){var m=n[a][b];0<m&&(d&&this.pl90++,h&&(m=0),this.pl8b.drawImage(this.pl81[m],g+(a-b)*this.pl98,k+(a+b)*this.pl99/2-f*this.pl99))}}};
pl6c.prototype.pl6=function(){var a,b,d=this.pl8f>=this.pl8e.length-1,e=this.pl8f>this.pl8e.length-1?this.pl8e.length-1:this.pl8f,f;this.pl8b.clearRect(0,0,this.pl7a,this.pl7b);for(f=0;f<=e;f++){var g=this.pl8f<=this.pl8e.length-1&&f==this.pl8f;var k=this.pl8e[f];for(a=0;a<k.length;a++)for(b=0;b<k[a].length;b++){var h=k[a][b];0<h&&(d&&this.pl90++,g&&(h=0),this.pl8b.drawImage(this.pl81[h],this.pl93+(a-b)*this.pl98,this.pl94+(a+b)*this.pl99/2-f*this.pl99))}}};
pl6c.prototype.pl7=function(){var a=this.pl8e[0].length,b=this.pl8e[0][0].length;this.pl78/a<this.pl79/b?this.pl91=this.pl92=Math.floor((this.pl78-40)/a)*this.pl7e:this.pl92=this.pl91=Math.floor((this.pl79-40)/b)*this.pl7e;this.pl93=Math.floor((this.pl78*this.pl7e-a*this.pl92)/2);this.pl94=Math.floor((this.pl79*this.pl7e-b*this.pl91)/2);this.pl95=this.pl9("#e0e0e0","#ffffff");this.pl96=this.pl9("#a0a0a0","#e8e8e8");this.pl97=[];for(a=0;a<this.pl83.length;a++)this.pl97[a]=this.pl9(this.pl83[a][0],
this.pl83[a][1])};
pl6c.prototype.pl8=function(){var a,b,d,e=-1E4,f=-1E4,g=1E4,k=1E4;var h=this.pl8e.length;var n=this.pl8e[0].length;var m=this.pl8e[0][0].length;for(a=0;a<h;a++)for(b=0;b<n;b++)for(d=0;d<m;d++)if(0<this.pl8e[a][b][d]){var l=64*(b-d)/2;l<g&&(g=l);l>e&&(e=l);l=36*(b+d)/2-36*a;l<k&&(k=l);l>f&&(f=l)}(e-g)/this.pl78>(f-k)/this.pl79?(this.pl92=Math.floor((this.pl78-40)/((e-g)/64+1)*this.pl7e),this.pl91=Math.round(72*this.pl92/64)):(this.pl91=Math.floor((this.pl79-40)/((f-k)/72+1)*this.pl7e),this.pl92=Math.round(64*
this.pl91/72));this.pl93=Math.floor((this.pl7a-(e+g)/64*this.pl92-this.pl92)/2);this.pl94=Math.floor((this.pl7b-(f+k)/72*this.pl91-this.pl91)/2);this.pl98=this.pl92/2;this.pl99=this.pl91/2;for(a=0;a<this.pl82.length;a++)this.pl81[a]=this.pla(a)};pl6c.prototype.pl9=function(a,b){var d=document.createElement("canvas");d.width=this.pl92+2;d.height=this.pl91+2;var e=d.getContext("2d");e.strokeStyle=a;e.fillStyle=b;e.lineWidth=1;e.beginPath();e.rect(.5,.5,this.pl92,this.pl91);e.fill();e.stroke();return d};
pl6c.prototype.pla=function(a){var b=Array(7);b[0]=[.5*this.pl92,0];b[1]=[this.pl92,.25*this.pl91];b[2]=[this.pl92,.75*this.pl91];b[3]=[.5*this.pl92,this.pl91];b[4]=[0,.75*this.pl91];b[5]=[0,.25*this.pl91];b[6]=[.5*this.pl92,.5*this.pl91];var d=document.createElement("canvas");d.width=this.pl92+1;d.height=this.pl91+1;var e=d.getContext("2d");e.lineWidth=.75;e.strokeStyle=this.pl82[a][0];e.beginPath();e.moveTo(.5+b[0][0],.5+b[0][1]);e.lineTo(.5+b[1][0],.5+b[1][1]);e.lineTo(.5+b[6][0],.5+b[6][1]);e.lineTo(.5+
b[5][0],.5+b[5][1]);e.closePath();e.fillStyle=this.pl82[a][1];e.fill();e.stroke();e.beginPath();e.moveTo(.5+b[5][0],.5+b[5][1]);e.lineTo(.5+b[6][0],.5+b[6][1]);e.lineTo(.5+b[3][0],.5+b[3][1]);e.lineTo(.5+b[4][0],.5+b[4][1]);e.closePath();e.fillStyle=this.pl82[a][2];e.fill();e.stroke();e.beginPath();e.moveTo(.5+b[1][0],.5+b[1][1]);e.lineTo(.5+b[2][0],.5+b[2][1]);e.lineTo(.5+b[3][0],.5+b[3][1]);e.lineTo(.5+b[6][0],.5+b[6][1]);e.closePath();e.fillStyle=this.pl82[a][3];e.fill();e.stroke();return d};
pl6c.prototype.plb=function(a,b,d,e){this.pl76.drawImage(this.pl81,this.pl93+(b-d)*this.pl98,this.pl94+(b+d)*this.pl99/2-a*this.pl99)};pl6c.prototype.plc=function(a){if(this.pl84.pl41(a.clientX,a.clientY))this.pl80=1,this.pl84.pl42(a.clientX,a.clientY);else{var b;for(b=0;b<this.pl85.length;b++)if(this.pl85[b].pl41(a.clientX,a.clientY)){this.pl80=3;this.pl9a=b;this.pl85[b].pl42(a.clientX,a.clientY);return}1<this.pl7e&&(this.pl80=2,this.pl12(a.clientX,a.clientY))}};
pl6c.prototype.pld=function(a){this.log("touchStart"+a.touches);if(this.pl84.pl41(a.touches[0].pageX,a.touches[0].pageY))this.log("dragMode = 1"),this.pl80=1,this.pl84.pl42(a.touches[0].pageX,a.touches[0].pageY);else{var b;for(b=0;b<this.pl85.length;b++)if(this.pl85[b].pl41(a.touches[0].pageX,a.touches[0].pageY)){this.pl80=3;this.pl9a=b;this.pl85[b].pl42(a.touches[0].pageX,a.touches[0].pageY);return}1<this.pl7e&&(this.pl80=2,this.pl12(a.touches[0].pageX,a.touches[0].pageY))}};
pl6c.prototype.ple=function(a){1==this.pl80?this.pl84.pl43(a.touches[0].pageX,a.touches[0].pageY):2==this.pl80?this.pl13(a.touches[0].pageX,a.touches[0].pageY):3==this.pl80&&this.pl85[this.pl9a].pl43(a.touches[0].pageX,a.touches[0].pageY)};pl6c.prototype.plf=function(a){1==this.pl80?this.pl84.pl43(a.clientX,a.clientY):2==this.pl80?this.pl13(a.clientX,a.clientY):3==this.pl80&&this.pl85[this.pl9a].pl43(a.clientX,a.clientY)};
pl6c.prototype.pl10=function(a){1==this.pl80?this.pl84.pl44():2==this.pl80?this.pl14():3==this.pl80&&this.pl85[this.pl9a].pl44();this.pl80=0};pl6c.prototype.pl11=function(a){1==this.pl80?this.pl84.pl44():2==this.pl80?this.pl14():3==this.pl80&&this.pl85[this.pl9a].pl44();this.pl80=0};pl6c.prototype.pl12=function(a,b){this.pl9b=a;this.pl9c=b};
pl6c.prototype.pl13=function(a,b){var d=this.pl7c+this.pl9b-a,e=this.pl7d+this.pl9c-b;0>d&&(a+=d,d=0);0>e&&(b+=e,e=0);d>this.pl7a-this.pl78&&(a=a+d-(this.pl7a-this.pl78),d=this.pl7a-this.pl78);e>this.pl7b-this.pl79&&(b=b+e-(this.pl7b-this.pl79),e=this.pl7b-this.pl79);this.pl8c=d;this.pl8d=e;this.pl76.clearRect(0,0,this.pl78,this.pl79);this.pl88?this.pl76.drawImage(this.pl8a,0,0,this.pl78,this.pl79,a-this.pl9b,b-this.pl9c,this.pl78,this.pl79):this.pl76.drawImage(this.pl8a,d,e,this.pl78,this.pl79,0,
0,this.pl78,this.pl79)};pl6c.prototype.pl14=function(){this.pl7c=this.pl8c;this.pl7d=this.pl8d;console.log("panStop() - "+this.pl7c+", "+this.pl7d);this.pl88&&(this.pl76.clearRect(0,0,this.pl78,this.pl79),0==this.pl7f?this.pl5():this.pl2(),this.pl76.drawImage(this.pl8a,0,0,this.pl78,this.pl79,0,0,this.pl78,this.pl79))};pl6c.prototype.log=function(a){this.pl86.innerHTML+=a+"<br/>";this.pl86.scrollTop=this.pl86.scrollHeight};
pl6c.prototype.pl15=function(a,b){a.preventDefault();var d=plcc.pla7;if(d.pl9d)b();else{s=a.target.className;if("bn"!=s.substring(s.length-2)){var e=a.target.getElementsByTagName("div");if(0==e.length){setTimeout(b,10);return}e=e[0]}else e=a.target;e.style.background="#ffffff";e.style.color="#000000";d.pl9d=e;setTimeout(b,10)}};pl6c.prototype.pl16=function(){this.pl9d&&(this.pl9d.style.background="#000000",this.pl9d.style.color="#ffffff",this.pl9d=null)};
pl6c.prototype.pl17=function(){var a=document.getElementById("ppro");a.style.left=(this.pl78-a.offsetWidth)/2+"px";a.style.top=this.pl79/2-32+"px";a.style.visibility="visible"};pl6c.prototype.pl18=function(a){document.getElementById("ppro").innerHTML=a};pl6c.prototype.pl19=function(){document.getElementById("ppro").style.visibility="hidden"};
pl6c.prototype.pl1a=function(a){document.getElementById("seglbn").style.background=0==a?"#003000":"#808080";document.getElementById("seglbn").style.color=0==a?"#ffffff":"#000000";document.getElementById("segrbn").style.background=0==a?"#808080":"#003000";document.getElementById("segrbn").style.color=0==a?"#000000":"#ffffff";this.pl7f=a;0==a?this.pl8():this.pl7()};pl6c.prototype.pl1b=function(){plcc.plb3.pl1b(parseInt(plcc.pla7.pl9d.id.substring(1)))};pl6c.prototype.pl1c=function(){plcc.plb3.pl1c(parseInt(plcc.pla7.pl9d.id.substring(1)))};
pl6c.prototype.pl1d=function(){for(var a=0,b="";;){el=document.getElementById("tl"+a);if(!el)break;b+=el.innerHTML+"<br/>";a++}a=40*++a;document.getElementById("pvl").style.height=a+"px";document.getElementById("pvlp").innerHTML=b};pl6c.prototype.pl1e=function(){this.pl89=!1;this.pl1f();document.getElementById("pctl").style.visibility="visible"};
pl6c.prototype.pl1f=function(){console.log("hideValues");for(i=0;i<this.pl85.length;i++)document.getElementById("pv"+i+"bn0").style.visibility="hidden",document.getElementById("pv"+i+"bn1").style.visibility="hidden",document.getElementById("pvrl"+i).style.visibility="hidden",document.getElementById("pvkn"+i).style.visibility="hidden";document.getElementById("pvl").style.visibility="hidden"};
pl6c.prototype.pl20=function(a){var b=this.pl8e[this.pl8f>this.pl8e.length-1?this.pl8e.length-1:this.pl8f],d=Math.floor((b.length+1)/2-1),e=Math.floor((b[0].length+1)/2-1),f,g,k=[],h=0;if(1<this.pl7e&&this.pl88){var n=this.pl93-this.pl7c;var m=this.pl94-this.pl7d}else n=this.pl93,m=this.pl94;if(14<this.pl91){var l=Math.floor((this.pl91-14)/2);a.font="bold 14px Helvetica"}else l=0,a.font="bold "+this.pl91+"px Helvetica";for(f=0;f<=d;f++){for(g=0;0>=b[f][g]&&g<=e;)g++;if(!(g>e)){var r=1;var q=g+1;if(0==
f)for(;0<b[f][q]&&q<=e;)q++,r++;else for(;0<b[f][q]&&0>=b[f-1][q]&&q<=e;)q++,r++;q=!1;1==r&&0<g&&0<b[f+1][g-1]&&(0==f||0>=b[f-1][g])&&(q=!0);if(q||1<r)q?k[h++]=new pl72(r,n+f*this.pl92,m+l+g*this.pl91-this.pl91,"top","right"):k[h++]=new pl72(r,n+f*this.pl92-1,m+l+g*this.pl91+Math.floor(r*this.pl91/2)-this.pl91/2,"top","right")}}for(g=0;g<=e;g++){for(f=0;0>=b[f][g]&&f<=d;)f++;if(!(f>d)){r=1;l=f+1;if(0==g)for(;0<b[l][g]&&l<=d;)l++,r++;else for(;0<b[l][g]&&0>=b[l][g-1]&&l<=d;)l++,r++;1<r&&(k[h++]=new pl72(r,
n+f*this.pl92+Math.floor(r*this.pl92/2),m+g*this.pl91,"bottom","center"))}}this.pl22(a,k)};
pl6c.prototype.pl21=function(a){var b=this.pl8e[this.pl8f>this.pl8e.length-1?this.pl8e.length-1:this.pl8f],d=Math.floor((b.length+1)/2-1),e=Math.floor((b[0].length+1)/2-1),f,g,k=[],h=0;if(1<this.pl7e&&this.pl88){var n=this.pl93-this.pl7c;var m=this.pl94-this.pl7d}else n=this.pl93,m=this.pl94;if(14<this.pl91){var l=Math.floor((this.pl91-14)/2);a.font="bold 14px Helvetica"}else l=0,a.font="bold "+this.pl91+"px Helvetica";a.fillStyle="#000";a.textBaseline="top";a.textAlign="left";var r=Math.floor(this.pl91/
2);for(f=d;0<=f;f--){for(g=e;0<=g&&0>=b[f][g];)g--;if(!(0>g)){var q=1;var u=g-1;if(0==f)for(;0<=u&&0<b[f][u];)u--,q++;else for(;0<=u&&0<b[f][u]&&0>=b[f+1][u];)u--,q++;u=!1;1==q&&g<e&&0<b[f+1][g-1]&&0>=b[f+1][g]&&(0==f||0<b[f-1][g+1])&&(u=!0);if(u||1<q)u?k[h++]=new pl72(q,n+1+(f+1)*this.pl92,m+(g+1)*this.pl91,"top","bottom"):k[h++]=new pl72(q,n+1+(f+1)*this.pl92,m+l+(g+1)*this.pl91-q*this.pl91/2-r,"top","bottom");if(g==e)break}}for(g=e-1;0<=g;g--){for(f=d;0<=f&&0>=b[f][g];)f--;if(!(0>f)){q=1;for(e=
f-1;0<=e&&0<b[e][g]&&0>=b[e][g+1];)e--,q++;1<q&&(k[h++]=new pl72(q,n+1+(f+1)*this.pl91-q*this.pl92/2-r/2,m+(g+1)*this.pl92,"top","bottom"));if(f==d)break}}this.pl22(a,k)};
pl6c.prototype.pl22=function(a,b){var d=65535,e=0,f=0,g=["#c00000","#008000","#0000c0"];for(c=0;c<b.length;c++){yp=-1;for(idx=0;idx<b.length;idx++)b[idx].plbd<d&&b[idx].plbd>yp&&(yp=b[idx].plbd,yFound=idx);d=yp;a.fillStyle=g[f];a.textBaseline=b[yFound].plbe;a.textAlign=b[yFound].plbf;a.fillText(b[yFound].plbb,b[yFound].plbc,b[yFound].plbd);5<=++e&&(e=0,++f>=g.length&&(f=0))}};
pl6c.prototype.pl23=function(){var a=plcc.pla7,b=document.getElementById("pcan"),d=window.innerWidth-120;b.width=d;b.height=window.innerHeight;a.pl8a&&(a.pl8a.width=b.width,a.pl8a.height=b.height);a.pl78=d;a.pl79=window.innerHeight;a.pl77.style.width=d+"px";a.pl77.style.height=window.innerHeight+"px";a.pl7a=a.pl78*a.pl7e;a.pl7b=a.pl79*a.pl7e;0==a.pl7f?(a.pl8(),a.pl3()):(a.pl7(),a.pl2());a.pl84.pl40();document.getElementById("pvl");"visible"==pvl.style.visibility&&plcc.plb3.pl67()};
function pl6d(a,b,d){this.pl9e=a;this.pl9f=b;this.pla0=1;this.pl24(a,b,d)}pl6d.prototype.pl24=function(a,b,d){this.pl8e=Array(a);var e;for(e=0;e<a;e++)this.pl8e[e]=this.pl26(b,d)};pl6d.prototype.pl25=function(a,b){var d;this.pla1=Array(a);for(d=0;d<a;d++)this.pla1[d]=new Int8Array(b)};pl6d.prototype.pl26=function(a,b){var d=Array(a),e,f;for(e=0;e<a;e++)for(d[e]=new Int8Array(b),f=0;f<b;f++)d[e][f]=-1;return d};
pl6d.prototype.pl27=function(a,b,d,e,f){var g=Math.abs(d-a),k=Math.abs(e-b),h=k&1,n=4*(1-g)*k*k,m=4*(h+1)*g*g,l=n+m+h*g*g,r=this.pla0;a>d&&(a=d,d+=g);b>e&&(b=e);b+=Math.floor((k+1)/2);e=b-h;g*=8*g;h=8*k*k;do{f[d][b]=r;f[a][b]=r;f[a][e]=r;f[d][e]=r;var q=2*l;q>=n&&(a++,d--,l+=n+=h);q<=m&&(b++,e--,l+=m+=g)}while(a<=d);for(;b-e<k;)f[a-1][++b]=r,f[a-1][--e]=r};
pl6d.prototype.pl28=function(a,b){switch(this.pla2){case 0:this.pl8e[this.pla3][a][b]=this.pla0;break;case 1:this.pl8e[b][this.pla3][a]=this.pla0;break;case 2:this.pl8e[b][a][this.pla3]=this.pla0}};pl6d.prototype.pl29=function(a,b){switch(this.pla2){case 0:return this.pl8e[this.pla3][a][b];case 1:return this.pl8e[b][this.pla3][a];case 2:return this.pl8e[b][a][this.pla3]}return 0};
pl6d.prototype.pl2a=function(a,b,d,e,f,g){var k=Math.abs(d-a),h=Math.abs(e-b),n=h&1,m=4*(1-k)*h*h,l=4*(n+1)*k*k,r=m+l+n*k*k;this.pla2=f;this.pla3=g;a>d&&(a=d,d+=k);b>e&&(b=e);b+=Math.floor((h+1)/2);e=b-n;k*=8*k;n=8*h*h;do this.pl28(d,b),this.pl28(a,b),this.pl28(a,e),this.pl28(d,e),f=2*r,f>=m&&(a++,d--,r+=m+=n),f<=l&&(b++,e--,r+=l+=k);while(a<=d);for(;b-e<h;)this.pl28(a-1,++b),this.pl28(a-1,--e)};
pl6d.prototype.pl2b=function(a,b){var d,e,f,g=this.pl8e[0].length;for(e=0;e<g;e++){for(d=0;d<g&&-1==this.pl8e[a][d][e];)d++;if(!(d>=g)){for(;d<g&&1<=this.pl8e[a][d][e];)d++;for(f=g-d;d<f;)this.pl8e[a][d++][e]=b}}};pl6d.prototype.pl2c=function(a,b){var d,e,f;for(d=a;d<=b;d++)for(e=a;e<=b;e++)for(f=a;f<=b;f++)this.pl8e[d][e][f]=0};
pl6d.prototype.pl2d=function(a,b){var d,e,f;var g=this.pl8e[0].length;for(f=0;f<g;f++){for(d=0;d<g&&0>=this.pl8e[a][d][f];)d++;if(!(d>=g||0<this.pl8e[b][d][f])){for(;0<this.pl8e[a][d][f];)d++;var k=g-d;for(e=g-1-d;d<k&&!(0<this.pl8e[b][d][f]);)this.pl8e[a][d][f]=this.pla0,this.pl8e[a][e][f]=this.pla0,d++,e--}}};
pl6d.prototype.pl30=function(a,b,d){d=3;var e=b*d,f=this.pl26(e,e),g=Math.floor((b+1)/4),k,h=Math.floor(d*d*d/8),n=Math.floor((b+1)/2),m=b-1;console.log("prec "+d+", quadLimit"+h);new pl6e;var l=Array(d);for(k=0;k<d;k++)l[k]=this.pl26(e,e);this.pl27(0,0,e-1,e-1,f);for(a&&(zpSoFar=0);zpSoFar<g;){var r=zpSoFar*d;for(a=0;a<d;a++){for(k=0;k<e;k++)for(g=0;g<e;g++)l[a][k][g]=-1;for(k=0;k<e&&!(0<f[k][r]);k++);this.pl27(k,k,e-k-1,e-k-1,l[a]);this.pl34(l[a],1)}for(e=0;e<n;e++)for(f=0;f<n;f++){for(a=k=0;a<
d;a++)k+=this.pl36(l[a],e*d,f*d,d);k>h&&(this.pl8e[zpSoFar][e][f]=1,this.pl8e[zpSoFar][m-e][f]=1,this.pl8e[zpSoFar][e][m-f]=1,this.pl8e[zpSoFar][m-e][m-f]=1,this.pl8e[f][zpSoFar][e]=1,this.pl8e[f][zpSoFar][m-e]=1,this.pl8e[f][e][zpSoFar]=1,this.pl8e[f][m-e][zpSoFar]=1,this.pl8e[f][e][m-zpSoFar]=1,this.pl8e[f][m-e][m-zpSoFar]=1,this.pl8e[f][m-zpSoFar][e]=1,this.pl8e[f][m-zpSoFar][m-e]=1)}break}this.pl8e[b-1]=this.pl8e[0];d=Math.floor((b+1)/2);for(l=1;l<d;l++)this.pl31(l,l-1),this.pl8e[b-1-l]=this.pl8e[l];
return!0};
pl6d.prototype.pl2e=function(a,b,d,e){var f=b*d,g=this.pl26(f,f),k=this.pl26(f,f),h,n=Math.floor((b+1)/4),m=Math.floor((d+1)/2-1),l=Math.floor(d*d/2),r=Math.floor((b+1)/2),q=b-1,u=new pl6e;this.pl27(0,0,f-1,f-1,g);a&&(this.pla4=0);for(;this.pla4<n;this.pla4++){var v=this.pla4*d+m;for(a=0;a<f;a++)for(h=0;h<f;h++)k[a][h]=-1;for(a=0;a<f&&!(0<g[a][v]);a++);if(0!=this.pla4)for(this.pl27(a,a,f-a-1,f-a-1,k),this.pl34(k,1),a=0;a<r;a++)for(h=0;h<r;h++)this.pl36(k,a*d,h*d,d)>l&&(this.pl8e[this.pla4][a][h]=this.pla0,
this.pl8e[this.pla4][q-a][h]=this.pla0,this.pl8e[this.pla4][a][q-h]=this.pla0,this.pl8e[this.pla4][q-a][q-h]=this.pla0,this.pl8e[h][this.pla4][a]=this.pla0,this.pl8e[h][this.pla4][q-a]=this.pla0,this.pl8e[h][a][this.pla4]=this.pla0,this.pl8e[h][q-a][this.pla4]=this.pla0,this.pl8e[h][a][q-this.pla4]=this.pla0,this.pl8e[h][q-a][q-this.pla4]=this.pla0,this.pl8e[h][q-this.pla4][a]=this.pla0,this.pl8e[h][q-this.pla4][q-a]=this.pla0);else for(a=Math.round(a/d),this.pl27(a,a,q-a,q-a,this.pl8e[0]),this.pl34(this.pl8e[0],
this.pla0),p=this.pl8e[0],a=0;a<r;a++)for(h=0;h<r;h++)0<p[a][h]&&(this.pl8e[h][this.pla4][a]=this.pla0,this.pl8e[h][this.pla4][q-a]=this.pla0,this.pl8e[h][a][this.pla4]=this.pla0,this.pl8e[h][q-a][this.pla4]=this.pla0,this.pl8e[h][a][q-this.pla4]=this.pla0,this.pl8e[h][q-a][q-this.pla4]=this.pla0,this.pl8e[h][q-this.pla4][a]=this.pla0,this.pl8e[h][q-this.pla4][q-a]=this.pla0);if(e&&500<u.pl3f())return!1}this.pl8e[b-1]=this.pl8e[0];d=Math.floor((b+1)/2);for(e=1;e<d;e++)this.pl31(e,e-1),this.pl8e[b-
1-e]=this.pl8e[e];return!0};pl6d.prototype.pl31=function(a,b){for(var d=this.pl8e[a],e=this.pl8e[b],f=Math.floor((d.length+1)/2)-1,g=Math.floor((d[0].length+1)/2)-1,k=d.length-1,h=d[0].length-1,n=0;n<f&&!(0<d[n][g]);)n++;for(var m=0;m<g&&!(0<d[f][m]);)m++;var l;m++;for(l=g;l>=m;l--){for(g=n;g<=f&&!(0<d[g++][l]););for(;g<=f&&!(0<d[g][l-1]&&-1!=e[g][l]);)g++;for(;g<=f;)d[g][l]=0,d[g][h-l]=0,d[k-g][l]=0,d[k-g][h-l]=0,g++}};
pl6d.prototype.pl32=function(a,b,d,e,f){var g=b*f,k=d*f,h=e*f,n=this.pl26(g,h),m=this.pl26(k,h),l=this.pl26(g,k),r=Math.floor((e+1)/2),q=Math.floor((f+1)/2-1),u=Math.floor(f*f/2),v=Math.floor((b+1)/2),x=Math.floor((d+1)/2);--b;--d;var t=new pl6e;this.pl27(0,0,g-1,h-1,n);this.pl27(0,0,k-1,h-1,m);a&&(this.pla4=0);for(;this.pla4<r;this.pla4++){var w=this.pla4*f+q;for(a=0;a<g;a++)for(h=0;h<k;h++)l[a][h]=-1;for(a=0;a<g&&!(0<n[a][w]);a++);for(h=0;h<k&&!(0<m[h][w]);h++);this.pl27(a,h,g-a-1,k-h-1,l);this.pl34(l,
1);for(a=0;a<v;a++)for(h=0;h<x;h++)this.pl36(l,a*f,h*f,f)>u&&(this.pl8e[this.pla4][a][h]=1,this.pl8e[this.pla4][b-a][h]=1,this.pl8e[this.pla4][a][d-h]=1,this.pl8e[this.pla4][b-a][d-h]=1);if(500<t.pl3f())return!1}this.pl8e[e-1]=this.pl8e[0];for(f=1;f<r;f++)this.pl31(f,f-1),this.pl8e[e-1-f]=this.pl8e[f];return!0};
pl6d.prototype.pl33=function(a,b,d,e,f,g){var k=Math.floor((g+1)/2-1);e*=g;var h=Math.floor((f+1)/2),n=b*g,m=d*g,l=this.pl26(e,e),r=this.pl26(n,m),q=Math.floor((b+1)/2),u=Math.floor((d+1)/2);--b;--d;var v=Math.floor(g*g/2);this.pl27(0,0,e-1,e-1,l);var x=new pl6e;a&&(this.pla4=0);for(;this.pla4<h;this.pla4++){if(500<x.pl3f())return!1;var t=this.pla4*g+k;for(a=0;a<e&&!(0<l[a][t]);a++);var w;for(t=0;t<n;t++)for(w=0;w<m;w++)r[t][w]=-1;t=a;this.pl27(t,t,n-1-t,n-1-t,r);t=e-a-1;this.pl27(t,t,n-1-t,n-1-t,
r);this.pl35(r,1);for(t=0;t<q;t++)for(a=0;a<u;a++)this.pl36(r,t*g,a*g,g)>v&&(this.pl8e[this.pla4][t][a]=1,this.pl8e[this.pla4][b-t][a]=1,this.pl8e[this.pla4][t][d-a]=1,this.pl8e[this.pla4][b-t][d-a]=1);if(this.pla4)for(a=u-1;0<a;a--){for(t=0;t<q&&!(0<this.pl8e[this.pla4][t][a]);)t++;if(t==q)break;for(t++;t<q&&0>=this.pl8e[this.pla4][t][a-1];)t++;for(;t<q&&!(0>this.pl8e[this.pla4][t+1][a])&&!(0>this.pl8e[this.pla4][t][a+1]);)0<=this.pl8e[this.pla4-1][t][a]&&(this.pl8e[this.pla4][t][a]=0,this.pl8e[this.pla4][b-
t][a]=0,this.pl8e[this.pla4][t][d-a]=0,this.pl8e[this.pla4][b-t][d-a]=0),t++}this.pl8e[f-1-this.pla4]=this.pl8e[this.pla4]}return this.pla4>=h};pl6d.prototype.pl34=function(a,b){var d,e,f,g=a.length,k=a[0].length;for(e=0;e<k;e++){for(d=0;d<g&&-1==a[d][e];)d++;if(!(d>=g)){for(;d<g&&1<=a[d][e];)d++;for(f=g-d;d<f;)a[d++][e]=b}}};
pl6d.prototype.pl35=function(a,b){var d=Math.floor((a.length+1)/2),e=Math.floor((a[0].length+1)/2),f,g,k,h=a.length-1,n=a[0].length-1;for(g=0;g<e;g++){for(f=0;f<d&&-1==a[f][g];)f++;if(!(f>=d-1)){for(;f<d&&1<=a[f][g];)f++;if(!(f>=d-1)){for(k=f+1;k<d&&-1==a[k][g];)k++;if(!(k>=d))for(;f<=d&&-1==a[f][g];)a[f][g]=b,a[f][n-g]=b,a[h-f][g]=b,a[h-f][n-g]=b,f++}}}for(f=0;f<d;f++){for(g=0;g<e&&-1==a[f][g];)g++;if(!(g>=e-1)){for(;g<e&&1<=a[f][g];)g++;if(!(g>=e-1)){for(k=g+1;k<e&&-1==a[f][k];)k++;if(!(k>=e))for(;g<
e&&-1==a[f][g];)a[f][g]=b,a[f][n-g]=b,a[h-f][g]=b,a[h-f][n-g]=b,g++}}}};pl6d.prototype.pl36=function(a,b,d,e){var f=b+e;e=d+e;for(var g,k=0;b<f;b++)for(g=d;g<e;g++)0<a[b][g]&&k++;return k};pl6d.prototype.pl37=function(a,b,d){var e,f;for(e=0;e<b;e++){var g="";for(f=0;f<d;f++)g+=0<a[e][f]?"*":"-";console.log(g)}};pl6d.prototype.pl38=function(a,b,d,e,f){for(var g,k,h,n;b<a.length;b++){h=e;for(g=0;g<a.length;g++){n=f;for(k=0;k<a.length;k++)this.pl8e[d][h][n++]=a[b][g][k];h++}d++}};
pl6d.prototype.pl39=function(a,b){var d,e;for(d=0;d<a.length;d++)for(e=0;e<a[d].length;e++)b[d][e]=a[d][e]};pl6d.prototype.pl3a=function(a,b){var d,e;for(d=0;d<a.length;d++)for(e=0;e<a[d].length;e++)b[d][e]=0<a[d][e]?0:b[d][e]};
pl6d.prototype.pl3b=function(a,b,d,e,f){var g,k,h,n;var m=a.length;var l=b.length;var r=d+l<=m?d+l:m;m=a[0].length;l=b[0].length;var q=e+l<=m?e+l:m;m=a[0][0].length;l=b[0][0].length;m=f+l<=m?f+l:m;for(l=h=n=0;d<r;d++){for(g=e;g<q;g++){for(k=f;k<m;k++){var u=b[l][h][n];var v=a[d][g][k];-1==v&&(a[d][g][k]=u);n++}h++;n=0}l++;h=0}};
pl6d.prototype.pl3c=function(a,b,d,e,f){var g,k,h,n;var m=a.length;var l=b.length;var r=d+l<=m?d+l:m;m=a[0].length;l=b[0].length;var q=e+l<=m?e+l:m;m=a[0][0].length;l=b[0][0].length;m=f+l<=m?f+l:m;for(l=h=n=0;d<r;d++){for(g=e;g<q;g++){for(k=f;k<m;k++){var u=b[l][h][n];a[d][g][k]=u;n++}h++;n=0}l++;h=0}};pl6d.prototype.pl3d=function(a,b,d){b=Math.floor(a*b);return b%2!=a%2?d?b+1:b-1:b};
pl6d.prototype.pl3e=function(a,b,d){var e,f,g;for(e=0;e<a.length;e++)for(f=0;f<a[0].length;f++)if(0<a[e][f])for(g=this.pl8e[0].length-1;0<=g;){if(0<this.pl8e[b+f][g][d+e]){this.pl8e[b+f][g][d+e]=a[e][f];break}g--}};function pl6e(){this.pla5=(new Date).getTime()}pl6e.prototype.pl3f=function(){return(new Date).getTime()-this.pla5};function pl6f(a,b,d){this.pla6=b;this.pla7=d;this.pl40();this.pla8=a;this.pl45()}
pl6f.prototype.pl40=function(){var a=this.pla7.pl79-160;this.pla9=a-32;this.plaa=this.pla7.pl78-32-16;this.plab=this.plac=Math.floor((this.pla7.pl79-a)/2);this.plad=this.plac+a-1-32;var b=document.getElementById("pslrl");b.style.left=this.plaa+12+"px";b.style.top=this.plab+12+"px";b.style.height=a-28+"px";this.plae=document.getElementById("pslkn");this.plae.style.top=this.plab+"px";this.plae.style.left=this.plaa+"px";this.plaf=document.getElementById("pslin");this.plaf.style.top=this.plab-4+"px";
this.plaf.style.left=this.plaa-70+"px";b=document.getElementById("pslbn0");b.style.left=this.plaa-4+"px";b.style.top=this.plab-40+"px";b=document.getElementById("pslbn1");b.style.left=this.plaa-4+"px";b.style.top=this.plab+a+"px";this.pl46(this.pla8)};pl6f.prototype.pl41=function(a,b){return!this.pla7.pl87&&a>=this.plaa&&a<=this.plaa+32&&b>=this.plab&&b<=this.plab+32};pl6f.prototype.pl42=function(a,b){this.plb0=b;this.plb1=b-this.plab;this.plaf.style.visibility="visible";this.pl45()};
pl6f.prototype.pl43=function(a,b){var d=this.plb0+b-this.plb0-this.plb1;d<this.plac?d=this.plac:d>this.plad&&(d=this.plad);this.plae.style.top=d+"px";this.plaf.style.top=d-4+"px";this.plab=d;this.pl45()};pl6f.prototype.pl44=function(){this.plaf.style.visibility="hidden";this.pla7.pl1(null,this.pla8-1,-1)};pl6f.prototype.pl45=function(){this.pla8=this.pla6-Math.floor(this.pla6*(this.plab-this.plac)/this.pla9);this.plaf.innerHTML=this.plae.innerHTML=this.pla8};
pl6f.prototype.pl46=function(a){a>this.pla6?a=this.pla6:1>a&&(a=1);newY=this.plac+this.pla9-1-Math.floor((a-1)*(this.pla9-1)/(this.pla6-1));this.plae.style.top=newY+"px";this.plaf.style.top=newY-4+"px";this.plab=newY;this.pla8=a;this.plaf.innerHTML=this.plae.innerHTML=this.pla8};function pl70(){this.plb2=0}
pl70.prototype.pl47=function(){document.getElementById("ptb").innerHTML='<div class="seglt" id="ptbiso"><div id="seglbn">3D</div></div><div class="segrt" id="ptbflt"><div id="segrbn">2D</div></div><div class="ptbt48" id="ptbz"><div class="ptbbn" id="ptbzv">zoom</div></div><div class="ptbt96" id="ptbm"><div class="ptbbn" id="ptbmv"></div></div>';this.pla7=new pl6c(0,0);this.plb3=new pl71(this.pla7);this.plb3.pl5b();this.plb3.pl4c();this.pl4c();this.pla7.pl1d();this.pl4b(!0);this.plb3.pl67()};
pl70.prototype.pl4b=function(a){var b=a?"visible":"hidden";document.getElementById("pctl").style.visibility=b;document.getElementById("ptb").style.visibility=b;document.getElementById("pslrl").style.visibility=b;document.getElementById("pslbn0").style.visibility=b;document.getElementById("pslbn1").style.visibility=b;document.getElementById("pslkn").style.visibility=b;document.getElementById("pcon").style.visibility=b;document.getElementById("pbc").style.visibility=b;a||this.pla7.pl89&&this.pla7.pl1f()};
pl70.prototype.pl4c=function(){document.getElementById("pev").addEventListener("click",this.pl51,!1);document.getElementById("pev").addEventListener("mousedown",this.pl53,!1);document.getElementById("pev").addEventListener("mousemove",this.pl54,!1);document.getElementById("pev").addEventListener("mouseout",this.pl55,!1);document.getElementById("pev").addEventListener("mouseup",this.pl55,!1);document.getElementById("pev").addEventListener("touchstart",this.pl52,!1);document.getElementById("pev").addEventListener("touchmove",
this.pl56,!1);document.getElementById("pev").addEventListener("touchend",this.pl57,!1);document.getElementById("pslbn0").addEventListener("click",function(a){plcc.pla7.pl15(a,plcc.pl4f)},!1);document.getElementById("pslbn1").addEventListener("click",function(a){plcc.pla7.pl15(a,plcc.pl50)},!1);document.getElementById("ptbz").addEventListener("click",function(a){plcc.pla7.pl15(a,plcc.pl0)},!1);document.getElementById("ptbiso").addEventListener("click",function(a){plcc.pl58()},!1);document.getElementById("ptbflt").addEventListener("click",
function(a){plcc.pl59()},!1);document.getElementById("ptbm").addEventListener("click",function(a){a.preventDefault();plcc.pl4e()},!1);document.getElementById("pvlhd").addEventListener("click",function(a){plcc.pla7.pl1e()},!1);var a;for(a=0;a<this.pla7.pl85.length;a++)document.getElementById("pv"+a+"bn0").addEventListener("click",function(a){plcc.pla7.pl15(a,plcc.pla7.pl1b)},!1),document.getElementById("pv"+a+"bn1").addEventListener("click",function(a){plcc.pla7.pl15(a,plcc.pla7.pl1c)},!1);window.onresize=
function(a){pto&&clearTimeout(pto);pto=setTimeout(plcc.pla7.pl23,200)};"onorientationchange"in window&&(window.onorientationchange=function(a){pto=setTimeout(plcc.pla7.pl23,10)})};pl70.prototype.pl4d=function(){alert("objectUpdate")};pl70.prototype.pl4e=function(){window.top.location.href="/plotz-menu.php"};pl70.prototype.pl0=function(){plcc.pla7.pl0();document.getElementById("ptbzv").innerHTML=1==plcc.pla7.pl7e?"100%":100*plcc.pla7.pl7e+"%";plcc.pla7.pl16()};
pl70.prototype.pl4f=function(a){plcc.pla7.pl87||(a=plcc.pla7.pl8f,a<plcc.pla7.pl8e.length?(a++,plcc.pla7.pl1(null,a,-1)):plcc.pla7.pl16())};pl70.prototype.pl50=function(a){plcc.pla7.pl87||(a=plcc.pla7.pl8f,1==plcc.pla7.pl7f&&plcc.pla7.pl8f>=plcc.pla7.pl8e.length&&a--,a?(a--,plcc.pla7.pl1(null,a,-1)):plcc.pla7.pl16())};pl70.prototype.pl51=function(a){};pl70.prototype.pl52=function(a){a.preventDefault();plcc.pla7.pld(a)};pl70.prototype.pl53=function(a){plcc.pla7.plc(a)};pl70.prototype.pl54=function(a){plcc.pla7.plf(a)};
pl70.prototype.pl55=function(a){plcc.pla7.pl11(a)};pl70.prototype.pl56=function(a){plcc.pla7.ple(a)};pl70.prototype.pl57=function(a){plcc.pla7.pl10(a)};pl70.prototype.pl58=function(){plcc.pl5a(0)};pl70.prototype.pl59=function(){plcc.pl5a(1)};pl70.prototype.pl5a=function(a){this.pla7.pl1a(a);this.pla7.pl1(null,this.pla7.pl8f,-1)};var plcc;function plcd(){plcc=new pl70;plcc.pl47()}window.onload=setTimeout(plcd,100);
function pl71(a){this.plb4=64;this.plb6=this.plb5=32;this.plb7=5;this.plb8=!0;this.pla7=a;a=document.getElementById("pctl");/*var b=new XMLHttpRequest;b.open("GET","/plotzhtml5/pclt.php?o=1",!1);b.send(null);200===b.status&&(a.style.width="204px",a.style.height="160px",a.innerHTML=b.responseText)*/}
pl71.prototype.pl4c=function(){var a=this.pla7.touch?"touchstart":"click";document.getElementById("st0").addEventListener(a,function(a){plcc.pla7.pl15(a,plcc.plb3.pl67);return!1},!1);document.getElementById("st1").addEventListener(a,function(a){plcc.pla7.pl15(a,plcc.plb3.pl67);return!1},!1);document.getElementById("st2").addEventListener(a,function(a){plcc.pla7.pl15(a,plcc.plb3.pl67);return!1},!1);document.getElementById("st3").addEventListener(a,function(a){plcc.pla7.pl15(a,plcc.plb3.pl67);return!1},
!1);document.getElementById("b0").addEventListener(a,function(a){plcc.pla7.pl15(a,plcc.plb3.pl60);return!1},!1);document.getElementById("b1").addEventListener(a,function(a){plcc.pla7.pl15(a,plcc.plb3.pl5f);return!1},!1);document.getElementById("b2").addEventListener(a,function(a){plcc.pla7.pl15(a,plcc.plb3.pl62);return!1},!1);document.getElementById("b3").addEventListener(a,function(a){plcc.pla7.pl15(a,plcc.plb3.pl61);return!1},!1);document.getElementById("b4").addEventListener(a,function(a){plcc.pla7.pl15(a,
plcc.plb3.pl64);return!1},!1);document.getElementById("b5").addEventListener(a,function(a){plcc.pla7.pl15(a,plcc.plb3.pl63);return!1},!1);document.getElementById("b6").addEventListener(a,function(a){plcc.pla7.pl15(a,plcc.plb3.pl66);return!1},!1);document.getElementById("b7").addEventListener(a,function(a){plcc.pla7.pl15(a,plcc.plb3.pl65);return!1},!1);document.getElementById("ptbmv").innerHTML="Ellipsoid"};
pl71.prototype.pl5b=function(){this.pla7.pl87=!0;this.pl5e();this.plb9=new pl6d(this.plb4,this.plb5,this.plb6);this.plb9.pla0=1;this.plba=!0;this.pl5c()};pl71.prototype.pl5c=function(){var a=plcc.plb3;a.plb9.pl32(a.plba,a.plb5,a.plb6,a.plb4,2*a.plb7-1)?a.plba?a.pl5d():(a.pla7.pl18("rendering"),setTimeout(plcc.plb3.pl5d,50)):(a.plba&&(a.plba=!1,a.pla7.pl17()),a.pla7.pl18("Creating ellipsoid "+Math.floor(200*a.plb9.pla4/a.plb9.pl9e)+"%"),setTimeout(plcc.plb3.pl5c,50))};
pl71.prototype.pl5d=function(){plcc.pla7.pl1(plcc.plb3.plb9.pl8e,plcc.plb3.plb9.pl9e,0);plcc.pla7.pl19();plcc.pla7.pl87=!1};pl71.prototype.pl5e=function(){document.getElementById("sz0").innerHTML=this.plb4;document.getElementById("sz1").innerHTML=this.plb5;document.getElementById("sz2").innerHTML=this.plb6;document.getElementById("sz3").innerHTML=this.plb7};pl71.prototype.pl5f=function(){var a=plcc.plb3;256>a.plb4?(a.plb4++,a.pl5b()):a.pla7.pl16()};
pl71.prototype.pl60=function(){var a=plcc.plb3;8<a.plb4?(a.plb4--,a.pl5b()):a.pla7.pl16()};pl71.prototype.pl61=function(){var a=plcc.plb3;256>a.plb5?(a.plb5++,a.pl5b()):a.pla7.pl16()};pl71.prototype.pl62=function(){var a=plcc.plb3;8<a.plb5?(a.plb5--,a.pl5b()):a.pla7.pl16()};pl71.prototype.pl63=function(){var a=plcc.plb3;256>a.plb6?(a.plb6++,a.pl5b()):a.pla7.pl16()};pl71.prototype.pl64=function(){var a=plcc.plb3;8<a.plb6?(a.plb6--,a.pl5b()):a.pla7.pl16()};
pl71.prototype.pl65=function(){var a=plcc.plb3;6>a.plb7?(a.plb7++,a.pl5b()):a.pla7.pl16()};pl71.prototype.pl66=function(){var a=plcc.plb3;1<a.plb7?(a.plb7--,a.pl5b()):a.pla7.pl16()};
pl71.prototype.pl67=function(){document.getElementById("pctl").style.visibility="hidden";document.getElementById("pvl").style.visibility="visible";var a=plcc.pla7.pl79-160,b;for(b=0;4>b;b++)plcc.pla7.pl85[b].pl69(64,a,plcc.pla7.pl78-64-64),a+=40;plcc.pla7.pl85[0].pl6a(8,plcc.plb3.plb4,256);plcc.pla7.pl85[1].pl6a(8,plcc.plb3.plb5,256);plcc.pla7.pl85[2].pl6a(8,plcc.plb3.plb6,256);plcc.pla7.pl85[3].pl6a(1,plcc.plb3.plb7,6);plcc.pla7.pl89=!0};
pl71.prototype.pl68=function(a,b){0==a?this.plb4=b:1==a?this.plb5=b:2==a?this.plb6=b:3==a&&(this.plb7=b);this.pl5b()};pl71.prototype.pl1b=function(a){0==a?(this.pl60(),this.pla7.pl85[0].pl46(this.plb4)):1==a?(this.pl62(),this.pla7.pl85[1].pl46(this.plb5)):2==a?(this.pl64(),this.pla7.pl85[2].pl46(this.plb6)):3==a&&(this.pl66(),this.pla7.pl85[3].pl46(this.plb7))};
pl71.prototype.pl1c=function(a){0==a?(this.pl5f(),this.pla7.pl85[0].pl46(this.plb4)):1==a?(this.pl61(),this.pla7.pl85[1].pl46(this.plb5)):2==a?(this.pl63(),this.pla7.pl85[2].pl46(this.plb6)):3==a&&(this.pl65(),this.pla7.pl85[3].pl46(this.plb7))};function pl72(a,b,d,e,f){this.plbb=a;this.plbc=b;this.plbd=d;this.plbe=e;this.plbf=f}
function pl73(a){this.plc0=a;this.plc2=this.plc1=0;this.plc3=document.getElementById("pv"+a+"bn0");this.plc4=document.getElementById("pv"+a+"bn1");this.plc5=document.getElementById("pvrl"+a);this.plae=document.getElementById("pvkn"+a);this.plaf=document.getElementById("pvin"+a);this.plc6=!1}
pl73.prototype.pl69=function(a,b,d){this.plc3.style.left=a+"px";this.plc3.style.top=b+"px";this.plc4.style.left=a+d-40+"px";this.plc4.style.top=b+"px";this.plc5.style.left=a+52+"px";this.plc5.style.top=b+16+"px";this.plc5.style.width=d-40-40-12-12+"px";this.plc7=a+40;this.plc8=d-40-40-32;this.plc9=this.plc7+this.plc8;this.plaa=a+40;this.plab=b+4;this.plae.style.left=this.plaa+"px";this.plae.style.top=this.plab+"px";this.plaf.style.left=this.plaa-16+"px";this.plaf.style.top=this.plab-44+"px"};
pl73.prototype.pl6a=function(a,b,d){this.plc3.style.visibility="visible";this.plc4.style.visibility="visible";this.plc5.style.visibility="visible";this.plae.style.visibility="visible";this.plc6=!0;this.plc1=a-1;this.pla6=1+d-a;this.pl46(b)};pl73.prototype.pl6b=function(a,b){this.pla6=b-this.plc1;this.pl46(a)};
pl73.prototype.pl46=function(a){a>this.pla6+this.minValu1?a=this.pla6+this.plc1:a<this.plc1+1&&(a=this.plc1+1);a-=this.plc1;newX=this.plc7+Math.floor(a*this.plc8/this.pla6)-1;this.plae.style.left=newX+"px";this.plaf.style.left=newX-16+"px";this.plaa=newX;this.pla8=a;this.plae.innerHTML=this.pla8+this.plc1};pl73.prototype.pl41=function(a,b){return!plcc.pla7.pl87&&this.plc6&&a>=this.plaa-4&&a<=this.plaa+40&&b>=this.plab-4&&b<=this.plab+40};
pl73.prototype.pl42=function(a,b){this.plca=a;this.plcb=a-this.plaa;this.plaf.style.visibility="visible";this.pl45()};pl73.prototype.pl43=function(a,b){var d=this.plca+a-this.plca-this.plcb;d<this.plc7?d=this.plc7:d>this.plc9-1&&(d=this.plc9-1);this.plae.style.left=d+"px";this.plaf.style.left=d-16+"px";this.plaa=d;this.pl45()};pl73.prototype.pl44=function(){this.plaf.style.visibility="hidden";this.pl46(this.pla8+this.plc1);plcc.plb3.pl68(this.plc0,this.pla8+this.plc1)};
pl73.prototype.pl45=function(){this.pla8=1+Math.floor(this.pla6*(this.plaa-this.plc7)/this.plc8);this.plaf.innerHTML=this.plae.innerHTML=this.pla8+this.plc1};
