function pl66(a,b,d){this.pl6e=b;this.pl6f=d;this.pl0();this.pl70=a;this.pl5()}
pl66.prototype.pl0=function(){var a=this.pl6f.pl92-160;this.pl71=a-32;this.pl72=this.pl6f.pl91-32-16;this.pl73=this.pl74=Math.floor((this.pl6f.pl92-a)/2);this.pl75=this.pl74+a-1-32;var b=document.getElementById("pslrl");b.style.left=this.pl72+12+"px";b.style.top=this.pl73+12+"px";b.style.height=a-28+"px";this.pl76=document.getElementById("pslkn");this.pl76.style.top=this.pl73+"px";this.pl76.style.left=this.pl72+"px";this.pl77=document.getElementById("pslin");this.pl77.style.top=this.pl73-4+"px";this.pl77.style.left=
this.pl72-70+"px";b=document.getElementById("pslbn0");b.style.left=this.pl72-4+"px";b.style.top=this.pl73-40+"px";b=document.getElementById("pslbn1");b.style.left=this.pl72-4+"px";b.style.top=this.pl73+a+"px";this.pl6(this.pl70)};pl66.prototype.pl1=function(a,b){return!this.pl6f.pla0&&a>=this.pl72&&a<=this.pl72+32&&b>=this.pl73&&b<=this.pl73+32};pl66.prototype.pl2=function(a,b){this.pl78=b;this.pl79=b-this.pl73;this.pl77.style.visibility="visible";this.pl5()};
pl66.prototype.pl3=function(a,b){var d=this.pl78+b-this.pl78-this.pl79;d<this.pl74?d=this.pl74:d>this.pl75&&(d=this.pl75);this.pl76.style.top=d+"px";this.pl77.style.top=d-4+"px";this.pl73=d;this.pl5()};pl66.prototype.pl4=function(){this.pl77.style.visibility="hidden";this.pl6f.pl1f(null,this.pl70-1,-1)};pl66.prototype.pl5=function(){this.pl70=this.pl6e-Math.floor(this.pl6e*(this.pl73-this.pl74)/this.pl71);this.pl77.innerHTML=this.pl76.innerHTML=this.pl70};
pl66.prototype.pl6=function(a){a>this.pl6e?a=this.pl6e:1>a&&(a=1);newY=this.pl74+this.pl71-1-Math.floor((a-1)*(this.pl71-1)/(this.pl6e-1));this.pl76.style.top=newY+"px";this.pl77.style.top=newY-4+"px";this.pl73=newY;this.pl70=a;this.pl77.innerHTML=this.pl76.innerHTML=this.pl70};function pl67(a,b,d,f,e){this.pl7a=a;this.pl7b=b;this.pl7c=d;this.pl7d=f;this.pl7e=e}function pl68(){this.pl7f=0}
pl68.prototype.pl7=function(){document.getElementById("ptb").innerHTML='<div class="seglt" id="ptbiso"><div id="seglbn">3D</div></div><div class="segrt" id="ptbflt"><div id="segrbn">2D</div></div><div class="ptbt48" id="ptbz"><div class="ptbbn" id="ptbzv">zoom</div></div><div class="ptbt96" id="ptbm"><div class="ptbbn" id="ptbmv"></div></div>';this.pl6f=new pl6a(0,0);this.pl80=new pl6b(this.pl6f);this.pl80.pl42();this.pl80.plc();this.plc();this.pl6f.pl3b();this.plb(!0);this.pl80.pl48()};
pl68.prototype.plb=function(a){var b=a?"visible":"hidden";document.getElementById("pctl").style.visibility=b;document.getElementById("ptb").style.visibility=b;document.getElementById("pslrl").style.visibility=b;document.getElementById("pslbn0").style.visibility=b;document.getElementById("pslbn1").style.visibility=b;document.getElementById("pslkn").style.visibility=b;document.getElementById("pcon").style.visibility=b;document.getElementById("pbc").style.visibility=b;a||this.pl6f.pla2&&this.pl6f.pl3d()};
pl68.prototype.plc=function(){document.getElementById("pev").addEventListener("click",this.pl12,!1);document.getElementById("pev").addEventListener("mousedown",this.pl14,!1);document.getElementById("pev").addEventListener("mousemove",this.pl15,!1);document.getElementById("pev").addEventListener("mouseout",this.pl16,!1);document.getElementById("pev").addEventListener("mouseup",this.pl16,!1);document.getElementById("pev").addEventListener("touchstart",this.pl13,!1);document.getElementById("pev").addEventListener("touchmove",
this.pl17,!1);document.getElementById("pev").addEventListener("touchend",this.pl18,!1);document.getElementById("pslbn0").addEventListener("click",function(a){plc7.pl6f.pl33(a,plc7.pl10)},!1);document.getElementById("pslbn1").addEventListener("click",function(a){plc7.pl6f.pl33(a,plc7.pl11)},!1);document.getElementById("ptbz").addEventListener("click",function(a){plc7.pl6f.pl33(a,plc7.plf)},!1);document.getElementById("ptbiso").addEventListener("click",function(a){plc7.pl19()},!1);document.getElementById("ptbflt").addEventListener("click",
function(a){plc7.pl1a()},!1);document.getElementById("ptbm").addEventListener("click",function(a){a.preventDefault();plc7.ple()},!1);document.getElementById("pvlhd").addEventListener("click",function(a){plc7.pl6f.pl3c()},!1);var a;for(a=0;a<this.pl6f.pl9e.length;a++)document.getElementById("pv"+a+"bn0").addEventListener("click",function(a){plc7.pl6f.pl33(a,plc7.pl6f.pl39)},!1),document.getElementById("pv"+a+"bn1").addEventListener("click",function(a){plc7.pl6f.pl33(a,plc7.pl6f.pl3a)},!1);window.onresize=
function(a){pto&&clearTimeout(pto);pto=setTimeout(plc7.pl6f.pl41,200)};"onorientationchange"in window&&(window.onorientationchange=function(a){pto=setTimeout(plc7.pl6f.pl41,10)})};pl68.prototype.pld=function(){alert("objectUpdate")};pl68.prototype.ple=function(){window.top.location.href="/plotz-menu.php"};pl68.prototype.plf=function(){plc7.pl6f.plf();document.getElementById("ptbzv").innerHTML=1==plc7.pl6f.pl97?"100%":100*plc7.pl6f.pl97+"%";plc7.pl6f.pl34()};
pl68.prototype.pl10=function(a){plc7.pl6f.pla0||(a=plc7.pl6f.pla8,a<plc7.pl6f.pla7.length?(a++,plc7.pl6f.pl1f(null,a,-1)):plc7.pl6f.pl34())};pl68.prototype.pl11=function(a){plc7.pl6f.pla0||(a=plc7.pl6f.pla8,1==plc7.pl6f.pl98&&plc7.pl6f.pla8>=plc7.pl6f.pla7.length&&a--,a?(a--,plc7.pl6f.pl1f(null,a,-1)):plc7.pl6f.pl34())};pl68.prototype.pl12=function(a){};pl68.prototype.pl13=function(a){a.preventDefault();plc7.pl6f.pl2b(a)};pl68.prototype.pl14=function(a){plc7.pl6f.pl2a(a)};pl68.prototype.pl15=function(a){plc7.pl6f.pl2d(a)};
pl68.prototype.pl16=function(a){plc7.pl6f.pl2f(a)};pl68.prototype.pl17=function(a){plc7.pl6f.pl2c(a)};pl68.prototype.pl18=function(a){plc7.pl6f.pl2e(a)};pl68.prototype.pl19=function(){plc7.pl1b(0)};pl68.prototype.pl1a=function(){plc7.pl1b(1)};pl68.prototype.pl1b=function(a){this.pl6f.pl38(a);this.pl6f.pl1f(null,this.pl6f.pla8,-1)};var plc7;function plc8(){plc7=new pl68;plc7.pl7()}window.onload=setTimeout(plc8,100);
function pl69(a){this.pl81=a;this.pl83=this.pl82=0;this.pl84=document.getElementById("pv"+a+"bn0");this.pl85=document.getElementById("pv"+a+"bn1");this.pl86=document.getElementById("pvrl"+a);this.pl76=document.getElementById("pvkn"+a);this.pl77=document.getElementById("pvin"+a);this.pl87=!1}
pl69.prototype.pl1c=function(a,b,d){this.pl84.style.left=a+"px";this.pl84.style.top=b+"px";this.pl85.style.left=a+d-40+"px";this.pl85.style.top=b+"px";this.pl86.style.left=a+52+"px";this.pl86.style.top=b+16+"px";this.pl86.style.width=d-40-40-12-12+"px";this.pl88=a+40;this.pl89=d-40-40-32;this.pl8a=this.pl88+this.pl89;this.pl72=a+40;this.pl73=b+4;this.pl76.style.left=this.pl72+"px";this.pl76.style.top=this.pl73+"px";this.pl77.style.left=this.pl72-16+"px";this.pl77.style.top=this.pl73-44+"px"};
pl69.prototype.pl1d=function(a,b,d){this.pl84.style.visibility="visible";this.pl85.style.visibility="visible";this.pl86.style.visibility="visible";this.pl76.style.visibility="visible";this.pl87=!0;this.pl82=a-1;this.pl6e=1+d-a;this.pl6(b)};pl69.prototype.pl1e=function(a,b){this.pl6e=b-this.pl82;this.pl6(a)};
pl69.prototype.pl6=function(a){a>this.pl6e+this.minValu1?a=this.pl6e+this.pl82:a<this.pl82+1&&(a=this.pl82+1);a-=this.pl82;newX=this.pl88+Math.floor(a*this.pl89/this.pl6e)-1;this.pl76.style.left=newX+"px";this.pl77.style.left=newX-16+"px";this.pl72=newX;this.pl70=a;this.pl76.innerHTML=this.pl70+this.pl82};pl69.prototype.pl1=function(a,b){return!plc7.pl6f.pla0&&this.pl87&&a>=this.pl72-4&&a<=this.pl72+40&&b>=this.pl73-4&&b<=this.pl73+40};
pl69.prototype.pl2=function(a,b){this.pl8b=a;this.pl8c=a-this.pl72;this.pl77.style.visibility="visible";this.pl5()};pl69.prototype.pl3=function(a,b){var d=this.pl8b+a-this.pl8b-this.pl8c;d<this.pl88?d=this.pl88:d>this.pl8a-1&&(d=this.pl8a-1);this.pl76.style.left=d+"px";this.pl77.style.left=d-16+"px";this.pl72=d;this.pl5()};pl69.prototype.pl4=function(){this.pl77.style.visibility="hidden";this.pl6(this.pl70+this.pl82);plc7.pl80.pl49(this.pl81,this.pl70+this.pl82)};
pl69.prototype.pl5=function(){this.pl70=1+Math.floor(this.pl6e*(this.pl72-this.pl88)/this.pl89);this.pl77.innerHTML=this.pl76.innerHTML=this.pl70+this.pl82};
function pl6a(a,b){var d=document.getElementById("pcan");a?(d.width=a,d.height=b):(a=d.width=window.innerWidth-120,b=d.height=window.innerHeight-0);this.pl8d=d.offsetLeft;this.pl8e=d.offsetTop;this.pl8f=d.getContext("2d");this.pl90=document.getElementById("pev");this.pl90.style.width=a+"px";this.pl90.style.height=b+"px";this.pl91=a;this.pl92=b;this.pl93=a;this.pl94=b;this.pl96=this.pl95=0;this.pl97=1;this.pl99=this.pl98=0;this.pl9a=[];this.pl9b=[];this.pl9c=[];this.pl9b[0]=["#000000","#ffff00","#b1b100",
"#5b5b00"];this.pl9b[1]=["#000000","#c0c0c0","#808080","#5f5f5f"];this.pl9b[2]=["#000000","#303060","#202040","#101020"];this.pl9b[3]=["#000000","#E0E0E0","#A0A0A0","#808080"];this.pl9b[4]=["#808080","#ffffff","#E0E0E0","#C0C0C0"];this.pl9b[5]=["#000000","#A00000","#700000","#400000"];this.pl9b[6]=["#808080","rgba(255, 255, 255, 0.09)","rgba(224, 224, 224, 0.09)","rgba(192, 192, 192, 0.09)"];this.pl9b[7]=["#333333","#FF8C00","#B16100","#5B3200"];this.pl9c[0]=["#000000","#b1b100"];this.pl9c[1]=["#000000",
"#808080"];this.pl9c[2]=["#000000","#202040"];this.pl9c[3]=["#000000","#A0A0A0"];this.pl9c[4]=["#000000","#E0E0E0"];this.pl9c[5]=["#000000","#700000"];this.pl9c[6]=["#000000","#80c0ff"];this.pl9c[7]=["#000000","#B16100"];this.pl9d=new pl66(32,32,this);this.pl9e=Array(4);for(d=0;4>d;d++)this.pl9e[d]=new pl69(d);this.pl9f=document.getElementById("pcon");this.pl9f.style.display="none";this.pla0=!1;this.pla1=!0;this.pla2=!1}
pl6a.prototype.plf=function(){var a=this.pl97;this.pl97=4>this.pl97?2*this.pl97:1;this.log("zoom="+this.pl97);if(1<this.pl97){this.pla1?(this.pla3=document.createElement("canvas"),this.pla3.width=this.pl91,this.pla3.height=this.pl92,this.pl93=this.pl91*this.pl97,this.pl94=this.pl92*this.pl97):(this.pla3=document.createElement("canvas"),this.pl93=this.pla3.width=this.pl91*this.pl97,this.pl94=this.pla3.height=this.pl92*this.pl97);this.pla4=this.pla3.getContext("2d");var b=(this.pl95+this.pl91/2)/a;
a=(this.pl96+this.pl92/2)/a;this.pla5=this.pl95=b*this.pl97-this.pl91/2;this.pla6=this.pl96=a*this.pl97-this.pl92/2;console.log("zoomOffX="+this.pl95+", this.pl96="+this.pl96+", cx="+b+", cy="+a)}else this.pla4=this.pla3=null,this.pl93=this.pl91,this.pl94=this.pl92,this.pl96=this.pla6=this.pl95=this.pla5=0;0==this.pl98?(this.pl26(),this.pl21()):(this.pl25(),this.pl20())};
pl6a.prototype.pl1f=function(a,b,d){a&&(this.pla7=a,this.pl38(0));this.pla8=b;0==this.pl98?this.pl21():this.pl20();this.pl9d.pl6e!=this.pla7.length&&(this.pl9d.pl6e=this.pla7.length);this.pl9d.pl6(this.pla8+1);this.pl34()};
pl6a.prototype.pl20=function(){var a,b,d=1==this.pla7.length;var f=this.pla8>this.pla7.length-1?this.pla7.length-1:this.pla8;new pl6d;if(1<this.pl97){var e=this.pla4;if(this.pla1){var g=this.plac-this.pl95;var h=this.plad-this.pl96;e.clearRect(0,0,this.pl91,this.pl92)}else e.clearRect(0,0,this.pl93,this.pl94)}else e=this.pl8f,g=this.plac,h=this.plad;this.pl8f.clearRect(0,0,this.pl91,this.pl92);var k=this.pla7[0].length;var n=this.pla7[0][0].length;for(a=0;a<k;a++)for(b=0;b<n;b++)e.drawImage(this.plae,
g+a*this.plab,h+b*this.plaa);if(0<f){var m=this.pla7[f-1];for(a=0;a<k;a++)for(b=0;b<n;b++)0<m[a][b]&&e.drawImage(this.plaf,g+a*this.plab,h+b*this.plaa)}m=this.pla7[f];for(a=0;a<k;a++)for(b=0;b<n;b++)f=m[a][b],0>=f||(e.drawImage(this.plb0[f],g+a*this.plab,h+b*this.plaa),d&&this.pla9++);e.beginPath();e.lineWidth=1;e.strokeStyle="#a00000";a=1+g+Math.floor(k/2)*this.plab-1;e.moveTo(a+.5,h);e.lineTo(a+.5,1+h+n*this.plaa);k%2&&(a+=this.plab,e.moveTo(a+.5,h),e.lineTo(a+.5,1+h+n*this.plaa));e.stroke();e.beginPath();
e.lineWidth=1;e.strokeStyle="#008000";b=1+h+Math.floor(n/2)*this.plaa-1;e.moveTo(g,b+.5);e.lineTo(1+g+k*this.plab,b+.5);n%2&&(b+=this.plaa,e.moveTo(g,b+.5),e.lineTo(1+g+k*this.plab,b+.5));e.stroke();plc7.pl80.plb9&&this.pl3e(e);plc7.pl80.innerEdgeSizes&&this.pl3f(e);1<this.pl97&&this.pla1&&this.pl8f.drawImage(this.pla3,0,0,this.pl91,this.pl92,0,0,this.pl91,this.pl92)};
pl6a.prototype.pl21=function(){1<this.pl97?(this.pl8f.clearRect(0,0,this.pl91,this.pl92),this.pla1?(this.pl23(),this.pl8f.drawImage(this.pla3,0,0,this.pl91,this.pl92,0,0,this.pl91,this.pl92)):(this.pl24(),this.pl8f.drawImage(this.pla3,this.pl95,this.pl96,this.pl91,this.pl92,0,0,this.pl91,this.pl92))):this.pl22()};
pl6a.prototype.pl22=function(){var a,b,d=this.pla8>=this.pla7.length-1,f=this.pla8>this.pla7.length-1?this.pla7.length-1:this.pla8,e;d&&(this.pla9=0);this.pl8f.clearRect(0,0,this.pl91,this.pl92);for(e=0;e<=f;e++){var g=this.pla8<=this.pla7.length-1&&e==this.pla8;var h=this.pla7[e];for(a=0;a<h.length;a++)for(b=0;b<h[a].length;b++){var k=h[a][b];0<k&&(d&&this.pla9++,g&&(k=0),this.pl8f.drawImage(this.pl9a[k],this.plac+(a-b)*this.plb1,this.plad+(a+b)*this.plb2/2-e*this.plb2))}}document.getElementById("pbc").innerHTML=
this.pla9};pl6a.prototype.pl23=function(){var a,b,d=this.pla8>=this.pla7.length-1,f=this.pla8>this.pla7.length-1?this.pla7.length-1:this.pla8,e,g=0+this.plac-this.pla5,h=0+this.plad-this.pla6;this.pla4.clearRect(0,0,this.pl91,this.pl92);for(e=0;e<=f;e++){var k=this.pla8<=this.pla7.length-1&&e==this.pla8;var n=this.pla7[e];for(a=0;a<n.length;a++)for(b=0;b<n[a].length;b++){var m=n[a][b];0<m&&(d&&this.pla9++,k&&(m=0),this.pla4.drawImage(this.pl9a[m],g+(a-b)*this.plb1,h+(a+b)*this.plb2/2-e*this.plb2))}}};
pl6a.prototype.pl24=function(){var a,b,d=this.pla8>=this.pla7.length-1,f=this.pla8>this.pla7.length-1?this.pla7.length-1:this.pla8,e;this.pla4.clearRect(0,0,this.pl93,this.pl94);for(e=0;e<=f;e++){var g=this.pla8<=this.pla7.length-1&&e==this.pla8;var h=this.pla7[e];for(a=0;a<h.length;a++)for(b=0;b<h[a].length;b++){var k=h[a][b];0<k&&(d&&this.pla9++,g&&(k=0),this.pla4.drawImage(this.pl9a[k],this.plac+(a-b)*this.plb1,this.plad+(a+b)*this.plb2/2-e*this.plb2))}}};
pl6a.prototype.pl25=function(){var a=this.pla7[0].length,b=this.pla7[0][0].length;this.pl91/a<this.pl92/b?this.plaa=this.plab=Math.floor((this.pl91-40)/a)*this.pl97:this.plab=this.plaa=Math.floor((this.pl92-40)/b)*this.pl97;this.plac=Math.floor((this.pl91*this.pl97-a*this.plab)/2);this.plad=Math.floor((this.pl92*this.pl97-b*this.plaa)/2);this.plae=this.pl27("#e0e0e0","#ffffff");this.plaf=this.pl27("#a0a0a0","#e8e8e8");this.plb0=[];for(a=0;a<this.pl9c.length;a++)this.plb0[a]=this.pl27(this.pl9c[a][0],
this.pl9c[a][1])};
pl6a.prototype.pl26=function(){var a,b,d,f=-1E4,e=-1E4,g=1E4,h=1E4;var k=this.pla7.length;var n=this.pla7[0].length;var m=this.pla7[0][0].length;for(a=0;a<k;a++)for(b=0;b<n;b++)for(d=0;d<m;d++)if(0<this.pla7[a][b][d]){var l=64*(b-d)/2;l<g&&(g=l);l>f&&(f=l);l=36*(b+d)/2-36*a;l<h&&(h=l);l>e&&(e=l)}(f-g)/this.pl91>(e-h)/this.pl92?(this.plab=Math.floor((this.pl91-40)/((f-g)/64+1)*this.pl97),this.plaa=Math.round(72*this.plab/64)):(this.plaa=Math.floor((this.pl92-40)/((e-h)/72+1)*this.pl97),this.plab=Math.round(64*
this.plaa/72));this.plac=Math.floor((this.pl93-(f+g)/64*this.plab-this.plab)/2);this.plad=Math.floor((this.pl94-(e+h)/72*this.plaa-this.plaa)/2);this.plb1=this.plab/2;this.plb2=this.plaa/2;for(a=0;a<this.pl9b.length;a++)this.pl9a[a]=this.pl28(a)};pl6a.prototype.pl27=function(a,b){var d=document.createElement("canvas");d.width=this.plab+2;d.height=this.plaa+2;var f=d.getContext("2d");f.strokeStyle=a;f.fillStyle=b;f.lineWidth=1;f.beginPath();f.rect(.5,.5,this.plab,this.plaa);f.fill();f.stroke();return d};
pl6a.prototype.pl28=function(a){var b=Array(7);b[0]=[.5*this.plab,0];b[1]=[this.plab,.25*this.plaa];b[2]=[this.plab,.75*this.plaa];b[3]=[.5*this.plab,this.plaa];b[4]=[0,.75*this.plaa];b[5]=[0,.25*this.plaa];b[6]=[.5*this.plab,.5*this.plaa];var d=document.createElement("canvas");d.width=this.plab+1;d.height=this.plaa+1;var f=d.getContext("2d");f.lineWidth=.75;f.strokeStyle=this.pl9b[a][0];f.beginPath();f.moveTo(.5+b[0][0],.5+b[0][1]);f.lineTo(.5+b[1][0],.5+b[1][1]);f.lineTo(.5+b[6][0],.5+b[6][1]);
f.lineTo(.5+b[5][0],.5+b[5][1]);f.closePath();f.fillStyle=this.pl9b[a][1];f.fill();f.stroke();f.beginPath();f.moveTo(.5+b[5][0],.5+b[5][1]);f.lineTo(.5+b[6][0],.5+b[6][1]);f.lineTo(.5+b[3][0],.5+b[3][1]);f.lineTo(.5+b[4][0],.5+b[4][1]);f.closePath();f.fillStyle=this.pl9b[a][2];f.fill();f.stroke();f.beginPath();f.moveTo(.5+b[1][0],.5+b[1][1]);f.lineTo(.5+b[2][0],.5+b[2][1]);f.lineTo(.5+b[3][0],.5+b[3][1]);f.lineTo(.5+b[6][0],.5+b[6][1]);f.closePath();f.fillStyle=this.pl9b[a][3];f.fill();f.stroke();
return d};pl6a.prototype.pl29=function(a,b,d,f){this.pl8f.drawImage(this.pl9a,this.plac+(b-d)*this.plb1,this.plad+(b+d)*this.plb2/2-a*this.plb2)};pl6a.prototype.pl2a=function(a){if(this.pl9d.pl1(a.clientX,a.clientY))this.pl99=1,this.pl9d.pl2(a.clientX,a.clientY);else{var b;for(b=0;b<this.pl9e.length;b++)if(this.pl9e[b].pl1(a.clientX,a.clientY)){this.pl99=3;this.plb3=b;this.pl9e[b].pl2(a.clientX,a.clientY);return}1<this.pl97&&(this.pl99=2,this.pl30(a.clientX,a.clientY))}};
pl6a.prototype.pl2b=function(a){this.log("touchStart"+a.touches);if(this.pl9d.pl1(a.touches[0].pageX,a.touches[0].pageY))this.log("dragMode = 1"),this.pl99=1,this.pl9d.pl2(a.touches[0].pageX,a.touches[0].pageY);else{var b;for(b=0;b<this.pl9e.length;b++)if(this.pl9e[b].pl1(a.touches[0].pageX,a.touches[0].pageY)){this.pl99=3;this.plb3=b;this.pl9e[b].pl2(a.touches[0].pageX,a.touches[0].pageY);return}1<this.pl97&&(this.pl99=2,this.pl30(a.touches[0].pageX,a.touches[0].pageY))}};
pl6a.prototype.pl2c=function(a){1==this.pl99?this.pl9d.pl3(a.touches[0].pageX,a.touches[0].pageY):2==this.pl99?this.pl31(a.touches[0].pageX,a.touches[0].pageY):3==this.pl99&&this.pl9e[this.plb3].pl3(a.touches[0].pageX,a.touches[0].pageY)};pl6a.prototype.pl2d=function(a){1==this.pl99?this.pl9d.pl3(a.clientX,a.clientY):2==this.pl99?this.pl31(a.clientX,a.clientY):3==this.pl99&&this.pl9e[this.plb3].pl3(a.clientX,a.clientY)};
pl6a.prototype.pl2e=function(a){1==this.pl99?this.pl9d.pl4():2==this.pl99?this.pl32():3==this.pl99&&this.pl9e[this.plb3].pl4();this.pl99=0};pl6a.prototype.pl2f=function(a){1==this.pl99?this.pl9d.pl4():2==this.pl99?this.pl32():3==this.pl99&&this.pl9e[this.plb3].pl4();this.pl99=0};pl6a.prototype.pl30=function(a,b){this.plb4=a;this.plb5=b};
pl6a.prototype.pl31=function(a,b){var d=this.pl95+this.plb4-a,f=this.pl96+this.plb5-b;0>d&&(a+=d,d=0);0>f&&(b+=f,f=0);d>this.pl93-this.pl91&&(a=a+d-(this.pl93-this.pl91),d=this.pl93-this.pl91);f>this.pl94-this.pl92&&(b=b+f-(this.pl94-this.pl92),f=this.pl94-this.pl92);this.pla5=d;this.pla6=f;this.pl8f.clearRect(0,0,this.pl91,this.pl92);this.pla1?this.pl8f.drawImage(this.pla3,0,0,this.pl91,this.pl92,a-this.plb4,b-this.plb5,this.pl91,this.pl92):this.pl8f.drawImage(this.pla3,d,f,this.pl91,this.pl92,0,
0,this.pl91,this.pl92)};pl6a.prototype.pl32=function(){this.pl95=this.pla5;this.pl96=this.pla6;console.log("panStop() - "+this.pl95+", "+this.pl96);this.pla1&&(this.pl8f.clearRect(0,0,this.pl91,this.pl92),0==this.pl98?this.pl23():this.pl20(),this.pl8f.drawImage(this.pla3,0,0,this.pl91,this.pl92,0,0,this.pl91,this.pl92))};pl6a.prototype.log=function(a){this.pl9f.innerHTML+=a+"<br/>";this.pl9f.scrollTop=this.pl9f.scrollHeight};
pl6a.prototype.pl33=function(a,b){a.preventDefault();var d=plc7.pl6f;if(d.plb6)b();else{s=a.target.className;if("bn"!=s.substring(s.length-2)){var f=a.target.getElementsByTagName("div");if(0==f.length){setTimeout(b,10);return}f=f[0]}else f=a.target;f.style.background="#ffffff";f.style.color="#000000";d.plb6=f;setTimeout(b,10)}};pl6a.prototype.pl34=function(){this.plb6&&(this.plb6.style.background="#000000",this.plb6.style.color="#ffffff",this.plb6=null)};
pl6a.prototype.pl35=function(){var a=document.getElementById("ppro");a.style.left=(this.pl91-a.offsetWidth)/2+"px";a.style.top=this.pl92/2-32+"px";a.style.visibility="visible"};pl6a.prototype.pl36=function(a){document.getElementById("ppro").innerHTML=a};pl6a.prototype.pl37=function(){document.getElementById("ppro").style.visibility="hidden"};
pl6a.prototype.pl38=function(a){document.getElementById("seglbn").style.background=0==a?"#003000":"#808080";document.getElementById("seglbn").style.color=0==a?"#ffffff":"#000000";document.getElementById("segrbn").style.background=0==a?"#808080":"#003000";document.getElementById("segrbn").style.color=0==a?"#000000":"#ffffff";this.pl98=a;0==a?this.pl26():this.pl25()};pl6a.prototype.pl39=function(){plc7.pl80.pl39(parseInt(plc7.pl6f.plb6.id.substring(1)))};pl6a.prototype.pl3a=function(){plc7.pl80.pl3a(parseInt(plc7.pl6f.plb6.id.substring(1)))};
pl6a.prototype.pl3b=function(){for(var a=0,b="";;){el=document.getElementById("tl"+a);if(!el)break;b+=el.innerHTML+"<br/>";a++}a=40*++a;document.getElementById("pvl").style.height=a+"px";document.getElementById("pvlp").innerHTML=b};pl6a.prototype.pl3c=function(){this.pla2=!1;this.pl3d();document.getElementById("pctl").style.visibility="visible"};
pl6a.prototype.pl3d=function(){console.log("hideValues");for(i=0;i<this.pl9e.length;i++)document.getElementById("pv"+i+"bn0").style.visibility="hidden",document.getElementById("pv"+i+"bn1").style.visibility="hidden",document.getElementById("pvrl"+i).style.visibility="hidden",document.getElementById("pvkn"+i).style.visibility="hidden";document.getElementById("pvl").style.visibility="hidden"};
pl6a.prototype.pl3e=function(a){var b=this.pla7[this.pla8>this.pla7.length-1?this.pla7.length-1:this.pla8],d=Math.floor((b.length+1)/2-1),f=Math.floor((b[0].length+1)/2-1),e,g,h=[],k=0;if(1<this.pl97&&this.pla1){var n=this.plac-this.pl95;var m=this.plad-this.pl96}else n=this.plac,m=this.plad;if(14<this.plaa){var l=Math.floor((this.plaa-14)/2);a.font="bold 14px Helvetica"}else l=0,a.font="bold "+this.plaa+"px Helvetica";for(e=0;e<=d;e++){for(g=0;0>=b[e][g]&&g<=f;)g++;if(!(g>f)){var r=1;var q=g+1;if(0==
e)for(;0<b[e][q]&&q<=f;)q++,r++;else for(;0<b[e][q]&&0>=b[e-1][q]&&q<=f;)q++,r++;q=!1;1==r&&0<g&&0<b[e+1][g-1]&&(0==e||0>=b[e-1][g])&&(q=!0);if(q||1<r)q?h[k++]=new pl67(r,n+e*this.plab,m+l+g*this.plaa-this.plaa,"top","right"):h[k++]=new pl67(r,n+e*this.plab-1,m+l+g*this.plaa+Math.floor(r*this.plaa/2)-this.plaa/2,"top","right")}}for(g=0;g<=f;g++){for(e=0;0>=b[e][g]&&e<=d;)e++;if(!(e>d)){r=1;l=e+1;if(0==g)for(;0<b[l][g]&&l<=d;)l++,r++;else for(;0<b[l][g]&&0>=b[l][g-1]&&l<=d;)l++,r++;1<r&&(h[k++]=new pl67(r,
n+e*this.plab+Math.floor(r*this.plab/2),m+g*this.plaa,"bottom","center"))}}this.pl40(a,h)};
pl6a.prototype.pl3f=function(a){var b=this.pla7[this.pla8>this.pla7.length-1?this.pla7.length-1:this.pla8],d=Math.floor((b.length+1)/2-1),f=Math.floor((b[0].length+1)/2-1),e,g,h=[],k=0;if(1<this.pl97&&this.pla1){var n=this.plac-this.pl95;var m=this.plad-this.pl96}else n=this.plac,m=this.plad;if(14<this.plaa){var l=Math.floor((this.plaa-14)/2);a.font="bold 14px Helvetica"}else l=0,a.font="bold "+this.plaa+"px Helvetica";a.fillStyle="#000";a.textBaseline="top";a.textAlign="left";var r=Math.floor(this.plaa/
2);for(e=d;0<=e;e--){for(g=f;0<=g&&0>=b[e][g];)g--;if(!(0>g)){var q=1;var u=g-1;if(0==e)for(;0<=u&&0<b[e][u];)u--,q++;else for(;0<=u&&0<b[e][u]&&0>=b[e+1][u];)u--,q++;u=!1;1==q&&g<f&&0<b[e+1][g-1]&&0>=b[e+1][g]&&(0==e||0<b[e-1][g+1])&&(u=!0);if(u||1<q)u?h[k++]=new pl67(q,n+1+(e+1)*this.plab,m+(g+1)*this.plaa,"top","bottom"):h[k++]=new pl67(q,n+1+(e+1)*this.plab,m+l+(g+1)*this.plaa-q*this.plaa/2-r,"top","bottom");if(g==f)break}}for(g=f-1;0<=g;g--){for(e=d;0<=e&&0>=b[e][g];)e--;if(!(0>e)){q=1;for(f=
e-1;0<=f&&0<b[f][g]&&0>=b[f][g+1];)f--,q++;1<q&&(h[k++]=new pl67(q,n+1+(e+1)*this.plaa-q*this.plab/2-r/2,m+(g+1)*this.plab,"top","bottom"));if(e==d)break}}this.pl40(a,h)};
pl6a.prototype.pl40=function(a,b){var d=65535,f=0,e=0,g=["#c00000","#008000","#0000c0"];for(c=0;c<b.length;c++){yp=-1;for(idx=0;idx<b.length;idx++)b[idx].pl7c<d&&b[idx].pl7c>yp&&(yp=b[idx].pl7c,yFound=idx);d=yp;a.fillStyle=g[e];a.textBaseline=b[yFound].pl7d;a.textAlign=b[yFound].pl7e;a.fillText(b[yFound].pl7a,b[yFound].pl7b,b[yFound].pl7c);5<=++f&&(f=0,++e>=g.length&&(e=0))}};
pl6a.prototype.pl41=function(){var a=plc7.pl6f,b=document.getElementById("pcan"),d=window.innerWidth-120;b.width=d;b.height=window.innerHeight;a.pla3&&(a.pla3.width=b.width,a.pla3.height=b.height);a.pl91=d;a.pl92=window.innerHeight;a.pl90.style.width=d+"px";a.pl90.style.height=window.innerHeight+"px";a.pl93=a.pl91*a.pl97;a.pl94=a.pl92*a.pl97;0==a.pl98?(a.pl26(),a.pl21()):(a.pl25(),a.pl20());a.pl9d.pl0();document.getElementById("pvl");"visible"==pvl.style.visibility&&plc7.pl80.pl48()};
function pl6b(a){this.pl6f=a;this.plb7=5;this.plb8=32;this.plb9=!0;a=document.getElementById("pctl");/*var b=new XMLHttpRequest;b.open("GET","/plotzhtml5/pclt.php?o=7",!1);b.send(null);200===b.status&&(a.style.width="204px",a.style.height="40px",a.innerHTML=b.responseText)*/}
pl6b.prototype.plc=function(){var a=this.pl6f.touch?"touchstart":"click";document.getElementById("b0").addEventListener(a,function(a){plc7.pl6f.pl33(a,plc7.pl80.pl47);return!1},!1);document.getElementById("b1").addEventListener(a,function(a){plc7.pl6f.pl33(a,plc7.pl80.pl46);return!1},!1);document.getElementById("st0").addEventListener(a,function(a){plc7.pl6f.pl33(a,plc7.pl80.pl48);return!1},!1);document.getElementById("ptbmv").innerHTML="Snowman"};
pl6b.prototype.pl42=function(){this.pl45();this.plba=this.pl6f.pla0=!0;this.plbb=0;this.plbc=new pl6c(this.plb8,this.plb8,this.plb8);this.plbc.plc1=4;this.plbd=this.plbc.pl63(this.plb8,.75,!1);this.plbe=new pl6c(this.plbd,this.plbd,this.plbd);this.plbe.plc1=4;this.pl43()};
pl6b.prototype.pl43=function(){var a=plc7.pl80,b;0==a.plbb&&(b=a.plbc.pl54(a.plba,a.plb8,2*a.plb7-1,!0))&&(a.plbb=1,a.plba=!0);1==a.plbb&&(b=a.plbe.pl54(a.plba,a.plbd,2*a.plb7-1,!0));b?a.plba||1!=a.plbb?a.pl44():(a.pl6f.pl36("rendering"),setTimeout(plc7.pl80.pl44,50)):(a.plba&&(a.plba=!1,a.pl6f.pl35()),0==a.plbb?a.pl6f.pl36("Creating body "+Math.floor(400*a.plbc.plc5/a.plbc.plbf)+"%"):a.pl6f.pl36("Creating head "+Math.floor(400*a.plbe.plc5/a.plbe.plbf)+"%"),setTimeout(plc7.pl80.pl43,50))};
pl6b.prototype.pl44=function(){var a=plc7.pl80,b,d,f;var e=a.plbc.pl63(a.plb8,.15,!0);var g=new pl6c(1,e,e);g.plc1=2;g.pl50(0,0,e-1,e-1,0,0);g.pl51(0,2);var h=Math.floor((a.plb8-e)/2);a.plbc.pl64(g.pla7[0],h+Math.floor(.25*a.plb8),h);a.plbc.pl64(g.pla7[0],h,h);a.plbc.pl64(g.pla7[0],h-Math.floor(.25*a.plb8),h);h=Math.floor(a.plbe.plbf/2);for(b=e=0;b<a.plbe.plbf&&!(0<a.plbe.pla7[0][b][h]);)b++;for(f=b+1;0<a.plbe.pla7[0][b+e][h];)e++;var k=e-2;h=3*Math.floor((k+1)/2);g=new pl6c(h,k,k);g.plc1=7;for(b=
d=0;d<g.plbf-1;){var n=k-b-1;for(e=0;3>e;e++)g.pl50(b,b,n,n,0,d),g.pl51(d,0),d++;b++}for(d=2;d<g.plbf-3;)g.pl53(d,d+1),d+=3;var m=Math.floor(.6*a.plbd);b=Math.floor(.9*a.plbd);n=Math.floor(.5*a.plbd);var l=32<a.plb8?2:1,r=Math.floor(.25*n),q=Math.floor(.15*a.plbd);b%2!=a.plbd%2&&b++;k=new pl6c(n,b,b);e=Math.floor((b-m)/2);m=b-2*e;b==m&&(m--,e=1);k.plc1=2;for(d=0;d<l;d++)k.pl50(0,0,b-1,b-1,0,d),k.pl51(d,0);k.plc1=5;for(d=l;d<l+r;d++)k.pl50(e,e,e+m-1,e+m-1,0,d),k.pl51(l,0);for(k.plc1=2;d<k.plbf;)k.pl50(e,
e,e+m-1,e+m-1,0,d),k.pl51(d,d==k.plbf-1?2:0),d++;k.pl53(l-1,l);for(d=0;d<l-1;d++)k.pla7[d]=k.pla7[l-1];d=a.plbd+2*h;m=Math.floor(.1*a.plb8);q=new pl6c(a.plb8+a.plbd-m+n-q,d,d);e=Math.floor((d-a.plb8)/2);q.pl61(q.pla7,a.plbc.pla7,0,e,e);q.pl61(q.pla7,a.plbe.pla7,a.plb8-m,h,h);e=(d-b)/2;q.pl62(q.pla7,k.pla7,q.plbf-n,e,e);f=a.plb8+f-m;n=Math.floor((d-g.plc0)/2);e=a.plbd+h;for(d=0;d<g.plbf;d++)for(b=0;b<g.plc0;b++)for(h=0;h<g.plc0;h++)g.pla7[d][b][h]&&(q.pla7[f+h][e+d][n+b]=g.pla7[d][b][h]);plc7.pl6f.pl1f(q.pla7,
q.plbf,0);plc7.pl6f.pl37();plc7.pl6f.pla0=!1};pl6b.prototype.pl45=function(){document.getElementById("sz0").innerHTML=this.plb8};pl6b.prototype.pl46=function(){var a=plc7.pl80;67>a.plb8?(a.plb8++,a.pl42()):a.pl6f.pl34()};pl6b.prototype.pl47=function(){var a=plc7.pl80;12<a.plb8?(a.plb8--,a.pl42()):a.pl6f.pl34()};
pl6b.prototype.pl48=function(){document.getElementById("pctl").style.visibility="hidden";document.getElementById("pvl").style.visibility="visible";plc7.pl6f.pl9e[0].pl1c(64,plc7.pl6f.pl92-40,plc7.pl6f.pl91-64-64);plc7.pl6f.pl9e[0].pl1d(12,plc7.pl80.plb8,67);plc7.pl6f.pla2=!0};pl6b.prototype.pl49=function(a,b){0==a&&(this.plb8=b);this.pl42()};pl6b.prototype.pl39=function(a){0==a&&(this.pl47(),this.pl6f.pl9e[0].pl6(this.plb8))};pl6b.prototype.pl3a=function(a){0==a&&(this.pl46(),this.pl6f.pl9e[0].pl6(this.plb8))};
function pl6c(a,b,d){this.plbf=a;this.plc0=b;this.plc1=1;this.pl4a(a,b,d)}pl6c.prototype.pl4a=function(a,b,d){this.pla7=Array(a);var f;for(f=0;f<a;f++)this.pla7[f]=this.pl4c(b,d)};pl6c.prototype.pl4b=function(a,b){var d;this.plc2=Array(a);for(d=0;d<a;d++)this.plc2[d]=new Int8Array(b)};pl6c.prototype.pl4c=function(a,b){var d=Array(a),f,e;for(f=0;f<a;f++)for(d[f]=new Int8Array(b),e=0;e<b;e++)d[f][e]=-1;return d};
pl6c.prototype.pl4d=function(a,b,d,f,e){var g=Math.abs(d-a),h=Math.abs(f-b),k=h&1,n=4*(1-g)*h*h,m=4*(k+1)*g*g,l=n+m+k*g*g,r=this.plc1;a>d&&(a=d,d+=g);b>f&&(b=f);b+=Math.floor((h+1)/2);f=b-k;g*=8*g;k=8*h*h;do{e[d][b]=r;e[a][b]=r;e[a][f]=r;e[d][f]=r;var q=2*l;q>=n&&(a++,d--,l+=n+=k);q<=m&&(b++,f--,l+=m+=g)}while(a<=d);for(;b-f<h;)e[a-1][++b]=r,e[a-1][--f]=r};
pl6c.prototype.pl4e=function(a,b){switch(this.plc3){case 0:this.pla7[this.plc4][a][b]=this.plc1;break;case 1:this.pla7[b][this.plc4][a]=this.plc1;break;case 2:this.pla7[b][a][this.plc4]=this.plc1}};pl6c.prototype.pl4f=function(a,b){switch(this.plc3){case 0:return this.pla7[this.plc4][a][b];case 1:return this.pla7[b][this.plc4][a];case 2:return this.pla7[b][a][this.plc4]}return 0};
pl6c.prototype.pl50=function(a,b,d,f,e,g){var h=Math.abs(d-a),k=Math.abs(f-b),n=k&1,m=4*(1-h)*k*k,l=4*(n+1)*h*h,r=m+l+n*h*h;this.plc3=e;this.plc4=g;a>d&&(a=d,d+=h);b>f&&(b=f);b+=Math.floor((k+1)/2);f=b-n;h*=8*h;n=8*k*k;do this.pl4e(d,b),this.pl4e(a,b),this.pl4e(a,f),this.pl4e(d,f),e=2*r,e>=m&&(a++,d--,r+=m+=n),e<=l&&(b++,f--,r+=l+=h);while(a<=d);for(;b-f<k;)this.pl4e(a-1,++b),this.pl4e(a-1,--f)};
pl6c.prototype.pl51=function(a,b){var d,f,e,g=this.pla7[0].length;for(f=0;f<g;f++){for(d=0;d<g&&-1==this.pla7[a][d][f];)d++;if(!(d>=g)){for(;d<g&&1<=this.pla7[a][d][f];)d++;for(e=g-d;d<e;)this.pla7[a][d++][f]=b}}};pl6c.prototype.pl52=function(a,b){var d,f,e;for(d=a;d<=b;d++)for(f=a;f<=b;f++)for(e=a;e<=b;e++)this.pla7[d][f][e]=0};
pl6c.prototype.pl53=function(a,b){var d,f,e;var g=this.pla7[0].length;for(e=0;e<g;e++){for(d=0;d<g&&0>=this.pla7[a][d][e];)d++;if(!(d>=g||0<this.pla7[b][d][e])){for(;0<this.pla7[a][d][e];)d++;var h=g-d;for(f=g-1-d;d<h&&!(0<this.pla7[b][d][e]);)this.pla7[a][d][e]=this.plc1,this.pla7[a][f][e]=this.plc1,d++,f--}}};
pl6c.prototype.pl56=function(a,b,d){d=3;var f=b*d,e=this.pl4c(f,f),g=Math.floor((b+1)/4),h,k=Math.floor(d*d*d/8),n=Math.floor((b+1)/2),m=b-1;console.log("prec "+d+", quadLimit"+k);new pl6d;var l=Array(d);for(h=0;h<d;h++)l[h]=this.pl4c(f,f);this.pl4d(0,0,f-1,f-1,e);for(a&&(zpSoFar=0);zpSoFar<g;){var r=zpSoFar*d;for(a=0;a<d;a++){for(h=0;h<f;h++)for(g=0;g<f;g++)l[a][h][g]=-1;for(h=0;h<f&&!(0<e[h][r]);h++);this.pl4d(h,h,f-h-1,f-h-1,l[a]);this.pl5a(l[a],1)}for(f=0;f<n;f++)for(e=0;e<n;e++){for(a=h=0;a<
d;a++)h+=this.pl5c(l[a],f*d,e*d,d);h>k&&(this.pla7[zpSoFar][f][e]=1,this.pla7[zpSoFar][m-f][e]=1,this.pla7[zpSoFar][f][m-e]=1,this.pla7[zpSoFar][m-f][m-e]=1,this.pla7[e][zpSoFar][f]=1,this.pla7[e][zpSoFar][m-f]=1,this.pla7[e][f][zpSoFar]=1,this.pla7[e][m-f][zpSoFar]=1,this.pla7[e][f][m-zpSoFar]=1,this.pla7[e][m-f][m-zpSoFar]=1,this.pla7[e][m-zpSoFar][f]=1,this.pla7[e][m-zpSoFar][m-f]=1)}break}this.pla7[b-1]=this.pla7[0];d=Math.floor((b+1)/2);for(l=1;l<d;l++)this.pl57(l,l-1),this.pla7[b-1-l]=this.pla7[l];
return!0};
pl6c.prototype.pl54=function(a,b,d,f){var e=b*d,g=this.pl4c(e,e),h=this.pl4c(e,e),k,n=Math.floor((b+1)/4),m=Math.floor((d+1)/2-1),l=Math.floor(d*d/2),r=Math.floor((b+1)/2),q=b-1,u=new pl6d;this.pl4d(0,0,e-1,e-1,g);a&&(this.plc5=0);for(;this.plc5<n;this.plc5++){var v=this.plc5*d+m;for(a=0;a<e;a++)for(k=0;k<e;k++)h[a][k]=-1;for(a=0;a<e&&!(0<g[a][v]);a++);if(0!=this.plc5)for(this.pl4d(a,a,e-a-1,e-a-1,h),this.pl5a(h,1),a=0;a<r;a++)for(k=0;k<r;k++)this.pl5c(h,a*d,k*d,d)>l&&(this.pla7[this.plc5][a][k]=this.plc1,
this.pla7[this.plc5][q-a][k]=this.plc1,this.pla7[this.plc5][a][q-k]=this.plc1,this.pla7[this.plc5][q-a][q-k]=this.plc1,this.pla7[k][this.plc5][a]=this.plc1,this.pla7[k][this.plc5][q-a]=this.plc1,this.pla7[k][a][this.plc5]=this.plc1,this.pla7[k][q-a][this.plc5]=this.plc1,this.pla7[k][a][q-this.plc5]=this.plc1,this.pla7[k][q-a][q-this.plc5]=this.plc1,this.pla7[k][q-this.plc5][a]=this.plc1,this.pla7[k][q-this.plc5][q-a]=this.plc1);else for(a=Math.round(a/d),this.pl4d(a,a,q-a,q-a,this.pla7[0]),this.pl5a(this.pla7[0],
this.plc1),p=this.pla7[0],a=0;a<r;a++)for(k=0;k<r;k++)0<p[a][k]&&(this.pla7[k][this.plc5][a]=this.plc1,this.pla7[k][this.plc5][q-a]=this.plc1,this.pla7[k][a][this.plc5]=this.plc1,this.pla7[k][q-a][this.plc5]=this.plc1,this.pla7[k][a][q-this.plc5]=this.plc1,this.pla7[k][q-a][q-this.plc5]=this.plc1,this.pla7[k][q-this.plc5][a]=this.plc1,this.pla7[k][q-this.plc5][q-a]=this.plc1);if(f&&500<u.pl65())return!1}this.pla7[b-1]=this.pla7[0];d=Math.floor((b+1)/2);for(f=1;f<d;f++)this.pl57(f,f-1),this.pla7[b-
1-f]=this.pla7[f];return!0};pl6c.prototype.pl57=function(a,b){for(var d=this.pla7[a],f=this.pla7[b],e=Math.floor((d.length+1)/2)-1,g=Math.floor((d[0].length+1)/2)-1,h=d.length-1,k=d[0].length-1,n=0;n<e&&!(0<d[n][g]);)n++;for(var m=0;m<g&&!(0<d[e][m]);)m++;var l;m++;for(l=g;l>=m;l--){for(g=n;g<=e&&!(0<d[g++][l]););for(;g<=e&&!(0<d[g][l-1]&&-1!=f[g][l]);)g++;for(;g<=e;)d[g][l]=0,d[g][k-l]=0,d[h-g][l]=0,d[h-g][k-l]=0,g++}};
pl6c.prototype.pl58=function(a,b,d,f,e){var g=b*e,h=d*e,k=f*e,n=this.pl4c(g,k),m=this.pl4c(h,k),l=this.pl4c(g,h),r=Math.floor((f+1)/2),q=Math.floor((e+1)/2-1),u=Math.floor(e*e/2),v=Math.floor((b+1)/2),x=Math.floor((d+1)/2);--b;--d;var t=new pl6d;this.pl4d(0,0,g-1,k-1,n);this.pl4d(0,0,h-1,k-1,m);a&&(this.plc5=0);for(;this.plc5<r;this.plc5++){var w=this.plc5*e+q;for(a=0;a<g;a++)for(k=0;k<h;k++)l[a][k]=-1;for(a=0;a<g&&!(0<n[a][w]);a++);for(k=0;k<h&&!(0<m[k][w]);k++);this.pl4d(a,k,g-a-1,h-k-1,l);this.pl5a(l,
1);for(a=0;a<v;a++)for(k=0;k<x;k++)this.pl5c(l,a*e,k*e,e)>u&&(this.pla7[this.plc5][a][k]=1,this.pla7[this.plc5][b-a][k]=1,this.pla7[this.plc5][a][d-k]=1,this.pla7[this.plc5][b-a][d-k]=1);if(500<t.pl65())return!1}this.pla7[f-1]=this.pla7[0];for(e=1;e<r;e++)this.pl57(e,e-1),this.pla7[f-1-e]=this.pla7[e];return!0};
pl6c.prototype.pl59=function(a,b,d,f,e,g){var h=Math.floor((g+1)/2-1);f*=g;var k=Math.floor((e+1)/2),n=b*g,m=d*g,l=this.pl4c(f,f),r=this.pl4c(n,m),q=Math.floor((b+1)/2),u=Math.floor((d+1)/2);--b;--d;var v=Math.floor(g*g/2);this.pl4d(0,0,f-1,f-1,l);var x=new pl6d;a&&(this.plc5=0);for(;this.plc5<k;this.plc5++){if(500<x.pl65())return!1;var t=this.plc5*g+h;for(a=0;a<f&&!(0<l[a][t]);a++);var w;for(t=0;t<n;t++)for(w=0;w<m;w++)r[t][w]=-1;t=a;this.pl4d(t,t,n-1-t,n-1-t,r);t=f-a-1;this.pl4d(t,t,n-1-t,n-1-t,
r);this.pl5b(r,1);for(t=0;t<q;t++)for(a=0;a<u;a++)this.pl5c(r,t*g,a*g,g)>v&&(this.pla7[this.plc5][t][a]=1,this.pla7[this.plc5][b-t][a]=1,this.pla7[this.plc5][t][d-a]=1,this.pla7[this.plc5][b-t][d-a]=1);if(this.plc5)for(a=u-1;0<a;a--){for(t=0;t<q&&!(0<this.pla7[this.plc5][t][a]);)t++;if(t==q)break;for(t++;t<q&&0>=this.pla7[this.plc5][t][a-1];)t++;for(;t<q&&!(0>this.pla7[this.plc5][t+1][a])&&!(0>this.pla7[this.plc5][t][a+1]);)0<=this.pla7[this.plc5-1][t][a]&&(this.pla7[this.plc5][t][a]=0,this.pla7[this.plc5][b-
t][a]=0,this.pla7[this.plc5][t][d-a]=0,this.pla7[this.plc5][b-t][d-a]=0),t++}this.pla7[e-1-this.plc5]=this.pla7[this.plc5]}return this.plc5>=k};pl6c.prototype.pl5a=function(a,b){var d,f,e,g=a.length,h=a[0].length;for(f=0;f<h;f++){for(d=0;d<g&&-1==a[d][f];)d++;if(!(d>=g)){for(;d<g&&1<=a[d][f];)d++;for(e=g-d;d<e;)a[d++][f]=b}}};
pl6c.prototype.pl5b=function(a,b){var d=Math.floor((a.length+1)/2),f=Math.floor((a[0].length+1)/2),e,g,h,k=a.length-1,n=a[0].length-1;for(g=0;g<f;g++){for(e=0;e<d&&-1==a[e][g];)e++;if(!(e>=d-1)){for(;e<d&&1<=a[e][g];)e++;if(!(e>=d-1)){for(h=e+1;h<d&&-1==a[h][g];)h++;if(!(h>=d))for(;e<=d&&-1==a[e][g];)a[e][g]=b,a[e][n-g]=b,a[k-e][g]=b,a[k-e][n-g]=b,e++}}}for(e=0;e<d;e++){for(g=0;g<f&&-1==a[e][g];)g++;if(!(g>=f-1)){for(;g<f&&1<=a[e][g];)g++;if(!(g>=f-1)){for(h=g+1;h<f&&-1==a[e][h];)h++;if(!(h>=f))for(;g<
f&&-1==a[e][g];)a[e][g]=b,a[e][n-g]=b,a[k-e][g]=b,a[k-e][n-g]=b,g++}}}};pl6c.prototype.pl5c=function(a,b,d,f){var e=b+f;f=d+f;for(var g,h=0;b<e;b++)for(g=d;g<f;g++)0<a[b][g]&&h++;return h};pl6c.prototype.pl5d=function(a,b,d){var f,e;for(f=0;f<b;f++){var g="";for(e=0;e<d;e++)g+=0<a[f][e]?"*":"-";console.log(g)}};pl6c.prototype.pl5e=function(a,b,d,f,e){for(var g,h,k,n;b<a.length;b++){k=f;for(g=0;g<a.length;g++){n=e;for(h=0;h<a.length;h++)this.pla7[d][k][n++]=a[b][g][h];k++}d++}};
pl6c.prototype.pl5f=function(a,b){var d,f;for(d=0;d<a.length;d++)for(f=0;f<a[d].length;f++)b[d][f]=a[d][f]};pl6c.prototype.pl60=function(a,b){var d,f;for(d=0;d<a.length;d++)for(f=0;f<a[d].length;f++)b[d][f]=0<a[d][f]?0:b[d][f]};
pl6c.prototype.pl61=function(a,b,d,f,e){var g,h,k,n;var m=a.length;var l=b.length;var r=d+l<=m?d+l:m;m=a[0].length;l=b[0].length;var q=f+l<=m?f+l:m;m=a[0][0].length;l=b[0][0].length;m=e+l<=m?e+l:m;for(l=k=n=0;d<r;d++){for(g=f;g<q;g++){for(h=e;h<m;h++){var u=b[l][k][n];var v=a[d][g][h];-1==v&&(a[d][g][h]=u);n++}k++;n=0}l++;k=0}};
pl6c.prototype.pl62=function(a,b,d,f,e){var g,h,k,n;var m=a.length;var l=b.length;var r=d+l<=m?d+l:m;m=a[0].length;l=b[0].length;var q=f+l<=m?f+l:m;m=a[0][0].length;l=b[0][0].length;m=e+l<=m?e+l:m;for(l=k=n=0;d<r;d++){for(g=f;g<q;g++){for(h=e;h<m;h++){var u=b[l][k][n];a[d][g][h]=u;n++}k++;n=0}l++;k=0}};pl6c.prototype.pl63=function(a,b,d){b=Math.floor(a*b);return b%2!=a%2?d?b+1:b-1:b};
pl6c.prototype.pl64=function(a,b,d){var f,e,g;for(f=0;f<a.length;f++)for(e=0;e<a[0].length;e++)if(0<a[f][e])for(g=this.pla7[0].length-1;0<=g;){if(0<this.pla7[b+e][g][d+f]){this.pla7[b+e][g][d+f]=a[f][e];break}g--}};function pl6d(){this.plc6=(new Date).getTime()}pl6d.prototype.pl65=function(){return(new Date).getTime()-this.plc6};
