function pl66(){this.pl6e=0}
pl66.prototype.pl0=function(){document.getElementById("ptb").innerHTML='<div class="seglt" id="ptbiso"><div id="seglbn">3D</div></div><div class="segrt" id="ptbflt"><div id="segrbn">2D</div></div><div class="ptbt48" id="ptbz"><div class="ptbbn" id="ptbzv">zoom</div></div><div class="ptbt96" id="ptbm"><div class="ptbbn" id="ptbmv"></div></div>';this.pl6f=new pl68(0,0);this.pl70=new pl6a(this.pl6f);this.pl70.pl41();this.pl70.pl5();this.pl5();this.pl6f.pl31();this.pl4(!0);this.pl70.pl47()};
pl66.prototype.pl4=function(a){var b=a?"visible":"hidden";document.getElementById("pctl").style.visibility=b;document.getElementById("ptb").style.visibility=b;document.getElementById("pslrl").style.visibility=b;document.getElementById("pslbn0").style.visibility=b;document.getElementById("pslbn1").style.visibility=b;document.getElementById("pslkn").style.visibility=b;document.getElementById("pcon").style.visibility=b;document.getElementById("pbc").style.visibility=b;a||this.pl6f.pl8b&&this.pl6f.pl33()};
pl66.prototype.pl5=function(){document.getElementById("pev").addEventListener("click",this.plb,!1);document.getElementById("pev").addEventListener("mousedown",this.pld,!1);document.getElementById("pev").addEventListener("mousemove",this.ple,!1);document.getElementById("pev").addEventListener("mouseout",this.plf,!1);document.getElementById("pev").addEventListener("mouseup",this.plf,!1);document.getElementById("pev").addEventListener("touchstart",this.plc,!1);document.getElementById("pev").addEventListener("touchmove",
this.pl10,!1);document.getElementById("pev").addEventListener("touchend",this.pl11,!1);document.getElementById("pslbn0").addEventListener("click",function(a){plc5.pl6f.pl29(a,plc5.pl9)},!1);document.getElementById("pslbn1").addEventListener("click",function(a){plc5.pl6f.pl29(a,plc5.pla)},!1);document.getElementById("ptbz").addEventListener("click",function(a){plc5.pl6f.pl29(a,plc5.pl8)},!1);document.getElementById("ptbiso").addEventListener("click",function(a){plc5.pl12()},!1);document.getElementById("ptbflt").addEventListener("click",
function(a){plc5.pl13()},!1);document.getElementById("ptbm").addEventListener("click",function(a){a.preventDefault();plc5.pl7()},!1);document.getElementById("pvlhd").addEventListener("click",function(a){plc5.pl6f.pl32()},!1);var a;for(a=0;a<this.pl6f.pl87.length;a++)document.getElementById("pv"+a+"bn0").addEventListener("click",function(a){plc5.pl6f.pl29(a,plc5.pl6f.pl2f)},!1),document.getElementById("pv"+a+"bn1").addEventListener("click",function(a){plc5.pl6f.pl29(a,plc5.pl6f.pl30)},!1);window.onresize=
function(a){pto&&clearTimeout(pto);pto=setTimeout(plc5.pl6f.pl37,200)};"onorientationchange"in window&&(window.onorientationchange=function(a){pto=setTimeout(plc5.pl6f.pl37,10)})};pl66.prototype.pl6=function(){alert("objectUpdate")};pl66.prototype.pl7=function(){window.top.location.href="./plotz-menu.php"};pl66.prototype.pl8=function(){plc5.pl6f.pl8();document.getElementById("ptbzv").innerHTML=1==plc5.pl6f.pl80?"100%":100*plc5.pl6f.pl80+"%";plc5.pl6f.pl2a()};
pl66.prototype.pl9=function(a){plc5.pl6f.pl89||(a=plc5.pl6f.pl91,a<plc5.pl6f.pl90.length?(a++,plc5.pl6f.pl15(null,a,-1)):plc5.pl6f.pl2a())};pl66.prototype.pla=function(a){plc5.pl6f.pl89||(a=plc5.pl6f.pl91,1==plc5.pl6f.pl81&&plc5.pl6f.pl91>=plc5.pl6f.pl90.length&&a--,a?(a--,plc5.pl6f.pl15(null,a,-1)):plc5.pl6f.pl2a())};pl66.prototype.plb=function(a){};pl66.prototype.plc=function(a){a.preventDefault();plc5.pl6f.pl21(a)};pl66.prototype.pld=function(a){plc5.pl6f.pl20(a)};pl66.prototype.ple=function(a){plc5.pl6f.pl23(a)};
pl66.prototype.plf=function(a){plc5.pl6f.pl25(a)};pl66.prototype.pl10=function(a){plc5.pl6f.pl22(a)};pl66.prototype.pl11=function(a){plc5.pl6f.pl24(a)};pl66.prototype.pl12=function(){plc5.pl14(0)};pl66.prototype.pl13=function(){plc5.pl14(1)};pl66.prototype.pl14=function(a){this.pl6f.pl2e(a);this.pl6f.pl15(null,this.pl6f.pl91,-1)};var plc5;function plc6(){plc5=new pl66;plc5.pl0()}window.onload=setTimeout(plc6,100);
function pl67(a,b,d,e,f){this.pl71=a;this.pl72=b;this.pl73=d;this.pl74=e;this.pl75=f}
function pl68(a,b){var d=document.getElementById("pcan");a?(d.width=a,d.height=b):(a=d.width=window.innerWidth-120,b=d.height=window.innerHeight-0);this.pl76=d.offsetLeft;this.pl77=d.offsetTop;this.pl78=d.getContext("2d");this.pl79=document.getElementById("pev");this.pl79.style.width=a+"px";this.pl79.style.height=b+"px";this.pl7a=a;this.pl7b=b;this.pl7c=a;this.pl7d=b;this.pl7f=this.pl7e=0;this.pl80=1;this.pl82=this.pl81=0;this.pl83=[];this.pl84=[];this.pl85=[];this.pl84[0]=["#000000","#ffff00","#b1b100",
"#5b5b00"];this.pl84[1]=["#000000","#c0c0c0","#808080","#5f5f5f"];this.pl84[2]=["#000000","#303060","#202040","#101020"];this.pl84[3]=["#000000","#E0E0E0","#A0A0A0","#808080"];this.pl84[4]=["#808080","#ffffff","#E0E0E0","#C0C0C0"];this.pl84[5]=["#000000","#A00000","#700000","#400000"];this.pl84[6]=["#808080","rgba(255, 255, 255, 0.09)","rgba(224, 224, 224, 0.09)","rgba(192, 192, 192, 0.09)"];this.pl84[7]=["#333333","#FF8C00","#B16100","#5B3200"];this.pl85[0]=["#000000","#b1b100"];this.pl85[1]=["#000000",
"#808080"];this.pl85[2]=["#000000","#202040"];this.pl85[3]=["#000000","#A0A0A0"];this.pl85[4]=["#000000","#E0E0E0"];this.pl85[5]=["#000000","#700000"];this.pl85[6]=["#000000","#80c0ff"];this.pl85[7]=["#000000","#B16100"];this.pl86=new pl6b(32,32,this);this.pl87=Array(4);for(d=0;4>d;d++)this.pl87[d]=new pl69(d);this.pl88=document.getElementById("pcon");this.pl88.style.display="none";this.pl89=!1;this.pl8a=!0;this.pl8b=!1}
pl68.prototype.pl8=function(){var a=this.pl80;this.pl80=4>this.pl80?2*this.pl80:1;this.log("zoom="+this.pl80);if(1<this.pl80){this.pl8a?(this.pl8c=document.createElement("canvas"),this.pl8c.width=this.pl7a,this.pl8c.height=this.pl7b,this.pl7c=this.pl7a*this.pl80,this.pl7d=this.pl7b*this.pl80):(this.pl8c=document.createElement("canvas"),this.pl7c=this.pl8c.width=this.pl7a*this.pl80,this.pl7d=this.pl8c.height=this.pl7b*this.pl80);this.pl8d=this.pl8c.getContext("2d");var b=(this.pl7e+this.pl7a/2)/a;
a=(this.pl7f+this.pl7b/2)/a;this.pl8e=this.pl7e=b*this.pl80-this.pl7a/2;this.pl8f=this.pl7f=a*this.pl80-this.pl7b/2;console.log("zoomOffX="+this.pl7e+", this.pl7f="+this.pl7f+", cx="+b+", cy="+a)}else this.pl8d=this.pl8c=null,this.pl7c=this.pl7a,this.pl7d=this.pl7b,this.pl7f=this.pl8f=this.pl7e=this.pl8e=0;0==this.pl81?(this.pl1c(),this.pl17()):(this.pl1b(),this.pl16())};
pl68.prototype.pl15=function(a,b,d){a&&(this.pl90=a,this.pl2e(0));this.pl91=b;0==this.pl81?this.pl17():this.pl16();this.pl86.plae!=this.pl90.length&&(this.pl86.plae=this.pl90.length);this.pl86.pl3b(this.pl91+1);this.pl2a()};
pl68.prototype.pl16=function(){var a,b,d=1==this.pl90.length;var e=this.pl91>this.pl90.length-1?this.pl90.length-1:this.pl91;new pl6c;if(1<this.pl80){var f=this.pl8d;if(this.pl8a){var g=this.pl95-this.pl7e;var k=this.pl96-this.pl7f;f.clearRect(0,0,this.pl7a,this.pl7b)}else f.clearRect(0,0,this.pl7c,this.pl7d)}else f=this.pl78,g=this.pl95,k=this.pl96;this.pl78.clearRect(0,0,this.pl7a,this.pl7b);var h=this.pl90[0].length;var n=this.pl90[0][0].length;for(a=0;a<h;a++)for(b=0;b<n;b++)f.drawImage(this.pl97,
g+a*this.pl94,k+b*this.pl93);if(0<e){var m=this.pl90[e-1];for(a=0;a<h;a++)for(b=0;b<n;b++)0<m[a][b]&&f.drawImage(this.pl98,g+a*this.pl94,k+b*this.pl93)}m=this.pl90[e];for(a=0;a<h;a++)for(b=0;b<n;b++)e=m[a][b],0>=e||(f.drawImage(this.pl99[e],g+a*this.pl94,k+b*this.pl93),d&&this.pl92++);f.beginPath();f.lineWidth=1;f.strokeStyle="#a00000";a=1+g+Math.floor(h/2)*this.pl94-1;f.moveTo(a+.5,k);f.lineTo(a+.5,1+k+n*this.pl93);h%2&&(a+=this.pl94,f.moveTo(a+.5,k),f.lineTo(a+.5,1+k+n*this.pl93));f.stroke();f.beginPath();
f.lineWidth=1;f.strokeStyle="#008000";b=1+k+Math.floor(n/2)*this.pl93-1;f.moveTo(g,b+.5);f.lineTo(1+g+h*this.pl94,b+.5);n%2&&(b+=this.pl93,f.moveTo(g,b+.5),f.lineTo(1+g+h*this.pl94,b+.5));f.stroke();plc5.pl70.plb4&&this.pl34(f);plc5.pl70.innerEdgeSizes&&this.pl35(f);1<this.pl80&&this.pl8a&&this.pl78.drawImage(this.pl8c,0,0,this.pl7a,this.pl7b,0,0,this.pl7a,this.pl7b)};
pl68.prototype.pl17=function(){1<this.pl80?(this.pl78.clearRect(0,0,this.pl7a,this.pl7b),this.pl8a?(this.pl19(),this.pl78.drawImage(this.pl8c,0,0,this.pl7a,this.pl7b,0,0,this.pl7a,this.pl7b)):(this.pl1a(),this.pl78.drawImage(this.pl8c,this.pl7e,this.pl7f,this.pl7a,this.pl7b,0,0,this.pl7a,this.pl7b))):this.pl18()};
pl68.prototype.pl18=function(){var a,b,d=this.pl91>=this.pl90.length-1,e=this.pl91>this.pl90.length-1?this.pl90.length-1:this.pl91,f;d&&(this.pl92=0);this.pl78.clearRect(0,0,this.pl7a,this.pl7b);for(f=0;f<=e;f++){var g=this.pl91<=this.pl90.length-1&&f==this.pl91;var k=this.pl90[f];for(a=0;a<k.length;a++)for(b=0;b<k[a].length;b++){var h=k[a][b];0<h&&(d&&this.pl92++,g&&(h=0),this.pl78.drawImage(this.pl83[h],this.pl95+(a-b)*this.pl9a,this.pl96+(a+b)*this.pl9b/2-f*this.pl9b))}}document.getElementById("pbc").innerHTML=
this.pl92};pl68.prototype.pl19=function(){var a,b,d=this.pl91>=this.pl90.length-1,e=this.pl91>this.pl90.length-1?this.pl90.length-1:this.pl91,f,g=0+this.pl95-this.pl8e,k=0+this.pl96-this.pl8f;this.pl8d.clearRect(0,0,this.pl7a,this.pl7b);for(f=0;f<=e;f++){var h=this.pl91<=this.pl90.length-1&&f==this.pl91;var n=this.pl90[f];for(a=0;a<n.length;a++)for(b=0;b<n[a].length;b++){var m=n[a][b];0<m&&(d&&this.pl92++,h&&(m=0),this.pl8d.drawImage(this.pl83[m],g+(a-b)*this.pl9a,k+(a+b)*this.pl9b/2-f*this.pl9b))}}};
pl68.prototype.pl1a=function(){var a,b,d=this.pl91>=this.pl90.length-1,e=this.pl91>this.pl90.length-1?this.pl90.length-1:this.pl91,f;this.pl8d.clearRect(0,0,this.pl7c,this.pl7d);for(f=0;f<=e;f++){var g=this.pl91<=this.pl90.length-1&&f==this.pl91;var k=this.pl90[f];for(a=0;a<k.length;a++)for(b=0;b<k[a].length;b++){var h=k[a][b];0<h&&(d&&this.pl92++,g&&(h=0),this.pl8d.drawImage(this.pl83[h],this.pl95+(a-b)*this.pl9a,this.pl96+(a+b)*this.pl9b/2-f*this.pl9b))}}};
pl68.prototype.pl1b=function(){var a=this.pl90[0].length,b=this.pl90[0][0].length;this.pl7a/a<this.pl7b/b?this.pl93=this.pl94=Math.floor((this.pl7a-40)/a)*this.pl80:this.pl94=this.pl93=Math.floor((this.pl7b-40)/b)*this.pl80;this.pl95=Math.floor((this.pl7a*this.pl80-a*this.pl94)/2);this.pl96=Math.floor((this.pl7b*this.pl80-b*this.pl93)/2);this.pl97=this.pl1d("#e0e0e0","#ffffff");this.pl98=this.pl1d("#a0a0a0","#e8e8e8");this.pl99=[];for(a=0;a<this.pl85.length;a++)this.pl99[a]=this.pl1d(this.pl85[a][0],
this.pl85[a][1])};
pl68.prototype.pl1c=function(){var a,b,d,e=-1E4,f=-1E4,g=1E4,k=1E4;var h=this.pl90.length;var n=this.pl90[0].length;var m=this.pl90[0][0].length;for(a=0;a<h;a++)for(b=0;b<n;b++)for(d=0;d<m;d++)if(0<this.pl90[a][b][d]){var l=64*(b-d)/2;l<g&&(g=l);l>e&&(e=l);l=36*(b+d)/2-36*a;l<k&&(k=l);l>f&&(f=l)}(e-g)/this.pl7a>(f-k)/this.pl7b?(this.pl94=Math.floor((this.pl7a-40)/((e-g)/64+1)*this.pl80),this.pl93=Math.round(72*this.pl94/64)):(this.pl93=Math.floor((this.pl7b-40)/((f-k)/72+1)*this.pl80),this.pl94=Math.round(64*
this.pl93/72));this.pl95=Math.floor((this.pl7c-(e+g)/64*this.pl94-this.pl94)/2);this.pl96=Math.floor((this.pl7d-(f+k)/72*this.pl93-this.pl93)/2);this.pl9a=this.pl94/2;this.pl9b=this.pl93/2;for(a=0;a<this.pl84.length;a++)this.pl83[a]=this.pl1e(a)};pl68.prototype.pl1d=function(a,b){var d=document.createElement("canvas");d.width=this.pl94+2;d.height=this.pl93+2;var e=d.getContext("2d");e.strokeStyle=a;e.fillStyle=b;e.lineWidth=1;e.beginPath();e.rect(.5,.5,this.pl94,this.pl93);e.fill();e.stroke();return d};
pl68.prototype.pl1e=function(a){var b=Array(7);b[0]=[.5*this.pl94,0];b[1]=[this.pl94,.25*this.pl93];b[2]=[this.pl94,.75*this.pl93];b[3]=[.5*this.pl94,this.pl93];b[4]=[0,.75*this.pl93];b[5]=[0,.25*this.pl93];b[6]=[.5*this.pl94,.5*this.pl93];var d=document.createElement("canvas");d.width=this.pl94+1;d.height=this.pl93+1;var e=d.getContext("2d");e.lineWidth=.75;e.strokeStyle=this.pl84[a][0];e.beginPath();e.moveTo(.5+b[0][0],.5+b[0][1]);e.lineTo(.5+b[1][0],.5+b[1][1]);e.lineTo(.5+b[6][0],.5+b[6][1]);
e.lineTo(.5+b[5][0],.5+b[5][1]);e.closePath();e.fillStyle=this.pl84[a][1];e.fill();e.stroke();e.beginPath();e.moveTo(.5+b[5][0],.5+b[5][1]);e.lineTo(.5+b[6][0],.5+b[6][1]);e.lineTo(.5+b[3][0],.5+b[3][1]);e.lineTo(.5+b[4][0],.5+b[4][1]);e.closePath();e.fillStyle=this.pl84[a][2];e.fill();e.stroke();e.beginPath();e.moveTo(.5+b[1][0],.5+b[1][1]);e.lineTo(.5+b[2][0],.5+b[2][1]);e.lineTo(.5+b[3][0],.5+b[3][1]);e.lineTo(.5+b[6][0],.5+b[6][1]);e.closePath();e.fillStyle=this.pl84[a][3];e.fill();e.stroke();
return d};pl68.prototype.pl1f=function(a,b,d,e){this.pl78.drawImage(this.pl83,this.pl95+(b-d)*this.pl9a,this.pl96+(b+d)*this.pl9b/2-a*this.pl9b)};pl68.prototype.pl20=function(a){if(this.pl86.pl3c(a.clientX,a.clientY))this.pl82=1,this.pl86.pl3d(a.clientX,a.clientY);else{var b;for(b=0;b<this.pl87.length;b++)if(this.pl87[b].pl3c(a.clientX,a.clientY)){this.pl82=3;this.pl9c=b;this.pl87[b].pl3d(a.clientX,a.clientY);return}1<this.pl80&&(this.pl82=2,this.pl26(a.clientX,a.clientY))}};
pl68.prototype.pl21=function(a){this.log("touchStart"+a.touches);if(this.pl86.pl3c(a.touches[0].pageX,a.touches[0].pageY))this.log("dragMode = 1"),this.pl82=1,this.pl86.pl3d(a.touches[0].pageX,a.touches[0].pageY);else{var b;for(b=0;b<this.pl87.length;b++)if(this.pl87[b].pl3c(a.touches[0].pageX,a.touches[0].pageY)){this.pl82=3;this.pl9c=b;this.pl87[b].pl3d(a.touches[0].pageX,a.touches[0].pageY);return}1<this.pl80&&(this.pl82=2,this.pl26(a.touches[0].pageX,a.touches[0].pageY))}};
pl68.prototype.pl22=function(a){1==this.pl82?this.pl86.pl3e(a.touches[0].pageX,a.touches[0].pageY):2==this.pl82?this.pl27(a.touches[0].pageX,a.touches[0].pageY):3==this.pl82&&this.pl87[this.pl9c].pl3e(a.touches[0].pageX,a.touches[0].pageY)};pl68.prototype.pl23=function(a){1==this.pl82?this.pl86.pl3e(a.clientX,a.clientY):2==this.pl82?this.pl27(a.clientX,a.clientY):3==this.pl82&&this.pl87[this.pl9c].pl3e(a.clientX,a.clientY)};
pl68.prototype.pl24=function(a){1==this.pl82?this.pl86.pl3f():2==this.pl82?this.pl28():3==this.pl82&&this.pl87[this.pl9c].pl3f();this.pl82=0};pl68.prototype.pl25=function(a){1==this.pl82?this.pl86.pl3f():2==this.pl82?this.pl28():3==this.pl82&&this.pl87[this.pl9c].pl3f();this.pl82=0};pl68.prototype.pl26=function(a,b){this.pl9d=a;this.pl9e=b};
pl68.prototype.pl27=function(a,b){var d=this.pl7e+this.pl9d-a,e=this.pl7f+this.pl9e-b;0>d&&(a+=d,d=0);0>e&&(b+=e,e=0);d>this.pl7c-this.pl7a&&(a=a+d-(this.pl7c-this.pl7a),d=this.pl7c-this.pl7a);e>this.pl7d-this.pl7b&&(b=b+e-(this.pl7d-this.pl7b),e=this.pl7d-this.pl7b);this.pl8e=d;this.pl8f=e;this.pl78.clearRect(0,0,this.pl7a,this.pl7b);this.pl8a?this.pl78.drawImage(this.pl8c,0,0,this.pl7a,this.pl7b,a-this.pl9d,b-this.pl9e,this.pl7a,this.pl7b):this.pl78.drawImage(this.pl8c,d,e,this.pl7a,this.pl7b,0,
0,this.pl7a,this.pl7b)};pl68.prototype.pl28=function(){this.pl7e=this.pl8e;this.pl7f=this.pl8f;console.log("panStop() - "+this.pl7e+", "+this.pl7f);this.pl8a&&(this.pl78.clearRect(0,0,this.pl7a,this.pl7b),0==this.pl81?this.pl19():this.pl16(),this.pl78.drawImage(this.pl8c,0,0,this.pl7a,this.pl7b,0,0,this.pl7a,this.pl7b))};pl68.prototype.log=function(a){this.pl88.innerHTML+=a+"<br/>";this.pl88.scrollTop=this.pl88.scrollHeight};
pl68.prototype.pl29=function(a,b){a.preventDefault();var d=plc5.pl6f;if(d.pl9f)b();else{s=a.target.className;if("bn"!=s.substring(s.length-2)){var e=a.target.getElementsByTagName("div");if(0==e.length){setTimeout(b,10);return}e=e[0]}else e=a.target;e.style.background="#ffffff";e.style.color="#000000";d.pl9f=e;setTimeout(b,10)}};pl68.prototype.pl2a=function(){this.pl9f&&(this.pl9f.style.background="#000000",this.pl9f.style.color="#ffffff",this.pl9f=null)};
pl68.prototype.pl2b=function(){var a=document.getElementById("ppro");a.style.left=(this.pl7a-a.offsetWidth)/2+"px";a.style.top=this.pl7b/2-32+"px";a.style.visibility="visible"};pl68.prototype.pl2c=function(a){document.getElementById("ppro").innerHTML=a};pl68.prototype.pl2d=function(){document.getElementById("ppro").style.visibility="hidden"};
pl68.prototype.pl2e=function(a){document.getElementById("seglbn").style.background=0==a?"#003000":"#808080";document.getElementById("seglbn").style.color=0==a?"#ffffff":"#000000";document.getElementById("segrbn").style.background=0==a?"#808080":"#003000";document.getElementById("segrbn").style.color=0==a?"#000000":"#ffffff";this.pl81=a;0==a?this.pl1c():this.pl1b()};pl68.prototype.pl2f=function(){plc5.pl70.pl2f(parseInt(plc5.pl6f.pl9f.id.substring(1)))};pl68.prototype.pl30=function(){plc5.pl70.pl30(parseInt(plc5.pl6f.pl9f.id.substring(1)))};
pl68.prototype.pl31=function(){for(var a=0,b="";;){el=document.getElementById("tl"+a);if(!el)break;b+=el.innerHTML+"<br/>";a++}a=40*++a;document.getElementById("pvl").style.height=a+"px";document.getElementById("pvlp").innerHTML=b};pl68.prototype.pl32=function(){this.pl8b=!1;this.pl33();document.getElementById("pctl").style.visibility="visible"};
pl68.prototype.pl33=function(){console.log("hideValues");for(i=0;i<this.pl87.length;i++)document.getElementById("pv"+i+"bn0").style.visibility="hidden",document.getElementById("pv"+i+"bn1").style.visibility="hidden",document.getElementById("pvrl"+i).style.visibility="hidden",document.getElementById("pvkn"+i).style.visibility="hidden";document.getElementById("pvl").style.visibility="hidden"};
pl68.prototype.pl34=function(a){var b=this.pl90[this.pl91>this.pl90.length-1?this.pl90.length-1:this.pl91],d=Math.floor((b.length+1)/2-1),e=Math.floor((b[0].length+1)/2-1),f,g,k=[],h=0;if(1<this.pl80&&this.pl8a){var n=this.pl95-this.pl7e;var m=this.pl96-this.pl7f}else n=this.pl95,m=this.pl96;if(14<this.pl93){var l=Math.floor((this.pl93-14)/2);a.font="bold 14px Helvetica"}else l=0,a.font="bold "+this.pl93+"px Helvetica";for(f=0;f<=d;f++){for(g=0;0>=b[f][g]&&g<=e;)g++;if(!(g>e)){var r=1;var q=g+1;if(0==
f)for(;0<b[f][q]&&q<=e;)q++,r++;else for(;0<b[f][q]&&0>=b[f-1][q]&&q<=e;)q++,r++;q=!1;1==r&&0<g&&0<b[f+1][g-1]&&(0==f||0>=b[f-1][g])&&(q=!0);if(q||1<r)q?k[h++]=new pl67(r,n+f*this.pl94,m+l+g*this.pl93-this.pl93,"top","right"):k[h++]=new pl67(r,n+f*this.pl94-1,m+l+g*this.pl93+Math.floor(r*this.pl93/2)-this.pl93/2,"top","right")}}for(g=0;g<=e;g++){for(f=0;0>=b[f][g]&&f<=d;)f++;if(!(f>d)){r=1;l=f+1;if(0==g)for(;0<b[l][g]&&l<=d;)l++,r++;else for(;0<b[l][g]&&0>=b[l][g-1]&&l<=d;)l++,r++;1<r&&(k[h++]=new pl67(r,
n+f*this.pl94+Math.floor(r*this.pl94/2),m+g*this.pl93,"bottom","center"))}}this.pl36(a,k)};
pl68.prototype.pl35=function(a){var b=this.pl90[this.pl91>this.pl90.length-1?this.pl90.length-1:this.pl91],d=Math.floor((b.length+1)/2-1),e=Math.floor((b[0].length+1)/2-1),f,g,k=[],h=0;if(1<this.pl80&&this.pl8a){var n=this.pl95-this.pl7e;var m=this.pl96-this.pl7f}else n=this.pl95,m=this.pl96;if(14<this.pl93){var l=Math.floor((this.pl93-14)/2);a.font="bold 14px Helvetica"}else l=0,a.font="bold "+this.pl93+"px Helvetica";a.fillStyle="#000";a.textBaseline="top";a.textAlign="left";var r=Math.floor(this.pl93/
2);for(f=d;0<=f;f--){for(g=e;0<=g&&0>=b[f][g];)g--;if(!(0>g)){var q=1;var u=g-1;if(0==f)for(;0<=u&&0<b[f][u];)u--,q++;else for(;0<=u&&0<b[f][u]&&0>=b[f+1][u];)u--,q++;u=!1;1==q&&g<e&&0<b[f+1][g-1]&&0>=b[f+1][g]&&(0==f||0<b[f-1][g+1])&&(u=!0);if(u||1<q)u?k[h++]=new pl67(q,n+1+(f+1)*this.pl94,m+(g+1)*this.pl93,"top","bottom"):k[h++]=new pl67(q,n+1+(f+1)*this.pl94,m+l+(g+1)*this.pl93-q*this.pl93/2-r,"top","bottom");if(g==e)break}}for(g=e-1;0<=g;g--){for(f=d;0<=f&&0>=b[f][g];)f--;if(!(0>f)){q=1;for(e=
f-1;0<=e&&0<b[e][g]&&0>=b[e][g+1];)e--,q++;1<q&&(k[h++]=new pl67(q,n+1+(f+1)*this.pl93-q*this.pl94/2-r/2,m+(g+1)*this.pl94,"top","bottom"));if(f==d)break}}this.pl36(a,k)};
pl68.prototype.pl36=function(a,b){var d=65535,e=0,f=0,g=["#c00000","#008000","#0000c0"];for(c=0;c<b.length;c++){yp=-1;for(idx=0;idx<b.length;idx++)b[idx].pl73<d&&b[idx].pl73>yp&&(yp=b[idx].pl73,yFound=idx);d=yp;a.fillStyle=g[f];a.textBaseline=b[yFound].pl74;a.textAlign=b[yFound].pl75;a.fillText(b[yFound].pl71,b[yFound].pl72,b[yFound].pl73);5<=++e&&(e=0,++f>=g.length&&(f=0))}};
pl68.prototype.pl37=function(){var a=plc5.pl6f,b=document.getElementById("pcan"),d=window.innerWidth-120;b.width=d;b.height=window.innerHeight;a.pl8c&&(a.pl8c.width=b.width,a.pl8c.height=b.height);a.pl7a=d;a.pl7b=window.innerHeight;a.pl79.style.width=d+"px";a.pl79.style.height=window.innerHeight+"px";a.pl7c=a.pl7a*a.pl80;a.pl7d=a.pl7b*a.pl80;0==a.pl81?(a.pl1c(),a.pl17()):(a.pl1b(),a.pl16());a.pl86.pl49();document.getElementById("pvl");"visible"==pvl.style.visibility&&plc5.pl70.pl47()};
function pl69(a){this.pla0=a;this.pla2=this.pla1=0;this.pla3=document.getElementById("pv"+a+"bn0");this.pla4=document.getElementById("pv"+a+"bn1");this.pla5=document.getElementById("pvrl"+a);this.pla6=document.getElementById("pvkn"+a);this.pla7=document.getElementById("pvin"+a);this.pla8=!1}
pl69.prototype.pl38=function(a,b,d){this.pla3.style.left=a+"px";this.pla3.style.top=b+"px";this.pla4.style.left=a+d-40+"px";this.pla4.style.top=b+"px";this.pla5.style.left=a+52+"px";this.pla5.style.top=b+16+"px";this.pla5.style.width=d-40-40-12-12+"px";this.pla9=a+40;this.plaa=d-40-40-32;this.plab=this.pla9+this.plaa;this.plac=a+40;this.plad=b+4;this.pla6.style.left=this.plac+"px";this.pla6.style.top=this.plad+"px";this.pla7.style.left=this.plac-16+"px";this.pla7.style.top=this.plad-44+"px"};
pl69.prototype.pl39=function(a,b,d){this.pla3.style.visibility="visible";this.pla4.style.visibility="visible";this.pla5.style.visibility="visible";this.pla6.style.visibility="visible";this.pla8=!0;this.pla1=a-1;this.plae=1+d-a;this.pl3b(b)};pl69.prototype.pl3a=function(a,b){this.plae=b-this.pla1;this.pl3b(a)};
pl69.prototype.pl3b=function(a){a>this.plae+this.minValu1?a=this.plae+this.pla1:a<this.pla1+1&&(a=this.pla1+1);a-=this.pla1;newX=this.pla9+Math.floor(a*this.plaa/this.plae)-1;this.pla6.style.left=newX+"px";this.pla7.style.left=newX-16+"px";this.plac=newX;this.plaf=a;this.pla6.innerHTML=this.plaf+this.pla1};pl69.prototype.pl3c=function(a,b){return!plc5.pl6f.pl89&&this.pla8&&a>=this.plac-4&&a<=this.plac+40&&b>=this.plad-4&&b<=this.plad+40};
pl69.prototype.pl3d=function(a,b){this.plb0=a;this.plb1=a-this.plac;this.pla7.style.visibility="visible";this.pl40()};pl69.prototype.pl3e=function(a,b){var d=this.plb0+a-this.plb0-this.plb1;d<this.pla9?d=this.pla9:d>this.plab-1&&(d=this.plab-1);this.pla6.style.left=d+"px";this.pla7.style.left=d-16+"px";this.plac=d;this.pl40()};pl69.prototype.pl3f=function(){this.pla7.style.visibility="hidden";this.pl3b(this.plaf+this.pla1);plc5.pl70.pl48(this.pla0,this.plaf+this.pla1)};
pl69.prototype.pl40=function(){this.plaf=1+Math.floor(this.plae*(this.plac-this.pla9)/this.plaa);this.pla7.innerHTML=this.pla6.innerHTML=this.plaf+this.pla1};function pl6a(a){this.pl6f=a;this.plb2=32;this.plb3=5;this.plb4=!0;a=document.getElementById("pctl");/*var b=new XMLHttpRequest;b.open("GET","./plotzhtml5/pclt.observatory.php",!1);b.send(null);200===b.status&&(a.style.width="204px",a.style.height="40px",a.innerHTML=b.responseText)*/}
pl6a.prototype.pl5=function(){var a=this.pl6f.touch?"touchstart":"click";document.getElementById("b0").addEventListener(a,function(a){plc5.pl6f.pl29(a,plc5.pl70.pl46);return!1},!1);document.getElementById("b1").addEventListener(a,function(a){plc5.pl6f.pl29(a,plc5.pl70.pl45);return!1},!1);document.getElementById("st0").addEventListener(a,function(a){plc5.pl6f.pl29(a,plc5.pl70.pl47);return!1},!1);document.getElementById("ptbmv").innerHTML="Observatory"};
pl6a.prototype.pl41=function(){this.pl6f.pl89=!0;this.pl44();this.plb5=new pl6d(this.plb2+2,this.plb2+2,this.plb2+2);this.plb6=new pl6d(this.plb2,this.plb2,this.plb2);this.plb7=!0;this.pl42()};pl6a.prototype.pl42=function(){var a=plc5.pl70;a.plb6.pl55(a.plb7,a.plb2,2*a.plb3-1)?a.plb7?a.pl43():(a.pl6f.pl2c("rendering"),setTimeout(plc5.pl70.pl43,50)):(a.plb7&&(a.plb7=!1,a.pl6f.pl2b()),a.pl6f.pl2c("Creating observatory "+Math.floor(400*a.plb6.plc4/a.plb6.plbe)+"%"),setTimeout(plc5.pl70.pl42,50))};
pl6a.prototype.pl43=function(){var a=plc5.pl70,b=Math.floor(a.plb2/2);a.plb5.pl5f(a.plb6.pl90,b,b+1,1,1);var d,e,f;b++;for(d=b-2;0<=d;d--)for(e=0;e<a.plb5.plbf;e++)for(f=0;f<a.plb5.plbf;f++)a.plb5.pl90[d][e][f]=a.plb5.pl90[b][e][f];var g=Math.round((a.plb2+1)/8);a.plb5.pl51(g,g,a.plb2+1-g,a.plb2+1-g,0,b-1);a.plb5.pl52(b-1,1);e=Array(a.plb5.plbe);for(d=0;d<a.plb5.plbe;d++)e[d]=Array(a.plb5.plbe);a.plb5.pl60(a.plb5.pl90[b-1],e);a.plb5.pl51(0,0,a.plb2+1,a.plb2+1,0,b-1);a.plb5.pl52(b-1,1);a.plb5.pl61(e,
a.plb5.pl90[b-1]);var k=Math.floor((a.plb2+2)/2);var h=0==a.plb2%2?k-1:k;d=Math.floor(a.plb2/12);h-=d;var n=k+d;var m=Math.floor(a.plb2/8);for(zp=a.plb2;zp>=b;zp--)for(e=h;e<=n;e++)for(f=k-m;f<a.plb2+2;f++)a.plb5.pl90[zp][e][f]=0;a.plb6=new pl6d(1,a.plb2+2,a.plb2+2);a.plb6.plc0=1;a.plb6.pl51(0,0,a.plb2+1,a.plb2+1,0,0);g=Math.round((n-h)/2);2*g<n-h+1&&g++;g++;for(d=h-g;d<h;d++)for(e=k-m;e<a.plb2+2;e++)for(f=a.plb2+2;f>=b;f--)0<a.plb6.pl90[0][e][f]&&(a.plb5.pl90[f][d][e]=a.plb6.pl90[0][e][f]);for(d=
n+1;d<=n+g;d++)for(e=k-m;e<a.plb2+2;e++)for(f=a.plb2+2;f>=b;f--)0<a.plb6.pl90[0][e][f]&&(a.plb5.pl90[f][d][e]=a.plb6.pl90[0][e][f]);g=Math.floor(a.plb2/8);a.plb5.pl90=a.plb5.pl90.slice(g,a.plb5.pl90.length);a.plb5.plbe=a.plb5.pl90.length;a.pl6f.pl15(a.plb5.pl90,a.plb5.plbe,0);a.pl6f.pl2d();a.pl6f.pl89=!1};pl6a.prototype.pl44=function(){document.getElementById("sz0").innerHTML=this.plb2};pl6a.prototype.pl45=function(){var a=plc5.pl70;128>a.plb2?(a.plb2++,a.pl41()):a.pl6f.pl2a()};
pl6a.prototype.pl46=function(){var a=plc5.pl70;16<a.plb2?(a.plb2--,a.pl41()):a.pl6f.pl2a()};pl6a.prototype.pl47=function(){document.getElementById("pctl").style.visibility="hidden";document.getElementById("pvl").style.visibility="visible";plc5.pl6f.pl87[0].pl38(64,plc5.pl6f.pl7b-40,plc5.pl6f.pl7a-64-64);plc5.pl6f.pl87[0].pl39(16,plc5.pl70.plb2,128);plc5.pl6f.pl8b=!0};pl6a.prototype.pl48=function(a,b){0==a&&(this.plb2=b);this.pl41()};pl6a.prototype.pl2f=function(a){0==a&&(this.pl46(),this.pl6f.pl87[0].pl3b(this.plb2))};
pl6a.prototype.pl30=function(a){0==a&&(this.pl45(),this.pl6f.pl87[0].pl3b(this.plb2))};function pl6b(a,b,d){this.plae=b;this.pl6f=d;this.pl49();this.plaf=a;this.pl40()}
pl6b.prototype.pl49=function(){var a=this.pl6f.pl7b-160;this.plb8=a-32;this.plac=this.pl6f.pl7a-32-16;this.plad=this.plb9=Math.floor((this.pl6f.pl7b-a)/2);this.plba=this.plb9+a-1-32;var b=document.getElementById("pslrl");b.style.left=this.plac+12+"px";b.style.top=this.plad+12+"px";b.style.height=a-28+"px";this.pla6=document.getElementById("pslkn");this.pla6.style.top=this.plad+"px";this.pla6.style.left=this.plac+"px";this.pla7=document.getElementById("pslin");this.pla7.style.top=this.plad-4+"px";
this.pla7.style.left=this.plac-70+"px";b=document.getElementById("pslbn0");b.style.left=this.plac-4+"px";b.style.top=this.plad-40+"px";b=document.getElementById("pslbn1");b.style.left=this.plac-4+"px";b.style.top=this.plad+a+"px";this.pl3b(this.plaf)};pl6b.prototype.pl3c=function(a,b){return!this.pl6f.pl89&&a>=this.plac&&a<=this.plac+32&&b>=this.plad&&b<=this.plad+32};pl6b.prototype.pl3d=function(a,b){this.plbb=b;this.plbc=b-this.plad;this.pla7.style.visibility="visible";this.pl40()};
pl6b.prototype.pl3e=function(a,b){var d=this.plbb+b-this.plbb-this.plbc;d<this.plb9?d=this.plb9:d>this.plba&&(d=this.plba);this.pla6.style.top=d+"px";this.pla7.style.top=d-4+"px";this.plad=d;this.pl40()};pl6b.prototype.pl3f=function(){this.pla7.style.visibility="hidden";this.pl6f.pl15(null,this.plaf-1,-1)};pl6b.prototype.pl40=function(){this.plaf=this.plae-Math.floor(this.plae*(this.plad-this.plb9)/this.plb8);this.pla7.innerHTML=this.pla6.innerHTML=this.plaf};
pl6b.prototype.pl3b=function(a){a>this.plae?a=this.plae:1>a&&(a=1);newY=this.plb9+this.plb8-1-Math.floor((a-1)*(this.plb8-1)/(this.plae-1));this.pla6.style.top=newY+"px";this.pla7.style.top=newY-4+"px";this.plad=newY;this.plaf=a;this.pla7.innerHTML=this.pla6.innerHTML=this.plaf};function pl6c(){this.plbd=(new Date).getTime()}pl6c.prototype.pl4a=function(){return(new Date).getTime()-this.plbd};function pl6d(a,b,d){this.plbe=a;this.plbf=b;this.plc0=1;this.pl4b(a,b,d)}
pl6d.prototype.pl4b=function(a,b,d){this.pl90=Array(a);var e;for(e=0;e<a;e++)this.pl90[e]=this.pl4d(b,d)};pl6d.prototype.pl4c=function(a,b){var d;this.plc1=Array(a);for(d=0;d<a;d++)this.plc1[d]=new Int8Array(b)};pl6d.prototype.pl4d=function(a,b){var d=Array(a),e,f;for(e=0;e<a;e++)for(d[e]=new Int8Array(b),f=0;f<b;f++)d[e][f]=-1;return d};
pl6d.prototype.pl4e=function(a,b,d,e,f){var g=Math.abs(d-a),k=Math.abs(e-b),h=k&1,n=4*(1-g)*k*k,m=4*(h+1)*g*g,l=n+m+h*g*g,r=this.plc0;a>d&&(a=d,d+=g);b>e&&(b=e);b+=Math.floor((k+1)/2);e=b-h;g*=8*g;h=8*k*k;do{f[d][b]=r;f[a][b]=r;f[a][e]=r;f[d][e]=r;var q=2*l;q>=n&&(a++,d--,l+=n+=h);q<=m&&(b++,e--,l+=m+=g)}while(a<=d);for(;b-e<k;)f[a-1][++b]=r,f[a-1][--e]=r};
pl6d.prototype.pl4f=function(a,b){switch(this.plc2){case 0:this.pl90[this.plc3][a][b]=this.plc0;break;case 1:this.pl90[b][this.plc3][a]=this.plc0;break;case 2:this.pl90[b][a][this.plc3]=this.plc0}};pl6d.prototype.pl50=function(a,b){switch(this.plc2){case 0:return this.pl90[this.plc3][a][b];case 1:return this.pl90[b][this.plc3][a];case 2:return this.pl90[b][a][this.plc3]}return 0};
pl6d.prototype.pl51=function(a,b,d,e,f,g){var k=Math.abs(d-a),h=Math.abs(e-b),n=h&1,m=4*(1-k)*h*h,l=4*(n+1)*k*k,r=m+l+n*k*k;this.plc2=f;this.plc3=g;a>d&&(a=d,d+=k);b>e&&(b=e);b+=Math.floor((h+1)/2);e=b-n;k*=8*k;n=8*h*h;do this.pl4f(d,b),this.pl4f(a,b),this.pl4f(a,e),this.pl4f(d,e),f=2*r,f>=m&&(a++,d--,r+=m+=n),f<=l&&(b++,e--,r+=l+=k);while(a<=d);for(;b-e<h;)this.pl4f(a-1,++b),this.pl4f(a-1,--e)};
pl6d.prototype.pl52=function(a,b){var d,e,f,g=this.pl90[0].length;for(e=0;e<g;e++){for(d=0;d<g&&-1==this.pl90[a][d][e];)d++;if(!(d>=g)){for(;d<g&&1<=this.pl90[a][d][e];)d++;for(f=g-d;d<f;)this.pl90[a][d++][e]=b}}};pl6d.prototype.pl53=function(a,b){var d,e,f;for(d=a;d<=b;d++)for(e=a;e<=b;e++)for(f=a;f<=b;f++)this.pl90[d][e][f]=0};
pl6d.prototype.pl54=function(a,b){var d,e,f;var g=this.pl90[0].length;for(f=0;f<g;f++){for(d=0;d<g&&0>=this.pl90[a][d][f];)d++;if(!(d>=g||0<this.pl90[b][d][f])){for(;0<this.pl90[a][d][f];)d++;var k=g-d;for(e=g-1-d;d<k&&!(0<this.pl90[b][d][f]);)this.pl90[a][d][f]=this.plc0,this.pl90[a][e][f]=this.plc0,d++,e--}}};
pl6d.prototype.pl57=function(a,b,d){d=3;var e=b*d,f=this.pl4d(e,e),g=Math.floor((b+1)/4),k,h=Math.floor(d*d*d/8),n=Math.floor((b+1)/2),m=b-1;console.log("prec "+d+", quadLimit"+h);new pl6c;var l=Array(d);for(k=0;k<d;k++)l[k]=this.pl4d(e,e);this.pl4e(0,0,e-1,e-1,f);for(a&&(zpSoFar=0);zpSoFar<g;){var r=zpSoFar*d;for(a=0;a<d;a++){for(k=0;k<e;k++)for(g=0;g<e;g++)l[a][k][g]=-1;for(k=0;k<e&&!(0<f[k][r]);k++);this.pl4e(k,k,e-k-1,e-k-1,l[a]);this.pl5b(l[a],1)}for(e=0;e<n;e++)for(f=0;f<n;f++){for(a=k=0;a<
d;a++)k+=this.pl5d(l[a],e*d,f*d,d);k>h&&(this.pl90[zpSoFar][e][f]=1,this.pl90[zpSoFar][m-e][f]=1,this.pl90[zpSoFar][e][m-f]=1,this.pl90[zpSoFar][m-e][m-f]=1,this.pl90[f][zpSoFar][e]=1,this.pl90[f][zpSoFar][m-e]=1,this.pl90[f][e][zpSoFar]=1,this.pl90[f][m-e][zpSoFar]=1,this.pl90[f][e][m-zpSoFar]=1,this.pl90[f][m-e][m-zpSoFar]=1,this.pl90[f][m-zpSoFar][e]=1,this.pl90[f][m-zpSoFar][m-e]=1)}break}this.pl90[b-1]=this.pl90[0];d=Math.floor((b+1)/2);for(l=1;l<d;l++)this.pl58(l,l-1),this.pl90[b-1-l]=this.pl90[l];
return!0};
pl6d.prototype.pl55=function(a,b,d,e){var f=b*d,g=this.pl4d(f,f),k=this.pl4d(f,f),h,n=Math.floor((b+1)/4),m=Math.floor((d+1)/2-1),l=Math.floor(d*d/2),r=Math.floor((b+1)/2),q=b-1,u=new pl6c;this.pl4e(0,0,f-1,f-1,g);a&&(this.plc4=0);for(;this.plc4<n;this.plc4++){var v=this.plc4*d+m;for(a=0;a<f;a++)for(h=0;h<f;h++)k[a][h]=-1;for(a=0;a<f&&!(0<g[a][v]);a++);if(0!=this.plc4)for(this.pl4e(a,a,f-a-1,f-a-1,k),this.pl5b(k,1),a=0;a<r;a++)for(h=0;h<r;h++)this.pl5d(k,a*d,h*d,d)>l&&(this.pl90[this.plc4][a][h]=this.plc0,
this.pl90[this.plc4][q-a][h]=this.plc0,this.pl90[this.plc4][a][q-h]=this.plc0,this.pl90[this.plc4][q-a][q-h]=this.plc0,this.pl90[h][this.plc4][a]=this.plc0,this.pl90[h][this.plc4][q-a]=this.plc0,this.pl90[h][a][this.plc4]=this.plc0,this.pl90[h][q-a][this.plc4]=this.plc0,this.pl90[h][a][q-this.plc4]=this.plc0,this.pl90[h][q-a][q-this.plc4]=this.plc0,this.pl90[h][q-this.plc4][a]=this.plc0,this.pl90[h][q-this.plc4][q-a]=this.plc0);else for(a=Math.round(a/d),this.pl4e(a,a,q-a,q-a,this.pl90[0]),this.pl5b(this.pl90[0],
this.plc0),p=this.pl90[0],a=0;a<r;a++)for(h=0;h<r;h++)0<p[a][h]&&(this.pl90[h][this.plc4][a]=this.plc0,this.pl90[h][this.plc4][q-a]=this.plc0,this.pl90[h][a][this.plc4]=this.plc0,this.pl90[h][q-a][this.plc4]=this.plc0,this.pl90[h][a][q-this.plc4]=this.plc0,this.pl90[h][q-a][q-this.plc4]=this.plc0,this.pl90[h][q-this.plc4][a]=this.plc0,this.pl90[h][q-this.plc4][q-a]=this.plc0);if(e&&500<u.pl4a())return!1}this.pl90[b-1]=this.pl90[0];d=Math.floor((b+1)/2);for(e=1;e<d;e++)this.pl58(e,e-1),this.pl90[b-
1-e]=this.pl90[e];return!0};pl6d.prototype.pl58=function(a,b){for(var d=this.pl90[a],e=this.pl90[b],f=Math.floor((d.length+1)/2)-1,g=Math.floor((d[0].length+1)/2)-1,k=d.length-1,h=d[0].length-1,n=0;n<f&&!(0<d[n][g]);)n++;for(var m=0;m<g&&!(0<d[f][m]);)m++;var l;m++;for(l=g;l>=m;l--){for(g=n;g<=f&&!(0<d[g++][l]););for(;g<=f&&!(0<d[g][l-1]&&-1!=e[g][l]);)g++;for(;g<=f;)d[g][l]=0,d[g][h-l]=0,d[k-g][l]=0,d[k-g][h-l]=0,g++}};
pl6d.prototype.pl59=function(a,b,d,e,f){var g=b*f,k=d*f,h=e*f,n=this.pl4d(g,h),m=this.pl4d(k,h),l=this.pl4d(g,k),r=Math.floor((e+1)/2),q=Math.floor((f+1)/2-1),u=Math.floor(f*f/2),v=Math.floor((b+1)/2),x=Math.floor((d+1)/2);--b;--d;var t=new pl6c;this.pl4e(0,0,g-1,h-1,n);this.pl4e(0,0,k-1,h-1,m);a&&(this.plc4=0);for(;this.plc4<r;this.plc4++){var w=this.plc4*f+q;for(a=0;a<g;a++)for(h=0;h<k;h++)l[a][h]=-1;for(a=0;a<g&&!(0<n[a][w]);a++);for(h=0;h<k&&!(0<m[h][w]);h++);this.pl4e(a,h,g-a-1,k-h-1,l);this.pl5b(l,
1);for(a=0;a<v;a++)for(h=0;h<x;h++)this.pl5d(l,a*f,h*f,f)>u&&(this.pl90[this.plc4][a][h]=1,this.pl90[this.plc4][b-a][h]=1,this.pl90[this.plc4][a][d-h]=1,this.pl90[this.plc4][b-a][d-h]=1);if(500<t.pl4a())return!1}this.pl90[e-1]=this.pl90[0];for(f=1;f<r;f++)this.pl58(f,f-1),this.pl90[e-1-f]=this.pl90[f];return!0};
pl6d.prototype.pl5a=function(a,b,d,e,f,g){var k=Math.floor((g+1)/2-1);e*=g;var h=Math.floor((f+1)/2),n=b*g,m=d*g,l=this.pl4d(e,e),r=this.pl4d(n,m),q=Math.floor((b+1)/2),u=Math.floor((d+1)/2);--b;--d;var v=Math.floor(g*g/2);this.pl4e(0,0,e-1,e-1,l);var x=new pl6c;a&&(this.plc4=0);for(;this.plc4<h;this.plc4++){if(500<x.pl4a())return!1;var t=this.plc4*g+k;for(a=0;a<e&&!(0<l[a][t]);a++);var w;for(t=0;t<n;t++)for(w=0;w<m;w++)r[t][w]=-1;t=a;this.pl4e(t,t,n-1-t,n-1-t,r);t=e-a-1;this.pl4e(t,t,n-1-t,n-1-t,
r);this.pl5c(r,1);for(t=0;t<q;t++)for(a=0;a<u;a++)this.pl5d(r,t*g,a*g,g)>v&&(this.pl90[this.plc4][t][a]=1,this.pl90[this.plc4][b-t][a]=1,this.pl90[this.plc4][t][d-a]=1,this.pl90[this.plc4][b-t][d-a]=1);if(this.plc4)for(a=u-1;0<a;a--){for(t=0;t<q&&!(0<this.pl90[this.plc4][t][a]);)t++;if(t==q)break;for(t++;t<q&&0>=this.pl90[this.plc4][t][a-1];)t++;for(;t<q&&!(0>this.pl90[this.plc4][t+1][a])&&!(0>this.pl90[this.plc4][t][a+1]);)0<=this.pl90[this.plc4-1][t][a]&&(this.pl90[this.plc4][t][a]=0,this.pl90[this.plc4][b-
t][a]=0,this.pl90[this.plc4][t][d-a]=0,this.pl90[this.plc4][b-t][d-a]=0),t++}this.pl90[f-1-this.plc4]=this.pl90[this.plc4]}return this.plc4>=h};pl6d.prototype.pl5b=function(a,b){var d,e,f,g=a.length,k=a[0].length;for(e=0;e<k;e++){for(d=0;d<g&&-1==a[d][e];)d++;if(!(d>=g)){for(;d<g&&1<=a[d][e];)d++;for(f=g-d;d<f;)a[d++][e]=b}}};
pl6d.prototype.pl5c=function(a,b){var d=Math.floor((a.length+1)/2),e=Math.floor((a[0].length+1)/2),f,g,k,h=a.length-1,n=a[0].length-1;for(g=0;g<e;g++){for(f=0;f<d&&-1==a[f][g];)f++;if(!(f>=d-1)){for(;f<d&&1<=a[f][g];)f++;if(!(f>=d-1)){for(k=f+1;k<d&&-1==a[k][g];)k++;if(!(k>=d))for(;f<=d&&-1==a[f][g];)a[f][g]=b,a[f][n-g]=b,a[h-f][g]=b,a[h-f][n-g]=b,f++}}}for(f=0;f<d;f++){for(g=0;g<e&&-1==a[f][g];)g++;if(!(g>=e-1)){for(;g<e&&1<=a[f][g];)g++;if(!(g>=e-1)){for(k=g+1;k<e&&-1==a[f][k];)k++;if(!(k>=e))for(;g<
e&&-1==a[f][g];)a[f][g]=b,a[f][n-g]=b,a[h-f][g]=b,a[h-f][n-g]=b,g++}}}};pl6d.prototype.pl5d=function(a,b,d,e){var f=b+e;e=d+e;for(var g,k=0;b<f;b++)for(g=d;g<e;g++)0<a[b][g]&&k++;return k};pl6d.prototype.pl5e=function(a,b,d){var e,f;for(e=0;e<b;e++){var g="";for(f=0;f<d;f++)g+=0<a[e][f]?"*":"-";console.log(g)}};pl6d.prototype.pl5f=function(a,b,d,e,f){for(var g,k,h,n;b<a.length;b++){h=e;for(g=0;g<a.length;g++){n=f;for(k=0;k<a.length;k++)this.pl90[d][h][n++]=a[b][g][k];h++}d++}};
pl6d.prototype.pl60=function(a,b){var d,e;for(d=0;d<a.length;d++)for(e=0;e<a[d].length;e++)b[d][e]=a[d][e]};pl6d.prototype.pl61=function(a,b){var d,e;for(d=0;d<a.length;d++)for(e=0;e<a[d].length;e++)b[d][e]=0<a[d][e]?0:b[d][e]};
pl6d.prototype.pl62=function(a,b,d,e,f){var g,k,h,n;var m=a.length;var l=b.length;var r=d+l<=m?d+l:m;m=a[0].length;l=b[0].length;var q=e+l<=m?e+l:m;m=a[0][0].length;l=b[0][0].length;m=f+l<=m?f+l:m;for(l=h=n=0;d<r;d++){for(g=e;g<q;g++){for(k=f;k<m;k++){var u=b[l][h][n];var v=a[d][g][k];-1==v&&(a[d][g][k]=u);n++}h++;n=0}l++;h=0}};
pl6d.prototype.pl63=function(a,b,d,e,f){var g,k,h,n;var m=a.length;var l=b.length;var r=d+l<=m?d+l:m;m=a[0].length;l=b[0].length;var q=e+l<=m?e+l:m;m=a[0][0].length;l=b[0][0].length;m=f+l<=m?f+l:m;for(l=h=n=0;d<r;d++){for(g=e;g<q;g++){for(k=f;k<m;k++){var u=b[l][h][n];a[d][g][k]=u;n++}h++;n=0}l++;h=0}};pl6d.prototype.pl64=function(a,b,d){b=Math.floor(a*b);return b%2!=a%2?d?b+1:b-1:b};
pl6d.prototype.pl65=function(a,b,d){var e,f,g;for(e=0;e<a.length;e++)for(f=0;f<a[0].length;f++)if(0<a[e][f])for(g=this.pl90[0].length-1;0<=g;){if(0<this.pl90[b+f][g][d+e]){this.pl90[b+f][g][d+e]=a[e][f];break}g--}};
